PSSYSP ;BIR/WRT-Pharmacy system site parameters routine ;09/02/97
 ;;1.0;PHARMACY DATA MANAGEMENT;**20,38**;9/30/97
 ; IV IDENTIFIER
 ;D ENIVID^PSSHL1
 ; CHANGE TYPE OF ORDER (FINISH) FROM OERR
 W ! S DIE="^PS(59.7,",DR="13;14",DA=1 D ^DIE
 K DIE,DA,DR W !
 Q
