ACRF12EN ;IHS/OIRM/DSD/AEF - PATCH 12 ENVIRONMENT CHECK ROUTINE [ 10/14/2004  10:14 AM ]
 ;;2.1;ADMIN RESOURCE MGT SYSTEM;**12**;NOV 05, 2001
 ;
EN ;EP -- MAIN ENTRY POINT
 ;
 ;CALL GENERIC EN^ACRFPENV(ACRPCHN,ACRPCHS,.XPDQUIT) ENVIRONMENT
 ;CHECK ROUTINE
 ;
 ;      WHERE:
 ;      ACRPCHN  =  PATCH NAME
 ;      ACRPCHS  =  PREREQUISITE PATCH NUMBERS
 ;      XPDQUIT  =  KIDS INSTALL TERMINATOR VARIABLE OUTPUT
 ;                  1 = QUIT
 ;
 K XPDQUIT
 ;
 S ACRPCHN="ACR*2.1*12"
 S ACRPCHS="1,2,3,4,5,6,7,8"          ;CHANGE AS NEEDED
 ;
 D EN^ACRFPENV(ACRPCHN,ACRPCHS,.XPDQUIT)
 ;
 Q
