ACRRR ; GENERATED FROM 'ACR RECEIVING REPORT' PRINT TEMPLATE (#3898) ; 09/29/09 ; (FILE 9002196, MARGIN=80)
 G BEGIN
N W !
T W:$X ! I '$D(DIOT(2)),DN,$D(IOSL),$S('$D(DIWF):1,$P(DIWF,"B",2):$P(DIWF,"B",2),1:1)+$Y'<IOSL,$D(^UTILITY($J,1))#2,^(1)?1U1P1E.E X ^(1)
 S DISTP=DISTP+1,DILCT=DILCT+1 D:'(DISTP#100) CSTP^DIO2
 Q
DT I $G(DUZ("LANG"))>1,Y W $$OUT^DIALOGU(Y,"DD") Q
 I Y W $P("JAN^FEB^MAR^APR^MAY^JUN^JUL^AUG^SEP^OCT^NOV^DEC",U,$E(Y,4,5))_" " W:Y#100 $J(Y#100\1,2)_"," W Y\10000+1700 W:Y#1 "  "_$E(Y_0,9,10)_":"_$E(Y_"000",11,12) Q
 W Y Q
M D @DIXX
 Q
BEGIN ;
 S:'$D(DN) DN=1 S DISTP=$G(DISTP),DILCT=$G(DILCT)
 I $D(DXS)<9 M DXS=^DIPT(3898,"DXS")
 S I(0)="^ACRDOC(",J(0)=9002196
 S ACRREPDA=$O(^ACRRR("AD",D0,ACRRRNO,0)) K DIP K:DN Y
 I $E($G(IOST),1,2)="C-" W !,"ARMS REF: ",$P($G(^ACRDOC(D0,0)),U,6),"/",D0 K DIP K:DN Y
 I 1 S:'$D(ACRPAGE) ACRPAGE=1 K DIP K:DN Y
 D N:$X>0 Q:'DN  W ?0 W "INDIAN HEALTH SERVICE"
 D N:$X>64 Q:'DN  W ?64 W "PAGE: "
 W ACRPAGE K DIP K:DN Y
 D N:$X>0 Q:'DN  W ?0 W "** "
 I 1 S ACRFINAL="" K DIP K:DN Y
 X DXS(1,9) K DIP K:DN Y
 W $S(ACRFINAL=1:"FINAL",ACRFINAL=2:"PARTIAL",1:"PENDING") K DIP K:DN Y
 W ?5 W " ** RECEIVING AND INSPECTION REPORT"
 W ?42 W:$D(ACRRRNO) " NO. ",ACRRRNO K DIP K:DN Y
 I $D(ACRACCRU) W ?$X+3,"(ACCRUAL POSTED)" K ACRACCRU K DIP K:DN Y
 D T Q:'DN  D N W ?0 W "PURCHASE ORDER NO.:"
 S X=$G(^ACRDOC(D0,0)) W ?21,$E($P(X,U,2),1,15)
 D N:$X>4 Q:'DN  W ?4 W "DHHS ORDER NO.:  "
 W $$EXPDN^ACRFUTL(D0) K DIP K:DN Y
 D N:$X>39 Q:'DN  W ?39 W "ORDER DATE:"
 S X=$G(^ACRDOC(D0,"PO")) W ?52 S Y=$P(X,U,1) D DT
 X DXS(2,9) K DIP K:DN Y
 D T Q:'DN  D N W ?0 W "VENDOR:"
 D N:$X>39 Q:'DN  W ?39 W "RECEIVING LOCATION:"
 S X=$G(^ACRDOC(D0,"PO")) D N:$X>0 Q:'DN  W ?0 S Y=$P(X,U,5) S Y=$S(Y="":Y,$D(^AUTTVNDR(Y,0))#2:$P(^(0),U),1:Y) W $E(Y,1,25)
 D N:$X>26 Q:'DN  W ?26 X DXS(3,9.2) S X=$P(DIP(101),U,13) S D0=I(0,0) K DIP K:DN Y W X
 S X=$G(^ACRDOC(D0,"POST")) D N:$X>39 Q:'DN  W ?39 S Y=$P(X,U,1) S Y=$S(Y="":Y,$D(^AUTTPRG(Y,0))#2:$P(^(0),U),1:Y) W $E(Y,1,30)
 D N:$X>0 Q:'DN  W ?0 X DXS(4,9.2) S X=$P(DIP(101),U,1) S D0=I(0,0) K DIP K:DN Y W X
 D N:$X>39 Q:'DN  W ?39 X DXS(5,9.2) S X=$P(DIP(101),U,1) S D0=I(0,0) K DIP K:DN Y W X
 D N:$X>0 Q:'DN  W ?0 X DXS(6,9.2) S X=$P(DIP(101),U,10) S D0=I(0,0) K DIP K:DN Y W X
 D N:$X>39 Q:'DN  W ?39 X DXS(7,9.2) S X=$P(DIP(101),U,2) S D0=I(0,0) K DIP K:DN Y W X
 D N:$X>0 Q:'DN  W ?0 X DXS(8,9.2) S X=$P(DIP(101),U,2) S D0=I(0,0) K DIP K:DN Y W X
 W ", "
 X DXS(9,9) K DIP K:DN Y W X
 W ?11 W "  "
 X DXS(10,9.2) S X=$P(DIP(101),U,4) S D0=I(0,0) K DIP K:DN Y W X
 D N:$X>39 Q:'DN  W ?39 X DXS(11,9.2) S X=$P(DIP(101),U,3) S D0=I(0,0) K DIP K:DN Y W X
 W ", "
 X DXS(12,9.3) S X=$P(DIP(201),U,2) S D0=I(0,0) K DIP K:DN Y W X
 W "  "
 X DXS(13,9.2) S X=$P(DIP(101),U,5) S D0=I(0,0) K DIP K:DN Y W X
 D N:$X>0 Q:'DN  W ?0 W "PHONE:"
 W ?8 X DXS(14,9.2) S X=$P(DIP(101),U,9) S D0=I(0,0) K DIP K:DN Y W X
 D T Q:'DN  D N W ?0 W "CONTRACT NO.:"
 S X=$G(^ACRDOC(D0,"PO")) W ?15,$E($P(X,U,2),1,15)
 D N:$X>39 Q:'DN  W ?39 W "REQUISITION NO.:"
 S X=$G(^ACRDOC(D0,0)) W ?57,$E($P(X,U,1),1,17)
 D N:$X>0 Q:'DN  W ?0 W "PURCH AGENT.:"
 S X=$G(^ACRDOC(D0,"PA")) W ?15 S Y=$P(X,U,1) S Y=$S(Y="":Y,$D(^ACRPA(Y,0))#2:$P(^(0),U),1:Y) S Y=$S(Y="":Y,$D(^VA(200,Y,0))#2:$P(^(0),U),1:Y) W $E(Y,1,20)
 D N:$X>39 Q:'DN  W ?39 W "ORDERING DEPT..:"
 S X=$G(^ACRDOC(D0,"PO")) W ?57 S Y=$P(X,U,7) S Y=$S(Y="":Y,$D(^AUTTPRG(Y,0))#2:$P(^(0),U),1:Y) W $E(Y,1,22)
 D T Q:'DN  D N W ?0 W "F.O.B. POINT:"
 W ?15 S Y=$P(X,U,9) W:Y]"" $S($D(DXS(15,Y)):DXS(15,Y),1:Y)
 D N:$X>39 Q:'DN  W ?39 W "GBL NO.:"
 W ?49,$E($P(X,U,10),1,10)
 D PAUSE^ACRFWARN K DIP K:DN Y
 D REQOFF^ACRFRRPT,^ACRFRRPT K DIP K:DN Y
 D T Q:'DN  D N W ?0 W "I HEREBY CERTIFY THAT ALL ITEMS LISTED ABOVE WERE RECEIVED, INSPECTED AND"
 D N:$X>0 Q:'DN  W ?0 W "ACCEPTED ON"
 W ?13 W ACRDATE K DIP K:DN Y
 D T Q:'DN  D N W ?0 W "INVOICE NO.:  "
 W $P($G(^ACRDOC(D0,20,+$G(ACRRRNO),0)),U) K DIP K:DN Y
 D N:$X>0 Q:'DN  W ?0 W "REMARKS:"
 D REM^ACRFRRP2(D0,$G(ACRREPDA)) K DIP K:DN Y
 K ACRREPDA K DIP K:DN Y
 W ?10 I 1 W !,ACRDUZ K DIP K:DN Y
 D N:$X>59 Q:'DN  W ?59 W ACRDATE2 K DIP K:DN Y
 D T Q:'DN  D N W ?0 W "PROPERTY VOUCHER NUMBER:"
 W ?$X+2,$G(ACRPVN) K DIP K:DN Y
 D PAUSE^ACRFWARN K DIP K:DN Y
 K Y
 Q
HEAD ;
 W !,"--------------------------------------------------------------------------------",!!
