BGP08 ;IHS/CMI/LAB-CREATED BY ^ATXSTX ON MAY 23, 2010;
 ;;10.0;IHS CLINICAL REPORTING;;JUN 18, 2010
 ;
 ; See referenced routines to see taxonomies being loaded.
 ;
START ;
 D ^BGP08A ;    BGP LVAD/HEART TRANSPLANT PROC
 D ^BGP08B ;    BGP MAJOR DEPRESSION (ADM)
 D ^BGP08C ;    BGP MAJOR DEPRESSION PRIOR
 D ^BGP08D ;    BGP MAJOR DEPRESSIVE DISORDERS
 D ^BGP08E ;    BGP MAMMOGRAM ICDS
 D ^BGP08F ;    BGP MAMMOGRAM PROCEDURES
 D ^BGP08G ;    BGP MASTECTOMY CPTS
 D ^BGP08H ;    BGP MASTECTOMY PROCEDURES
 D ^BGP08I ;    BGP MEASLES EVIDENCE
 D ^BGP08J ;    BGP MH OPT VISIT CPT NMH 1
 D ^BGP08K ;    BGP MH OPT VISIT CPT NMH 3
 D ^BGP08L ;    BGP MICROALBUM LOINC CODES
 D ^BGP08M ;    BGP MISCARRIAGE/ABORTION DXS
 D ^BGP08N ;    BGP MMR CONTRAINDICATIONS
 D ^BGP08O ;    BGP MOOD DISORDERS
 D ^BGP08P ;    BGP MUMPS EVIDENCE
 D ^BGP08Q ;    BGP MYOPATHY/MYALGIA
 D ^BGP08R ;    BGP NEPHROPATHY CPTS
 D ^BGP08S ;    BGP NEPHROPATHY DXS
 D ^BGP08T ;    BGP NEPHROPATHY PROCEDURES
 D ^BGP08U ;    BGP NON-TOBACCO CPTS
 D ^BGP08V ;    BGP OPT MH VISIT CPTS MH
 D ^BGP08W ;    BGP OPT MH VISIT POVS
 D ^BGP08X ;    BGP OPV CONTRAINDICATIONS
 D ^BGP08Y ;    BGP OPV EVID DISEASE
 D ^BGP08Z ;    BGP OSTEO SCREEN CPTS
 Q
