BGP2PHEL ; IHS/CMI/LAB - IHS gpra print ;
 ;;12.0;IHS CLINICAL REPORTING;;JAN 9, 2012;Build 51
 ;
 ;
PRINT ;EP
 S BGPGPG=0
 S BGPIOSL=$S($G(BGPGUI):55,1:IOSL)
 S BGPQUIT=""
 S ^TMP($J,"BGPDEL",0)=0
 S BGPPTYPE="P"
 I BGPROT="D" G DEL
 D AREACP^BGP2ELH
 S BGPQUIT="",BGPGPG=0,BGPRPT=0
 D PRINT1^BGP2DELP
 Q:BGPQUIT
 Q:BGPROT="P"
DEL ;create delimited output file
 S BGPQUIT="",BGPGPG=0,BGPRPT=0
 D ^%ZISC ;close printer device
 K ^TMP($J)
 S BGPPTYPE="D"
 D ^BGP2ELL ;create ^tmp of delimited report
 Q
 ;
