BGP3CP1 ; IHS/CMI/LAB - IHS gpra print ;
 ;;13.0;IHS CLINICAL REPORTING;;NOV 20, 2012;Build 81
 ;
 ;
AMIALL ;EP
 I $Y>(BGPIOSL-3) D HDR^BGP3CP Q:BGPQUIT  D L1H^BGP3CP
 S BGPNOBA=1
 D WRACE^BGP3CPU(DFN)
 Q:BGPQUIT
 D WDOB^BGP3CPU(DFN)
 Q:BGPQUIT
 D WZIP^BGP3CPU(DFN)
 Q:BGPQUIT
 D WINS^BGP3CPU(BGPVSIT,DFN)
 Q:BGPQUIT
 D WADM^BGP3CPU(BGPVINP)
 Q:BGPQUIT
 D WADM92^BGP3CPU(BGPVINP)
 Q:BGPQUIT
 D WADMS92^BGP3CPU(BGPVINP)
 Q:BGPQUIT
 D WDT^BGP3CPU(BGPVINP)
 Q:BGPQUIT
 D WDSGS92^BGP3CPU(BGPVINP)
 Q:BGPQUIT
 I $$TRANS^BGP3CU(BGPVINP) D WTT^BGP3CPU(BGPVINP) Q:BGPQUIT
 K BGPNOBA
 D WPPDPOV^BGP3CPU(BGPVSIT)
 Q:BGPQUIT
 S BGPNOBA=1
 D OTHDPOVS^BGP3CPU(BGPVSIT)
 Q:BGPQUIT
 D WPRINPRO^BGP3CPU2
 Q:BGPQUIT
 D WOTHPROS^BGP3CPU2
 K BGPNOBA
 Q
 ;
AMI1 ;EP
 I $Y>(BGPIOSL-3) D HDR^BGP3CP Q:BGPQUIT  D L1H^BGP3CP
 I $$TRANSIN^BGP3CU(BGPVINP) D TRANSIN^BGP3CP3 Q:BGPQUIT
 D WDT^BGP3CPU(BGPVINP)
 Q:BGPQUIT
 I $$TRANS^BGP3CU(BGPVINP) D WTT^BGP3CPU(BGPVINP)
 Q:BGPQUIT
 I $$TRANS^BGP3CU(BGPVINP),$$DODA^BGP3CU(BGPVSIT,BGPVINP) D TRANSN^BGP3CP2 Q:BGPQUIT
 D WPPDPOV^BGP3CPU(BGPVSIT)
 Q:BGPQUIT
 D OTHDPOVS^BGP3CPU(BGPVSIT)
 Q:BGPQUIT
 S X=$$COMFORT^BGP3CU(DFN,$P($P(^AUPNVSIT(BGPVSIT,0),U),"."),$P($P(^AUPNVINP(BGPVINP,0),U),"."))
 D WCOMFORT^BGP3CPU(X)
 Q:BGPQUIT
 K BGPY,BGPDATA
 D NMIDRUG^BGP3CU1(DFN,$$FMADD^XLFDT($P($P(^AUPNVSIT(BGPVSIT,0),U),"."),-1),$P($P(^AUPNVINP(BGPVINP,0),U),"."),.BGPDATA,"DM AUDIT ASPIRIN DRUGS",0)
 D WNMIASP^BGP3CPU
 Q:BGPQUIT
 K X
 S X=$$LASTMED^BGP3CU1(DFN,$$FMADD^XLFDT($P($P(^AUPNVSIT(BGPVSIT,0),U),"."),-365),$$FMADD^XLFDT($P($P(^AUPNVINP(BGPVINP,0),U),"."),30),"DM AUDIT ASPIRIN DRUGS") I X]"" S X="Last Outpatient Rx: "_X
 K BGPUD
 D IVUD^BGP3CU1(DFN,$P($P(BGPVSIT0,U),"."),$$DSCH^BGP3CU(BGPVINP),$O(^ATXAX("B","DM AUDIT ASPIRIN DRUGS",0)),.BGPUD)
 D WLASTASP^BGP3CPU
 Q:BGPQUIT
 S X=$$LASTASPC^BGP3CU1(DFN,$$FMADD^XLFDT($P($P(^AUPNVSIT(BGPVSIT,0),U),"."),-365),$$FMADD^XLFDT($P($P(^AUPNVINP(BGPVINP,0),U),"."),30))
 D WASPCPT^BGP3CPU(X)
 Q:BGPQUIT
 S X=$$LASTMED^BGP3CU1(DFN,$$FMADD^XLFDT($P($P(^AUPNVSIT(BGPVSIT,0),U),"."),-365),$$FMADD^XLFDT($P($P(^AUPNVINP(BGPVINP,0),U),"."),30),"BGP ANTI-PLATELET DRUGS","","BGP CMS ANTI-PLATELET CLASS") I X]"" S X="Last Outpatient Rx: "_X
 K BGPUD
 D IVUD^BGP3CU1(DFN,$P($P(BGPVSIT0,U),"."),$$DSCH^BGP3CU(BGPVINP),$O(^ATXAX("B","BGP ANTI-PLATELET DRUGS",0)),.BGPUD,$O(^ATXAX("B","BGP ANTI-PLATELET DRUGS",0)))
 D WLASTAP^BGP3CPU
 Q:BGPQUIT
 D ALLALG1^BGP3CU1(DFN,DT,$$DSCH^BGP3CU(BGPVINP),.BGPDATA)
 D WALLALG^BGP3CPU
 Q:BGPQUIT
 K BGPDATA
 D ALLALGA1^BGP3CU1(DFN,DT,.BGPDATA)
 D WALLALGT^BGP3CPU
 K BGPDATA
 D IVUD^BGP3CU1(DFN,$P($P(BGPVSIT0,U),"."),$$DSCH^BGP3CU(BGPVINP),,.BGPDATA)
 D WIVUD^BGP3CPU
 Q
AMI1W ;EP
 I $Y>(BGPIOSL-3) D HDR^BGP3CP Q:BGPQUIT  D L1H^BGP3CP
 I $$TRANSIN^BGP3CU(BGPVINP) D TRANSIN^BGP3CP3 Q:BGPQUIT
 D WDOD^BGP3CPU(DFN)
 Q:BGPQUIT
 D WDT^BGP3CPU(BGPVINP)
 Q:BGPQUIT
 I $$TRANS^BGP3CU(BGPVINP) D WTT^BGP3CPU(BGPVINP)
 Q:BGPQUIT
 I $$TRANS^BGP3CU(BGPVINP),$$DODA^BGP3CU(BGPVSIT,BGPVINP) D TRANSN^BGP3CP2 Q:BGPQUIT
 D WPPDPOV^BGP3CPU(BGPVSIT)
 Q:BGPQUIT
 D OTHDPOVS^BGP3CPU(BGPVSIT)
 Q:BGPQUIT
 S X=$$COMFORT^BGP3CU(DFN,$P($P(^AUPNVSIT(BGPVSIT,0),U),"."),$P($P(^AUPNVINP(BGPVINP,0),U),"."))
 D WCOMFORT^BGP3CPU(X)
 Q:BGPQUIT
 S X=$$ASAALLEG^BGP3CU1(DFN,$$DOB^AUPNPAT(DFN),$$DSCH^BGP3CU(BGPVINP)),X=$P(X,U,2,999)
 D WASAALEG^BGP3CPU
 Q:BGPQUIT
 K BGPDATA
 D WARRX^BGP3CU1(DFN,$$FMADD^XLFDT($P($P(^AUPNVSIT(BGPVSIT,0),U),"."),-180),$P($P(^AUPNVSIT(BGPVSIT,0),U),"."),1,.BGPDATA)
 D WWARRX^BGP3CPU
 Q:BGPQUIT
 K BGPDATA,BGPY
 D NMIDRUG^BGP3CU1(DFN,$P($P(^AUPNVSIT(BGPVSIT,0),U),"."),$P($P(^AUPNVINP(BGPVINP,0),U),"."),.BGPDATA,"DM AUDIT ASPIRIN DRUGS",0)
 D WNMIASP^BGP3CPU
 Q:BGPQUIT
 K X
 S X=$$LASTMED^BGP3CU1(DFN,$$FMADD^XLFDT($P($P(^AUPNVSIT(BGPVSIT,0),U),"."),-365),$$FMADD^XLFDT($P($P(^AUPNVINP(BGPVINP,0),U),"."),30),"DM AUDIT ASPIRIN DRUGS") I X]"" S X="Last Outpatient Rx: "_X
 K BGPUD
 D IVUD^BGP3CU1(DFN,$P($P(BGPVSIT0,U),"."),$$DSCH^BGP3CU(BGPVINP),$O(^ATXAX("B","DM AUDIT ASPIRIN DRUGS",0)),.BGPUD)
 D WLASTASP^BGP3CPU
 Q:BGPQUIT
 S X=$$LASTASPC^BGP3CU1(DFN,$$FMADD^XLFDT($P($P(^AUPNVSIT(BGPVSIT,0),U),"."),-365),$$FMADD^XLFDT($P($P(^AUPNVINP(BGPVINP,0),U),"."),30))
 D WASPCPT^BGP3CPU(X)
 Q:BGPQUIT
 S X=$$LASTMED^BGP3CU1(DFN,$$FMADD^XLFDT($P($P(^AUPNVSIT(BGPVSIT,0),U),"."),-365),$$FMADD^XLFDT($P($P(^AUPNVINP(BGPVINP,0),U),"."),30),"BGP ANTI-PLATELET DRUGS","","BGP CMS ANTI-PLATELET CLASS") I X]"" S X="Last Outpatient RX: "_X
 K BGPUD
 D IVUD^BGP3CU1(DFN,$P($P(BGPVSIT0,U),"."),$$DSCH^BGP3CU(BGPVINP),$O(^ATXAX("B","BGP ANTI-PLATELET DRUGS",0)),.BGPUD,$O(^ATXAX("B","BGP ANTI-PLATELET DRUGS",0)))
 D WLASTAP^BGP3CPU
 Q:BGPQUIT
 D ALLALG1^BGP3CU1(DFN,DT,$$DSCH^BGP3CU(BGPVINP),.BGPDATA)
 D WALLALG^BGP3CPU
 Q:BGPQUIT
 K BGPDATA
 D ALLALGA1^BGP3CU1(DFN,DT,.BGPDATA)
 D WALLALGT^BGP3CPU
 Q:BGPQUIT
 K BGPDATA
 D IVUD^BGP3CU1(DFN,$P($P(BGPVSIT0,U),"."),$$DSCH^BGP3CU(BGPVINP),,.BGPDATA)
 D WIVUD^BGP3CPU
 Q
AMI2 ;EP
 I $Y>(BGPIOSL-3) D HDR^BGP3CP Q:BGPQUIT  D L1H^BGP3CP
 D WDT^BGP3CPU(BGPVINP)
 Q:BGPQUIT
 I $$TRANS^BGP3CU(BGPVINP) D WTT^BGP3CPU(BGPVINP)
 Q:BGPQUIT
 I $$TRANS^BGP3CU(BGPVINP) D TRANSN^BGP3CP2 Q:BGPQUIT
 D WPPDPOV^BGP3CPU(BGPVSIT)
 Q:BGPQUIT
 D OTHDPOVS^BGP3CPU(BGPVSIT)
 Q:BGPQUIT
 S X=$$COMFORT^BGP3CU(DFN,$P($P(^AUPNVSIT(BGPVSIT,0),U),"."),$P($P(^AUPNVINP(BGPVINP,0),U),"."))
 D WCOMFORT^BGP3CPU(X)
 Q:BGPQUIT
 K BGPY,BGPDATA
 D NMIDRUG^BGP3CU1(DFN,$P($P(^AUPNVSIT(BGPVSIT,0),U),"."),$P($P(^AUPNVINP(BGPVINP,0),U),"."),.BGPDATA,"DM AUDIT ASPIRIN DRUGS",0)
 D WNMIASP^BGP3CPU
 Q:BGPQUIT
 S X=$$LASTMED^BGP3CU1(DFN,$$FMADD^XLFDT($P($P(^AUPNVSIT(BGPVSIT,0),U),"."),-365),$$FMADD^XLFDT($P($P(^AUPNVINP(BGPVINP,0),U),"."),30),"DM AUDIT ASPIRIN DRUGS") I X]"" S X="Last Outpatient Rx: "_X
 K BGPUD
 D IVUD^BGP3CU1(DFN,$P($P(BGPVSIT0,U),"."),$$DSCH^BGP3CU(BGPVINP),$O(^ATXAX("B","DM AUDIT ASPIRIN DRUGS",0)),.BGPUD)
 D WLASTASP^BGP3CPU
 Q:BGPQUIT
 S X=$$LASTASPC^BGP3CU1(DFN,$$FMADD^XLFDT($P($P(^AUPNVSIT(BGPVSIT,0),U),"."),-365),$$FMADD^XLFDT($P($P(^AUPNVINP(BGPVINP,0),U),"."),30))
 D WASPCPT^BGP3CPU(X)
 Q:BGPQUIT
 S X=$$LASTMED^BGP3CU1(DFN,$$FMADD^XLFDT($P($P(^AUPNVSIT(BGPVSIT,0),U),"."),-365),$$FMADD^XLFDT($P($P(^AUPNVINP(BGPVINP,0),U),"."),30),"BGP ANTI-PLATELET DRUGS","","BGP CMS ANTI-PLATELET CLASS") I X]"" S X="Last Outpatient RX: "_X
 K BGPUD
 D IVUD^BGP3CU1(DFN,$P($P(BGPVSIT0,U),"."),$$DSCH^BGP3CU(BGPVINP),$O(^ATXAX("B","BGP ANTI-PLATELET DRUGS",0)),.BGPUD,$O(^ATXAX("B","BGP ANTI-PLATELET DRUGS",0)))
 D WLASTAP^BGP3CPU
 Q:BGPQUIT
 D ALLALG1^BGP3CU1(DFN,DT,$$DSCH^BGP3CU(BGPVINP),.BGPDATA)
 D WALLALG^BGP3CPU
 Q:BGPQUIT
 K BGPDATA
 D ALLALGA1^BGP3CU1(DFN,DT,.BGPDATA)
 D WALLALGT^BGP3CPU
 K BGPDATA
 D IVUD^BGP3CU1(DFN,$P($P(BGPVSIT0,U),"."),$$DSCH^BGP3CU(BGPVINP),,.BGPDATA)
 D WIVUD^BGP3CPU
 Q
AMI2W ;EP
 I $Y>(BGPIOSL-3) D HDR^BGP3CP Q:BGPQUIT  D L1H^BGP3CP
 D WDOD^BGP3CPU(DFN)
 Q:BGPQUIT
 D WDT^BGP3CPU(BGPVINP)
 Q:BGPQUIT
 I $$TRANS^BGP3CU(BGPVINP) D WTT^BGP3CPU(BGPVINP)
 Q:BGPQUIT
 I $$TRANS^BGP3CU(BGPVINP) D TRANSN^BGP3CP2 Q:BGPQUIT
 D WPPDPOV^BGP3CPU(BGPVSIT)
 Q:BGPQUIT
 D OTHDPOVS^BGP3CPU(BGPVSIT)
 Q:BGPQUIT
 S X=$$COMFORT^BGP3CU(DFN,$P($P(^AUPNVSIT(BGPVSIT,0),U),"."),$P($P(^AUPNVINP(BGPVINP,0),U),"."))
 D WCOMFORT^BGP3CPU(X)
 Q:BGPQUIT
 S X=$$ASAALLEG^BGP3CU1(DFN,$$DOB^AUPNPAT(DFN),$$DSCH^BGP3CU(BGPVINP))
 D WASAALEG^BGP3CPU
 Q:BGPQUIT
 K BGPDATA
 D WARRX^BGP3CU1(DFN,$P($P(^AUPNVINP(BGPVINP,0),U),"."),$P($P(^AUPNVINP(BGPVINP,0),U),"."),1,.BGPDATA)
 D WWARRX^BGP3CPU
 Q:BGPQUIT
 K BGPDATA
 D NMIDRUG^BGP3CU1(DFN,$P($P(^AUPNVSIT(BGPVSIT,0),U),"."),$P($P(^AUPNVINP(BGPVINP,0),U),"."),.BGPDATA,"DM AUDIT ASPIRIN DRUGS",0)
 D WNMIASP^BGP3CPU
 Q:BGPQUIT
 S X=$$LASTMED^BGP3CU1(DFN,$$FMADD^XLFDT($P($P(^AUPNVSIT(BGPVSIT,0),U),"."),-365),$$FMADD^XLFDT($P($P(^AUPNVINP(BGPVINP,0),U),"."),30),"DM AUDIT ASPIRIN DRUGS") I X]"" S X="Last Outpatient Rx: "_X
 K BGPUD
 D IVUD^BGP3CU1(DFN,$P($P(BGPVSIT0,U),"."),$$DSCH^BGP3CU(BGPVINP),$O(^ATXAX("B","DM AUDIT ASPIRIN DRUGS",0)),.BGPUD)
 D WLASTASP^BGP3CPU
 Q:BGPQUIT
 S X=$$LASTASPC^BGP3CU1(DFN,$P($P(^AUPNVINP(BGPVINP,0),U),"."),$P($P(^AUPNVINP(BGPVINP,0),U),"."))
 D WASPCPT^BGP3CPU(X)
 Q:BGPQUIT
 S X=$$LASTMED^BGP3CU1(DFN,$$FMADD^XLFDT($P($P(^AUPNVSIT(BGPVSIT,0),U),"."),-365),$$FMADD^XLFDT($P($P(^AUPNVINP(BGPVINP,0),U),"."),30),"BGP ANTI-PLATELET DRUGS","","BGP CMS ANTI-PLATELET CLASS") I X]"" S X="Last Outpatient RX: "_X
 K BGPUD
 D IVUD^BGP3CU1(DFN,$P($P(BGPVSIT0,U),"."),$$DSCH^BGP3CU(BGPVINP),$O(^ATXAX("B","BGP ANTI-PLATELET DRUGS",0)),.BGPUD,$O(^ATXAX("B","BGP ANTI-PLATELET DRUGS",0)))
 D WLASTAP^BGP3CPU
 Q:BGPQUIT
 D ALLALG1^BGP3CU1(DFN,DT,$$DSCH^BGP3CU(BGPVINP),.BGPDATA)
 D WALLALG^BGP3CPU
 Q:BGPQUIT
 K BGPDATA
 D ALLALGA1^BGP3CU1(DFN,DT,.BGPDATA)
 D WALLALGT^BGP3CPU
 Q:BGPQUIT
 K BGPDATA
 D IVUD^BGP3CU1(DFN,$P($P(BGPVSIT0,U),"."),$$DSCH^BGP3CU(BGPVINP),,.BGPDATA)
 D WIVUD^BGP3CPU
 Q
AMI3 ;EP
 I $Y>(BGPIOSL-3) D HDR^BGP3CP Q:BGPQUIT  D L1H^BGP3CP
 D WDT^BGP3CPU(BGPVINP)
 Q:BGPQUIT
 I $$TRANS^BGP3CU(BGPVINP) D WTT^BGP3CPU(BGPVINP)
 Q:BGPQUIT
 I $$TRANS^BGP3CU(BGPVINP) D TRANSN^BGP3CP2 Q:BGPQUIT
 D WPPDPOV^BGP3CPU(BGPVSIT)
 Q:BGPQUIT
 D OTHDPOVS^BGP3CPU(BGPVSIT)
 Q:BGPQUIT
 K BGPDATA
 S BGPC=0
 D LVSD^BGP3CU1(DFN,$$FMADD^XLFDT($$DSCH^BGP3CU(BGPVINP),-365),$$DSCH^BGP3CU(BGPVINP),.BGPDATA,0)
 D EJECFRAC^BGP3CU1(DFN,$$FMADD^XLFDT($$DSCH^BGP3CU(BGPVINP),-365),$$DSCH^BGP3CU(BGPVINP),.BGPDATA,BGPC)
 D WLVSD^BGP3CPU
 Q:BGPQUIT
 K BGPDATA
 S X=$$COMFORT^BGP3CU(DFN,$P($P(^AUPNVSIT(BGPVSIT,0),U),"."),$P($P(^AUPNVINP(BGPVINP,0),U),"."))
 D WCOMFORT^BGP3CPU(X)
 Q:BGPQUIT
 K BGPDATA,BGPDX
 S BGPXX=0
 D ANGIOED^BGP3CU6(DFN,$$FMADD^XLFDT($$DSCH^BGP3CU(BGPVINP),-365),$$DSCH^BGP3CU(BGPVINP),.BGPDATA,0)
 S X=0 F  S X=$O(BGPDATA(X)) Q:X'=+X  S BGPXX=BGPXX+1,BGPDX(BGPXX)=BGPDATA(X)
 K BGPDATA D HYPERKAL^BGP3CU6(DFN,$$FMADD^XLFDT($$DSCH^BGP3CU(BGPVINP),-365),$$DSCH^BGP3CU(BGPVINP),.BGPDATA,0)
 S X=0 F  S X=$O(BGPDATA(X)) Q:X'=+X  S BGPXX=BGPXX+1,BGPDX(BGPXX)=BGPDATA(X)
 K BGPDATA D HYPOTEN^BGP3CU6(DFN,$$FMADD^XLFDT($$DSCH^BGP3CU(BGPVINP),-365),$$DSCH^BGP3CU(BGPVINP),.BGPDATA,0)
 S X=0 F  S X=$O(BGPDATA(X)) Q:X'=+X  S BGPXX=BGPXX+1,BGPDX(BGPXX)=BGPDATA(X)
 K BGPDATA D RENART^BGP3CU6(DFN,$$FMADD^XLFDT($$DSCH^BGP3CU(BGPVINP),-365),$$DSCH^BGP3CU(BGPVINP),.BGPDATA,0)
 S X=0 F  S X=$O(BGPDATA(X)) Q:X'=+X  S BGPXX=BGPXX+1,BGPDX(BGPXX)=BGPDATA(X)
 K BGPDATA D RENAL^BGP3CU6(DFN,$$FMADD^XLFDT($$DSCH^BGP3CU(BGPVINP),-365),$$DSCH^BGP3CU(BGPVINP),.BGPDATA,0)
 S X=0 F  S X=$O(BGPDATA(X)) Q:X'=+X  S BGPXX=BGPXX+1,BGPDX(BGPXX)=BGPDATA(X)
 D WDXS^BGP3CPU
 K BGPDATA
 K BGPY
 Q:BGPQUIT
 S X=$$ACEALLEG^BGP3CU1(DFN,$$DOB^AUPNPAT(DFN),$$DSCH^BGP3CU(BGPVINP))
 S Z=$$ARBALLEG^BGP3CU1(DFN,$$DOB^AUPNPAT(DFN),$$DSCH^BGP3CU(BGPVINP))
 D WACEALEG^BGP3CPU
 Q:BGPQUIT
 K BGPDATA
 S BGPC=0
 D NMIDRUG^BGP3CU1(DFN,$P($P(^AUPNVSIT(BGPVSIT,0),U),"."),$P($P(^AUPNVINP(BGPVINP,0),U),"."),.BGPDATA,"BGP CMS ACEI MEDS",0)
 D NMIDRUG^BGP3CU1(DFN,$P($P(^AUPNVSIT(BGPVSIT,0),U),"."),$P($P(^AUPNVINP(BGPVINP,0),U),"."),.BGPDATA,"BGP CMS ARB MEDS",BGPC)
 D WNMIACE^BGP3CPU(.BGPDATA)
 Q:BGPQUIT
 S X=$$LASTMED^BGP3CU1(DFN,$$FMADD^XLFDT($P($P(^AUPNVSIT(BGPVSIT,0),U),"."),-365),$$FMADD^XLFDT($P($P(^AUPNVINP(BGPVINP,0),U),"."),30),"BGP CMS ACEI MEDS","","BGP CMS ACEI MEDS CLASS")
 S Z=$$LASTMED^BGP3CU1(DFN,$$FMADD^XLFDT($P($P(^AUPNVSIT(BGPVSIT,0),U),"."),-365),$$FMADD^XLFDT($P($P(^AUPNVINP(BGPVINP,0),U),"."),30),"BGP CMS ARB MEDS","","BGP CMS ARB MEDS CLASS")
 D WLASTACE^BGP3CPU
 Q:BGPQUIT
 D ALLALG1^BGP3CU1(DFN,DT,$$DSCH^BGP3CU(BGPVINP),.BGPDATA)
 D WALLALG^BGP3CPU
 Q:BGPQUIT
 K BGPDATA
 D ALLALGA1^BGP3CU1(DFN,DT,.BGPDATA)
 D WALLALGT^BGP3CPU
 K BGPDATA
 D IVUD^BGP3CU1(DFN,$P($P(BGPVSIT0,U),"."),$$DSCH^BGP3CU(BGPVINP),,.BGPDATA)
 D WIVUD^BGP3CPU
 Q
 ;
AMI3W ;EP
 D AMI3W^BGP3CP11
 Q
