BGP3DP7 ; IHS/CMI/LAB - print ind ;
 ;;7.0;IHS CLINICAL REPORTING;;JAN 24, 2007
 ;
 ;
ID ;EP
 D H1^BGP3DPH
 F BGPPC1="D.A","D.B","D.C","D.D","D.E","D.F" Q:BGPQUIT  D PI
 Q
IE1 ;EP
 D H1^BGP3DPH
 F BGPPC1="E-1.A" Q:BGPQUIT  D PI
 Q
IE2 ;E[
 D H1^BGP3DPH
 F BGPPC1="E-2.A" Q:BGPQUIT  D PI
 Q
IG ;EP
 D H1^BGP3DPH
 F BGPPC1="G.A","G.B" Q:BGPQUIT  D PI
 Q
II ;EP
 D H1^BGP3DPH
 F BGPPC1="I.A","I.B","I.E","I.F" Q:BGPQUIT  D PI
 Q
J1 ;EP
 D H1^BGP3DPH
 F BGPPC1="J-1.A","J-1.B","J-1.C" Q:BGPQUIT  D PI
 Q
J2 ;
 D H1^BGP3DPH
 F BGPPC1="J-2.A","J-2.B","J-2.C" Q:BGPQUIT  D PI
 Q
J3 ;
 D H1^BGP3DPH
 F BGPPC1="J-3.A","J-3.B","J-3.C" Q:BGPQUIT  D PI
 Q
J4 ;EP
 D H1^BGP3DPH
 F BGPPC1="J-4.A","J-4.B","J-4.C" Q:BGPQUIT  D PI
 Q
J5 ;EP
 D H1^BGP3DPH
 F BGPPC1="J-5.A","J-5.B","J-5.C" Q:BGPQUIT  D PI
 Q
J6 ;EP
 D H1^BGP3DPH
 F BGPPC1="J-6.A","J-6.B","J-6.C" Q:BGPQUIT  D PI
 Q
PI ;EP
 S BGPPC=$O(^BGPINDC("AA",BGPPC1,0))
 I BGPRTYPE'=4,BGPINDT="G",$P(^BGPINDC(BGPPC,0),U,5)'=1 Q
 I BGPRTYPE'=4,BGPINDT="A",$P(^BGPINDC(BGPPC,0),U,6)'=1 Q
 I BGPINDT="D",$P(^BGPINDC(BGPPC,0),U,12)'=1 Q
 I BGPINDT="C",$P(^BGPINDC(BGPPC,0),U,13)'=1 Q
 S BGPDF=$P(^BGPINDC(BGPPC,0),U,8)
 ;get denominator value of indicator
 S BGPNP=$P(^DD(90243,BGPDF,0),U,4),N=$P(BGPNP,";"),P=$P(BGPNP,";",2)
 S BGPCYD=$$V(1,BGPRPT,N,P)
 S BGPPRD=$$V(2,BGPRPT,N,P)
 S BGPBLD=$$V(3,BGPRPT,N,P)
 ;write out denominator
 I BGPPC1="025.E" D HEADER^BGP3DPH Q:BGPQUIT  W !!,^BGPIND(BGPIC,53,1,0) D H1^BGP3DPH
 I BGPRTYPE=4,BGPPC1="D.D"!(BGPPC1="J-1.B")!(BGPPC1="J-2.B")!(BGPPC1="J-3.B")!(BGPPC1="J-4.B") D HEADER^BGP3DPH Q:BGPQUIT  W !!,^BGPIND(BGPIC,53,1,0) D H1^BGP3DPH
 I BGPRTYPE=4,BGPPC1="I.E" D HEADER^BGP3DPH Q:BGPQUIT  W !!,^BGPIND(BGPIC,53,1,0) D H1^BGP3DPH
 I $Y>(IOSL-13) D HEADER^BGP3DPH Q:BGPQUIT  W !!,^BGPIND(BGPIC,53,1,0) D H1^BGP3DPH
 I BGPPC1="025.D" W !
 I BGPPC1="026.C" W !
 I BGPPC1="026.B" W !
 I BGPPC1="I.B"!(BGPPC1="I.F") G NEXT
 I BGPRTYPE=4 W !!,$P(^BGPINDC(BGPPC,0),U,17) I $P(^BGPINDC(BGPPC,0),U,18)]"" W !,$P(^BGPINDC(BGPPC,0),U,18) I $P(^BGPINDC(BGPPC,0),U,21)]"" W !,$P(^BGPINDC(BGPPC,0),U,21)
 I BGPRTYPE=1 W !!,$P(^BGPINDC(BGPPC,11),U,1) I $P(^BGPINDC(BGPPC,11),U,2)]"" W !,$P(^BGPINDC(BGPPC,11),U,2) I $P(^BGPINDC(BGPPC,11),U,3)]"" W !,$P(^BGPINDC(BGPPC,11),U,3)
 I BGPRTYPE=2 W !!,$P(^BGPINDC(BGPPC,11),U,4) I $P(^BGPINDC(BGPPC,11),U,5)]"" W !,$P(^BGPINDC(BGPPC,11),U,5) I $P(^BGPINDC(BGPPC,11),U,6)]"" W !,$P(^BGPINDC(BGPPC,11),U,6)
 W ?20,$$C(BGPCYD,0,8),?35,$$C(BGPPRD,0,8),?58,$$C(BGPBLD,0,8),!
NEXT ;get numerator value of indicator and calc %
 S BGPPC2=0 F  S BGPPC2=$O(^BGPINDC("AA",BGPPC1,BGPPC2))  Q:BGPPC2'=+BGPPC2!(BGPQUIT)  D PROC
 Q
PROC ;
 I $P(^BGPINDC(BGPPC2,0),U,4)["031"!($P(^BGPINDC(BGPPC2,0),U,4)["C-")!($P(^BGPINDC(BGPPC2,0),U,4)["I.") D
 .S BGPDF=$P(^BGPINDC(BGPPC2,0),U,8)
 .;get denominator value of indicator
 .S BGPNP=$P(^DD(90243,BGPDF,0),U,4),N=$P(BGPNP,";"),P=$P(BGPNP,";",2)
 .S BGPCYD=$$V(1,BGPRPT,N,P)
 .S BGPPRD=$$V(2,BGPRPT,N,P)
 .S BGPBLD=$$V(3,BGPRPT,N,P)
 S BGPNF=$P(^BGPINDC(BGPPC2,0),U,9)
 S BGPNP=$P(^DD(90243,BGPNF,0),U,4),N=$P(BGPNP,";"),P=$P(BGPNP,";",2)
 D SETN
 ;write header for 1.A.1
 W !!,$P(^BGPINDC(BGPPC2,0),U,15)
 I $P(^BGPINDC(BGPPC2,0),U,16)]"" W !?1,$P(^BGPINDC(BGPPC2,0),U,16)
 I $P(^BGPINDC(BGPPC2,0),U,19)]"" W !?1,$P(^BGPINDC(BGPPC2,0),U,19)
 D H2^BGP3DPH
 Q
SETN ;set numerator fields
 S BGPCYN=$$V(1,BGPRPT,N,P)
 S BGPPRN=$$V(2,BGPRPT,N,P)
 S BGPBLN=$$V(3,BGPRPT,N,P)
 S BGPCYP=$S(BGPCYD:((BGPCYN/BGPCYD)*100),1:"")
 S BGPPRP=$S(BGPPRD:((BGPPRN/BGPPRD)*100),1:"")
 S BGPBLP=$S(BGPBLD:((BGPBLN/BGPBLD)*100),1:"")
 Q
V(T,R,N,P) ;EP
 I $G(BGPAREAA) G VA
 I T=1 Q $P($G(^BGPGPDC(R,N)),U,P)
 I T=2 Q $P($G(^BGPGPDP(R,N)),U,P)
 I T=3 Q $P($G(^BGPGPDB(R,N)),U,P)
 Q ""
VA ;
 NEW X,V,C S X=0,C="" F  S X=$O(BGPSUL(X)) Q:X'=+X  D
 .I T=1 S C=C+$P($G(^BGPGPDC(X,N)),U,P)
 .I T=2 S C=C+$P($G(^BGPGPDP(X,N)),U,P)
 .I T=3 S C=C+$P($G(^BGPGPDB(X,N)),U,P)
 .Q
 Q C
C(X,X2,X3) ;
 D COMMA^%DTC
 Q X
