BGP6BX ; IHS/CMI/LAB -CREATED BY ^ATXSTX ON AUG 21, 2005 ;
 ;;7.0;IHS CLINICAL REPORTING;;JAN 24, 2007
 ;;;BGP6;;AUG 21, 2005
 ;
 ; See referenced routines to see taxonomies being loaded.
 ;
START ;
 D ^BGP6BXA ;   BGP CMS BETA BLOCKER CLASS
 D ^BGP6BXB ;   BGP CMS BETA BLOCKER NDC
 D ^BGP6BXC ;   BGP CMS BRADYCARDIA DXS
 D ^BGP6BXD ;   BGP CMS CIRCULATORY SHOCK DXS
 D ^BGP6BXE ;   BGP CMS EJECTION FRACTION CPTS
 D ^BGP6BXF ;   BGP CMS EJECTION FRACTION PROC
 D ^BGP6BXG ;   BGP CMS HEART FAILURE DXS
 D ^BGP6BXH ;   BGP CMS LVSD DXS
 D ^BGP6BXJ ;   BGP CMS SEPTI/RESP FAIL DXS
 D ^BGP6BXL ;   BGP COLORECTAL CANCER DXS
 D ^BGP6BXM ;   BGP COPD DXS
 D ^BGP6BXN ;   BGP COPD DXS BB CONT
 D ^BGP6BXO ;   BGP CPT FLU
 D ^BGP6BXQ ;   BGP CPT MAMMOGRAM
 D ^BGP6BXR ;   BGP CPT MAMMOGRAM HEDIS
 D ^BGP6BXS ;   BGP CPT PAP
 D ^BGP6BXT ;   BGP CREATININE CPTS
 D ^BGP6BXU ;   BGP CREATININE LOINC CODES
 D ^BGP6BXV ;   BGP DEPRESSIVE DISORDERS
 D ^BGP6BXW ;   BGP DIPHTHERIA EVIDENCE
 D ^BGP6BXX ;   BGP DV DXS
 D ^BGP6BXY ;   BGP EMPHYSEMA DXS
 Q
