BGP6POS2 ; IHS/CMI/LAB - NO DESCRIPTION PROVIDED 28 Jan 2005 1:34 PM ;
 ;;16.1;IHS CLINICAL REPORTING;;MAR 22, 2016;Build 170
 ;
 ;
PRE ;EP
 ;CHANGE PACKAGE FILE NAME
 S BGPX=0 F  S BGPX=$O(^BGPCTRL(BGPX)) Q:BGPX'=+BGPX  S DA=BGPX,DIK="^BGPCTRL(" D ^DIK
 S BGPX=0 F  S BGPX=$O(^BGPPEIM(BGPX)) Q:BGPX'=+BGPX  S DA=BGPX,DIK="^BGPPEIM(" D ^DIK
 S BGPX=0 F  S BGPX=$O(^BGPELIM(BGPX)) Q:BGPX'=+BGPX  S DA=BGPX,DIK="^BGPELIM(" D ^DIK
 S BGPX=0 F  S BGPX=$O(^BGPELIIM(BGPX)) Q:BGPX'=+BGPX  S DA=BGPX,DIK="^BGPELIIM(" D ^DIK
 S BGPX=0 F  S BGPX=$O(^BGPNPLM(BGPX)) Q:BGPX'=+BGPX  S DA=BGPX,DIK="^BGPNPLM(" D ^DIK
 S BGPX=0 F  S BGPX=$O(^BGPINDMC(BGPX)) Q:BGPX'=+BGPX  S DA=BGPX,DIK="^BGPINDMC(" D ^DIK
 S BGPX=0 F  S BGPX=$O(^BGPINDM(BGPX)) Q:BGPX'=+BGPX  S DA=BGPX,DIK="^BGPINDM(" D ^DIK
 S BGPX=0 F  S BGPX=$O(^BGPTAXM(BGPX)) Q:BGPX'=+BGPX  S DA=BGPX,DIK="^BGPTAXM(" D ^DIK
 S BGPX=0 F  S BGPX=$O(^BGPSNOMM(BGPX)) Q:BGPX'=+BGPX  S DA=BGPX,DIK="^BGPSNOMM(" D ^DIK
 Q
