BGP6GX ; IHS/CMI/LAB -CREATED BY ^ATXSTX ON JAN 10, 2006 ;
 ;;7.0;IHS CLINICAL REPORTING;;JAN 24, 2007
 ;;;BGP6;;JAN 10, 2006
 ;
 ; See referenced routines to see taxonomies being loaded.
 ;
START ;
 D ^BGP6GXA ;   BGP TOTAL CHOLECTOMY PROCS
 D ^BGP6GXB ;   BGP BE CPTS
 D ^BGP6GXC ;   BGP COLO CPTS
 D ^BGP6GXD ;   BGP HYSTERECTOMY PROCEDURES
 D ^BGP6GXE ;   BGP HYPOTENSION DXS
 D ^BGP6GXG ;   BGP PHARYNGITIS DXS
 D ^BGP6GXH ;   BGP GROUP A STREP CPT
 D ^BGP6GXI ;   BGP GROUP A STREP LOINC
 D ^BGP6GXJ ;   BGP HEDIS ASTHMA LEUK NDC
 D ^BGP6GXK ;   BGP CHLAMYDIA CPTS
 D ^BGP6GXL ;   BGP CD4 CPTS
 D ^BGP6GXM ;   BGP URI DXS
 D ^BGP6GXN ;   BGP ESRD DXS
 D ^BGP6GXO ;   BGP ESRD DXS
 D ^BGP6GXP ;   BGP HEDIS ASTHMA INHALED NDC
 D ^BGP6GXQ ;   BGP HEDIS ASTHMA INHALED NDC
 D ^BGP6GXR ;   BGP NEPHROPATHY CPTS
 D ^BGP6GXS ;   BGP ALT LOINC
 D ^BGP6GXT ;   BGP AST LOINC
 D ^BGP6GXU ;   BGP LIVER FUNCTION LOINC
 D ^BGP6GXX ;   BGP RA LEFLUNOMIDE NDC
 D ^BGP6GXY ;   BGP RA METHOTREXATE NDC
 Q
