BGP7DP1C ; IHS/CMI/LAB - print ind 1 21 Mar 2007 12:55 PM ;
 ;;7.0;IHS CLINICAL REPORTING;;JAN 24, 2007
 ;
 ;
PI ;EP
 S BGPDENP=0
 S BGPPC2=0 F  S BGPPC2=$O(^BGPINDAC("ABC",BGPPC1,BGPPC2)) Q:BGPPC2=""  S BGPPC=$O(^BGPINDAC("ABC",BGPPC1,BGPPC2,0)) D PI1
 Q
PI1 ;EP
 K BGPEXCT,BGPSDP,BGPSDPN ;SDPX
 I BGPRTYPE=1,$P(^BGPINDAC(BGPPC,0),U,5)'=1 Q
 I BGPINDT="D",$P(^BGPINDAC(BGPPC,0),U,12)'=1 Q
 I BGPINDT="C",$P(^BGPINDAC(BGPPC,0),U,13)'=1 Q
 I BGPINDT="W",$P($G(^BGPINDAC(BGPPC,12)),U,2)'=1 Q
 I BGPINDT="E",$P($G(^BGPINDAC(BGPPC,12)),U,3)'=1 Q
 S BGPDF=$P(^BGPINDAC(BGPPC,0),U,8)
 ;get denominator value
 S BGPNP=$P(^DD(90530.03,BGPDF,0),U,4),N=$P(BGPNP,";"),P=$P(BGPNP,";",2)
 S BGPCYD=$$V(1,BGPRPT,N,P,1) I $G(BGPAREAA) D SETEXA(1,N,P) ;SPDX
 S BGPPRD=$$V(2,BGPRPT,N,P,1) I $G(BGPAREAA) D SETEXA(2,N,P) ;SPDX
 S BGPBLD=$$V(3,BGPRPT,N,P,1) I $G(BGPAREAA) D SETEXA(3,N,P) ;SPDX
 ;write out denominator
 I BGPRTYPE=1,$P(^BGPINDAC(BGPPC,0),U,4)="MS.A.9" S BGPDENP=0
 I BGPRTYPE=1,$P(^BGPINDAC(BGPPC,0),U,4)="DM.2.1" S BGPDENP=0
 I 'BGPDENP D
 .I $E($P(^BGPINDAC(BGPPC,0),U,4),1,3)="I.B"!($E($P(^BGPINDAC(BGPPC,0),U,4),1,3)="I.F") Q
 .I $P(^BGPINDAC(BGPPC,0),U,11),BGPRTYPE=1 D HEADER^BGP7DPH Q:BGPQUIT  W !!,^BGPINDA(BGPIC,53,1,0) D H1^BGP7DPH
 .I $P(^BGPINDAC(BGPPC,0),U,24),BGPRTYPE=4 D HEADER^BGP7DPH Q:BGPQUIT  W !!,^BGPINDA(BGPIC,53,1,0) D H1^BGP7DPH
 .I $Y>(BGPIOSL-15) D HEADER^BGP7DPH Q:BGPQUIT  W !!,^BGPINDA(BGPIC,53,1,0) D H1^BGP7DPH
 .W !!,$P(^BGPINDAC(BGPPC,0),U,17)
 .I $P(^BGPINDAC(BGPPC,0),U,18)]"" D C18
 .I $P(^BGPINDAC(BGPPC,0),U,21)]"" D C21
 .W ?20,$$C(BGPCYD,0,8),?35,$$C(BGPPRD,0,8),?58,$$C(BGPBLD,0,8),!
 .S BGPDENP=1
 I $P(^BGPINDAC(BGPPC,0),U,4)["I." D
 .S BGPDF=$P(^BGPINDAC(BGPPC,0),U,8)
 .;get denominator value of measure
 .S BGPNP=$P(^DD(90530.03,BGPDF,0),U,4),N=$P(BGPNP,";"),P=$P(BGPNP,";",2)
 .S BGPCYD=$$V(1,BGPRPT,N,P,1) I $G(BGPAREAA) D SETEXA(1,N,P) ;SPDX
 .S BGPPRD=$$V(2,BGPRPT,N,P,1) I $G(BGPAREAA) D SETEXA(2,N,P) ;SPDX
 .S BGPBLD=$$V(3,BGPRPT,N,P,1) I $G(BGPAREAA) D SETEXA(3,N,P) ;SPDX
 S BGPNF=$P(^BGPINDAC(BGPPC,0),U,9)
 S BGPNP=$P(^DD(90530.03,BGPNF,0),U,4),N=$P(BGPNP,";"),P=$P(BGPNP,";",2)
 D SETN
 ;write header
 I $P(^BGPINDAC(BGPPC,0),U,22) W !
 I $P($G(^BGPINDAC(BGPPC,12)),U,8),BGPRTYPE=4 D HEADER^BGP7DPH Q:BGPQUIT  W !!,^BGPINDA(BGPIC,53,1,0) D H1^BGP7DPH
 W !,$P(^BGPINDAC(BGPPC,0),U,15) I BGPRTYPE=4,$P($G(^BGPINDAC(BGPPC,12)),U,5) W " (GPRA)"
 I $P(^BGPINDAC(BGPPC,0),U,16)]"" W !?1,$P(^BGPINDAC(BGPPC,0),U,16)
 I BGPRTYPE=4,$P($G(^BGPINDAC(BGPPC,12)),U,6) W:$P(^BGPINDAC(BGPPC,0),U,16)="" ! W " (GPRA)"
 I $P(^BGPINDAC(BGPPC,0),U,19)]"" W !?1,$P(^BGPINDAC(BGPPC,0),U,19)
 I BGPRTYPE=4,$P($G(^BGPINDAC(BGPPC,12)),U,7) W:$P(^BGPINDAC(BGPPC,0),U,19)="" ! W " (GPRA)"
 D H2^BGP7DPH
 Q
C18 ;
 W !,$P(^BGPINDAC(BGPPC,0),U,18)
 Q
C21 ;
 W !,$P(^BGPINDAC(BGPPC,0),U,21)
 Q
I1AGE ;EP - age tallies
 D I1AGE^BGP7DP11
 Q
SETN ;EP - set numerator fields
 S BGPCYN=$$V^BGP7DP1C(1,BGPRPT,N,P,2) ;SPDX
 S BGPPRN=$$V^BGP7DP1C(2,BGPRPT,N,P,2) ;SPDX
 S BGPBLN=$$V^BGP7DP1C(3,BGPRPT,N,P,2) ;SPDX
 S BGPCYP=$S(BGPCYD:((BGPCYN/BGPCYD)*100),1:"")
 S BGPPRP=$S(BGPPRD:((BGPPRN/BGPPRD)*100),1:"")
 S BGPBLP=$S(BGPBLD:((BGPBLN/BGPBLD)*100),1:"")
 I $G(BGPAREAA) D SDP
 I $P($G(^BGPINDAC(BGPPC,14)),U),'$G(BGPNOSUM) D
 .S ^TMP($J,"SUMMARY",$P(^BGPSCAT($P(^BGPINDAC(BGPPC,14),U,5),0),U,2),$P(^BGPINDAC(BGPPC,14),U,6),BGPPC)=BGPCYP_U_BGPPRP_U_BGPBLP
 .I $G(BGPAREAA) D  ;SDPX
 ..S X=0 F  S X=$O(BGPSDP(X)) Q:X'=+X  D  ;SDPX
 ...S ^TMP($J,"SUMMARY DETAIL PAGE",$P(^BGPSCAT($P(^BGPINDAC(BGPPC,14),U,5),0),U,2),$P(^BGPINDAC(BGPPC,14),U,6),BGPPC,X)=$P($G(BGPSDP(X,1)),U,3)_U_$P($G(BGPSDP(X,2)),U,3)_U_$P($G(BGPSDP(X,3)),U,3)_U_$J(BGPCYP,5,1)
 .S ^TMP($J,"SUMMARYDEL",$P(^BGPSCAT($P(^BGPINDAC(BGPPC,14),U,5),0),U,2),$P(^BGPINDAC(BGPPC,14),U,6),BGPPC)=$$SB($J(BGPCYP,5,1))_U_$$SB($J(BGPPRP,5,1))_U_$$SB($J(BGPBLP,5,1))
 .I $G(BGPAREAA) D  ;SDPX
 ..S X=0 F  S X=$O(BGPSDP(X)) Q:X'=+X  D  ;SDPX
 ...S A=$P(^BGPSCAT($P(^BGPINDAC(BGPPC,14),U,5),0),U,2)
 ...S B=$P(^BGPINDAC(BGPPC,14),U,6)
 ...S ^TMP($J,"SUMMARYDEL DETAIL PAGE",A,B,BGPPC,X)=$$SB($J($P($G(BGPSDP(X,1)),U,3),5,1))_U_$$SB($J($P($G(BGPSDP(X,2)),U,3),5,1))_U_$$SB($J($P($G(BGPSDP(X,3)),U,3),5,1))_U_$$SB($J(BGPCYP,5,1))
 ;NON
 I $P($G(^BGPINDAC(BGPPC,15)),U),'$G(BGPNOSUM) D
 .S ^TMP($J,"SUMMARY NON",$P(^BGPSCAT($P(^BGPINDAC(BGPPC,15),U,5),0),U,3),$P(^BGPINDAC(BGPPC,15),U,6),BGPPC)=BGPCYP_U_BGPPRP_U_BGPBLP
 .I $G(BGPAREAA) D  ;SDPX
 ..S X=0 F  S X=$O(BGPSDPN(X)) Q:X'=+X  D  ;SDPX
 ...S ^TMP($J,"SUMMARY DETAIL PAGE NON",$P(^BGPSCAT($P(^BGPINDAC(BGPPC,15),U,5),0),U,3),$P(^BGPINDAC(BGPPC,15),U,6),BGPPC,X)=$P($G(BGPSDPN(X,1)),U,3)_U_$P($G(BGPSDPN(X,2)),U,3)_U_$P($G(BGPSDPN(X,3)),U,3)_U_$J(BGPCYP,5,1)
 I $P($G(^BGPINDAC(BGPPC,15)),U),'$G(BGPNOSUM) D
 .S ^TMP($J,"SUMMARYDEL NON",$P(^BGPSCAT($P(^BGPINDAC(BGPPC,15),U,5),0),U,3),$P(^BGPINDAC(BGPPC,15),U,6),BGPPC)=$$SB($J(BGPCYP,5,1))_U_$$SB($J(BGPPRP,5,1))_U_$$SB($J(BGPBLP,5,1))
 .I $G(BGPAREAA) D  ;SDPX
 ..S X=0 F  S X=$O(BGPSDPN(X)) Q:X'=+X  D  ;SDPX
 ...S A=$P(^BGPSCAT($P(^BGPINDAC(BGPPC,15),U,5),0),U,3)
 ...S B=$P(^BGPINDAC(BGPPC,15),U,6)
 ...S ^TMP($J,"SUMMARYDEL DETAIL PAGE NON",A,B,BGPPC,X)=$$SB($J($P($G(BGPSDPN(X,1)),U,3),5,1))_U_$$SB($J($P($G(BGPSDPN(X,2)),U,3),5,1))_U_$$SB($J($P($G(BGPSDPN(X,3)),U,3),5,1))_U_$$SB($J(BGPCYP,5,1))
 I $G(BGPIIDEL),BGPROT="B" Q
GPRANT1 ;
 I $G(BGPAREAA),$G(BGPEXCEL) D
 .Q:$P(^BGPINDAC(BGPPC,0),U,14)=""
 .;set each numerator and percent,then set BGPEI
 .NEW X S X=0 F  S X=$O(BGPSUL(X)) Q:X'=+X  D
 ..S $P(BGPEXCT(X,1),U,1)=$P($G(^BGPGPDCA(X,N)),U,P),$P(BGPEXCT(X,1),U,3)=$S($P(BGPEXCT(X,1),U,2):(($P(BGPEXCT(X,1),U,1)/$P(BGPEXCT(X,1),U,2))*100),1:"")
 ..S $P(BGPEXCT(X,2),U,1)=$P($G(^BGPGPDPA(X,N)),U,P),$P(BGPEXCT(X,2),U,3)=$S($P(BGPEXCT(X,2),U,2):(($P(BGPEXCT(X,2),U,1)/$P(BGPEXCT(X,2),U,2))*100),1:"")
 ..S $P(BGPEXCT(X,3),U,1)=$P($G(^BGPGPDBA(X,N)),U,P),$P(BGPEXCT(X,3),U,3)=$S($P(BGPEXCT(X,3),U,2):(($P(BGPEXCT(X,3),U,1)/$P(BGPEXCT(X,3),U,2))*100),1:"")
 .S X=0 F  S X=$O(BGPEXCT(X)) Q:X'=+X  D
 ..S A=$P(BGPEXCT(X,1),U,1),B=$P(BGPEXCT(X,1),U,2),C=$P(BGPEXCT(X,1),U,3)
 ..S D=$P(BGPEXCT(X,2),U,1),E=$P(BGPEXCT(X,2),U,2),F=$P(BGPEXCT(X,2),U,3)
 ..S G=$P(BGPEXCT(X,3),U,1),H=$P(BGPEXCT(X,3),U,2),I=$P(BGPEXCT(X,3),U,3)
 ..I $P($P(^BGPINDAC(BGPPC,0),U,4),".")="023" S Y=$P(^BGPINDAC(BGPPC,0),U,14),$P(BGPEI(X),U,Y)=$S(B:B,1:0),$P(BGPEI(X),U,(Y+3))=$S(E:E,1:0),$P(BGPEI(X),U,(Y+6))=$S(H:H,1:0) Q
 ..I $P($P(^BGPINDAC(BGPPC,0),U,4),".")="014" S Y=$P(^BGPINDAC(BGPPC,0),U,14),$P(BGPEI(X),U,Y)=$S(B:B,1:0),$P(BGPEI(X),U,(Y+3))=$S(E:E,1:0),$P(BGPEI(X),U,(Y+6))=$S(H:H,1:0) Q
 ..I $P($P(^BGPINDAC(BGPPC,0),U,4),".")="016" S Y=$P(^BGPINDAC(BGPPC,0),U,14),$P(BGPEI(X),U,Y)=$S(B:B,1:0),$P(BGPEI(X),U,(Y+3))=$S(E:E,1:0),$P(BGPEI(X),U,(Y+6))=$S(H:H,1:0) Q
 ..S Y=$P(^BGPINDAC(BGPPC,0),U,14)
 ..S $P(BGPEI(X),U,$P(^BGPINDAC(BGPPC,0),U,14))=$S(A:A,1:0),$P(BGPEI(X),U,(Y+1))=$S(B:B,1:0),$P(BGPEI(X),U,(Y+2))=$$SL(C)
 ..S $P(BGPEI(X),U,(Y+3))=$S(D:D,1:0),$P(BGPEI(X),U,(Y+4))=$S(E:E,1:0),$P(BGPEI(X),U,(Y+5))=$$SL(F),$P(BGPEI(X),U,(Y+6))=$S(G:G,1:0),$P(BGPEI(X),U,(Y+7))=$S(H:H,1:0),$P(BGPEI(X),U,(Y+8))=$$SL(I)
CRSNT1 ;
 I $G(BGPAREAA),$G(BGPEXCEL) D
 .Q:$P(^BGPINDAC(BGPPC,0),U,6)=""
 .;set each numerator and percent,then set BGPGRAN1
 .NEW X S X=0 F  S X=$O(BGPSUL(X)) Q:X'=+X  D
 ..S $P(BGPEXCT(X,1),U,1)=$P($G(^BGPGPDCA(X,N)),U,P),$P(BGPEXCT(X,1),U,3)=$S($P(BGPEXCT(X,1),U,2):(($P(BGPEXCT(X,1),U,1)/$P(BGPEXCT(X,1),U,2))*100),1:"")
 ..S $P(BGPEXCT(X,2),U,1)=$P($G(^BGPGPDPA(X,N)),U,P),$P(BGPEXCT(X,2),U,3)=$S($P(BGPEXCT(X,2),U,2):(($P(BGPEXCT(X,2),U,1)/$P(BGPEXCT(X,2),U,2))*100),1:"")
 ..S $P(BGPEXCT(X,3),U,1)=$P($G(^BGPGPDBA(X,N)),U,P),$P(BGPEXCT(X,3),U,3)=$S($P(BGPEXCT(X,3),U,2):(($P(BGPEXCT(X,3),U,1)/$P(BGPEXCT(X,3),U,2))*100),1:"")
 .S X=0 F  S X=$O(BGPEXCT(X)) Q:X'=+X  D
 ..S A=$P(BGPEXCT(X,1),U,1),B=$P(BGPEXCT(X,1),U,2),C=$P(BGPEXCT(X,1),U,3)
 ..S D=$P(BGPEXCT(X,2),U,1),E=$P(BGPEXCT(X,2),U,2),F=$P(BGPEXCT(X,2),U,3)
 ..S G=$P(BGPEXCT(X,3),U,1),H=$P(BGPEXCT(X,3),U,2),I=$P(BGPEXCT(X,3),U,3)
 ..I $P($P(^BGPINDAC(BGPPC,0),U,4),".")="023" S Y=$P(^BGPINDAC(BGPPC,0),U,6),$P(BGPGRAN1(X),U,Y)=$S(B:B,1:0),$P(BGPGRAN1(X),U,(Y+3))=$S(E:E,1:0),$P(BGPGRAN1(X),U,(Y+6))=$S(H:H,1:0) Q
 ..I $P($P(^BGPINDAC(BGPPC,0),U,4),".")="014" S Y=$P(^BGPINDAC(BGPPC,0),U,6),$P(BGPGRAN1(X),U,Y)=$S(B:B,1:0),$P(BGPGRAN1(X),U,(Y+3))=$S(E:E,1:0),$P(BGPGRAN1(X),U,(Y+6))=$S(H:H,1:0) Q
 ..I $P($P(^BGPINDAC(BGPPC,0),U,4),".")="016" S Y=$P(^BGPINDAC(BGPPC,0),U,6),$P(BGPGRAN1(X),U,Y)=$S(B:B,1:0),$P(BGPGRAN1(X),U,(Y+3))=$S(E:E,1:0),$P(BGPGRAN1(X),U,(Y+6))=$S(H:H,1:0) Q
 ..S Y=$P(^BGPINDAC(BGPPC,0),U,6)
 ..S $P(BGPGRAN1(X),U,$P(^BGPINDAC(BGPPC,0),U,6))=$S(A:A,1:0),$P(BGPGRAN1(X),U,(Y+1))=$S(B:B,1:0),$P(BGPGRAN1(X),U,(Y+2))=$$SL(C)
 ..S $P(BGPGRAN1(X),U,(Y+3))=$S(D:D,1:0),$P(BGPGRAN1(X),U,(Y+4))=$S(E:E,1:0),$P(BGPGRAN1(X),U,(Y+5))=$$SL(F),$P(BGPGRAN1(X),U,(Y+6))=$S(G:G,1:0),$P(BGPGRAN1(X),U,(Y+7))=$S(H:H,1:0),$P(BGPGRAN1(X),U,(Y+8))=$$SL(I)
CRSNT2 ;
 I $G(BGPAREAA),$G(BGPEXCEL) D
 .Q:$P(^BGPINDAC(BGPPC,0),U,7)=""
 .;set each numerator and percent,then set BGPGRAN2
 .NEW X S X=0 F  S X=$O(BGPSUL(X)) Q:X'=+X  D
 ..S $P(BGPEXCT(X,1),U,1)=$P($G(^BGPGPDCA(X,N)),U,P),$P(BGPEXCT(X,1),U,3)=$S($P(BGPEXCT(X,1),U,2):(($P(BGPEXCT(X,1),U,1)/$P(BGPEXCT(X,1),U,2))*100),1:"")
 ..S $P(BGPEXCT(X,2),U,1)=$P($G(^BGPGPDPA(X,N)),U,P),$P(BGPEXCT(X,2),U,3)=$S($P(BGPEXCT(X,2),U,2):(($P(BGPEXCT(X,2),U,1)/$P(BGPEXCT(X,2),U,2))*100),1:"")
 ..S $P(BGPEXCT(X,3),U,1)=$P($G(^BGPGPDBA(X,N)),U,P),$P(BGPEXCT(X,3),U,3)=$S($P(BGPEXCT(X,3),U,2):(($P(BGPEXCT(X,3),U,1)/$P(BGPEXCT(X,3),U,2))*100),1:"")
 .S X=0 F  S X=$O(BGPEXCT(X)) Q:X'=+X  D
 ..S A=$P(BGPEXCT(X,1),U,1),B=$P(BGPEXCT(X,1),U,2),C=$P(BGPEXCT(X,1),U,3)
 ..S D=$P(BGPEXCT(X,2),U,1),E=$P(BGPEXCT(X,2),U,2),F=$P(BGPEXCT(X,2),U,3)
 ..S G=$P(BGPEXCT(X,3),U,1),H=$P(BGPEXCT(X,3),U,2),I=$P(BGPEXCT(X,3),U,3)
 ..I $P($P(^BGPINDAC(BGPPC,0),U,4),".")="023" S Y=$P(^BGPINDAC(BGPPC,0),U,7),$P(BGPGRAN2(X),U,Y)=$S(B:B,1:0),$P(BGPGRAN2(X),U,(Y+3))=$S(E:E,1:0),$P(BGPGRAN2(X),U,(Y+6))=$S(H:H,1:0) Q
 ..I $P($P(^BGPINDAC(BGPPC,0),U,4),".")="014" S Y=$P(^BGPINDAC(BGPPC,0),U,7),$P(BGPGRAN2(X),U,Y)=$S(B:B,1:0),$P(BGPGRAN2(X),U,(Y+3))=$S(E:E,1:0),$P(BGPGRAN2(X),U,(Y+6))=$S(H:H,1:0) Q
 ..I $P($P(^BGPINDAC(BGPPC,0),U,4),".")="016" S Y=$P(^BGPINDAC(BGPPC,0),U,7),$P(BGPGRAN2(X),U,Y)=$S(B:B,1:0),$P(BGPGRAN2(X),U,(Y+3))=$S(E:E,1:0),$P(BGPGRAN2(X),U,(Y+6))=$S(H:H,1:0) Q
 ..S Y=$P(^BGPINDAC(BGPPC,0),U,7)
 ..S $P(BGPGRAN2(X),U,$P(^BGPINDAC(BGPPC,0),U,7))=$S(A:A,1:0),$P(BGPGRAN2(X),U,(Y+1))=$S(B:B,1:0),$P(BGPGRAN2(X),U,(Y+2))=$$SL(C)
 ..S $P(BGPGRAN2(X),U,(Y+3))=$S(D:D,1:0),$P(BGPGRAN2(X),U,(Y+4))=$S(E:E,1:0),$P(BGPGRAN2(X),U,(Y+5))=$$SL(F),$P(BGPGRAN2(X),U,(Y+6))=$S(G:G,1:0),$P(BGPGRAN2(X),U,(Y+7))=$S(H:H,1:0),$P(BGPGRAN2(X),U,(Y+8))=$$SL(I)
 Q
SL(V) ;
 I V="" S V=0
 Q $$STRIP^XLFSTR($J(V,5,1)," ")
SETEXA(T,N,P) ;EP - set denominator
 Q:'$G(BGPEXCEL)
 NEW X,Y,Z
 S X=0 F  S X=$O(BGPSUL(X)) Q:X'=+X  D
 .I T=1 S $P(BGPEXCT(X,T),U,2)=$P($G(^BGPGPDCA(X,N)),U,P)
 .I T=2 S $P(BGPEXCT(X,T),U,2)=$P($G(^BGPGPDPA(X,N)),U,P)
 .I T=3 S $P(BGPEXCT(X,T),U,2)=$P($G(^BGPGPDBA(X,N)),U,P)
 Q
V(T,R,N,P,ND) ;EP ;SPDX
 I $G(BGPAREAA) G VA
 NEW X
 I T=1 S X=$P($G(^BGPGPDCA(R,N)),U,P) Q $S(X]"":X,1:0)
 I T=2 S X=$P($G(^BGPGPDPA(R,N)),U,P) Q $S(X]"":X,1:0)
 I T=3 S X=$P($G(^BGPGPDBA(R,N)),U,P) Q $S(X]"":X,1:0)
 Q ""
VA ;
 NEW X,V,C S X=0,C="" F  S X=$O(BGPSUL(X)) Q:X'=+X  D
 .I T=1 S C=C+$P($G(^BGPGPDCA(X,N)),U,P)
 .I T=2 S C=C+$P($G(^BGPGPDPA(X,N)),U,P)
 .I T=3 S C=C+$P($G(^BGPGPDBA(X,N)),U,P)
 .I $G(BGPAREAA),$P($G(^BGPINDAC(BGPPC,14)),U) D  ;SPDX
 ..I T=1 S $P(BGPSDP(X,T),U,ND)=$P($G(^BGPGPDCA(X,N)),U,P) ;SPDX
 ..I T=2 S $P(BGPSDP(X,T),U,ND)=$P($G(^BGPGPDPA(X,N)),U,P) ;SPDX
 ..I T=3 S $P(BGPSDP(X,T),U,ND)=$P($G(^BGPGPDBA(X,N)),U,P) ;SPDX
 .I $G(BGPAREAA),$P($G(^BGPINDAC(BGPPC,15)),U) D  ;SPDX
 ..I T=1 S $P(BGPSDPN(X,T),U,ND)=$P($G(^BGPGPDCA(X,N)),U,P) ;SPDX
 ..I T=2 S $P(BGPSDPN(X,T),U,ND)=$P($G(^BGPGPDPA(X,N)),U,P) ;SPDX
 ..I T=3 S $P(BGPSDPN(X,T),U,ND)=$P($G(^BGPGPDBA(X,N)),U,P) ;SPDX
 .Q
 Q $S(C]"":C,1:0)
C(X,X2,X3) ;
 D COMMA^%DTC
 Q X
SDP ;SDPX
 ;loop thru each BGPSDP and set 3rd piece
 NEW X,Y,T,D,N
 S X=0 F  S X=$O(BGPSDP(X)) Q:X'=+X  D
 .S T=0 F  S T=$O(BGPSDP(X,T)) Q:T'=+T  D
 ..S D=$P(BGPSDP(X,T),U,1),N=$P(BGPSDP(X,T),U,2)
 ..S $P(BGPSDP(X,T),U,3)=$S(D:((N/D)*100),1:"")
 S X=0 F  S X=$O(BGPSDPN(X)) Q:X'=+X  D
 .S T=0 F  S T=$O(BGPSDPN(X,T)) Q:T'=+T  D
 ..S D=$P(BGPSDPN(X,T),U,1),N=$P(BGPSDPN(X,T),U,2)
 ..S $P(BGPSDPN(X,T),U,3)=$S(D:((N/D)*100),1:"")
 Q
SB(X) ;EP - Strip leading and trailing blanks from X.
 NEW %
 X ^DD("FUNC",$O(^DD("FUNC","B","STRIPBLANKS",0)),1)
 Q X
