BGP82T ;IHS/CMI/LAB-CREATED BY ^ATXSTX ON JUL 05, 2008;
 ;;8.0;IHS CLINICAL REPORTING;**2**;MAR 12, 2008
 ;
 ; See referenced routines to see taxonomies being loaded.
 ;
START ;
 D ^BGP82TA ;   BGP SYSTOLIC BP CPTS
 D ^BGP82TB ;   BGP DIASTOLIC BP CPTS
 D ^BGP82TC ;   BGP TIA DXS
 D ^BGP82TD ;   BGP CPT FLU
 D ^BGP82TE ;   BGP SMOKING CPTS
 D ^BGP82TF ;   BGP HIV/AIDS DXS
 D ^BGP82TG ;   BGP ALCOHOL SCREENING CPTS
 D ^BGP82TH ;   BGP BNI CPTS
 D ^BGP82TI ;   BGP TOBACCO USER CPTS
 D ^BGP82TJ ;   BGP TOBACCO USER DXS
 D ^BGP82TK ;   BGP BE CPTS
 D ^BGP82TL ;   BGP ASTHMA INHALED STEROID NDC
 D ^BGP82TM ;   BGP HEDIS ASTHMA LEUK NDC
 D ^BGP82TN ;   BGP HEDIS ASTHMA NDC
 D ^BGP82TO ;   BGP SMOKER CPTS
 D ^BGP82TP ;   BGP SMOKELESS TOBACCO CPTS
 D ^BGP82TQ ;   BGP NON-TOBACCO CPTS
 D ^BGP82TR ;   BGP SIG PROCS
 D ^BGP82TS ;   BGP FOBT DXS
 D ^BGP82TT ;   BGP COLO PROCS
 D ^BGP82TU ;   BGP HGBA1C CPTS
 Q
