BGP8GX ; IHS/CMI/LAB -CREATED BY ^ATXSTX ON SEP 28, 2007 ;
 ;;8.0;IHS CLINICAL REPORTING;;MAR 12, 2008
 ;;;BGP6;;SEP 28, 2007
 ;
 ; See referenced routines to see taxonomies being loaded.
 ;
START ;
 D ^BGP8GXA ;   BGP HYPERTENSION DXS
 D ^BGP8GXB ;   BGP HYPOTENSION DXS
 D ^BGP8GXC ;   BGP HYSTERECTOMY CPTS
 D ^BGP8GXD ;   BGP HYSTERECTOMY DXS
 D ^BGP8GXE ;   BGP HYSTERECTOMY PROCEDURES
 D ^BGP8GXF ;   BGP IHD DXS
 D ^BGP8GXG ;   BGP INJURY DIAGNOSES
 D ^BGP8GXH ;   BGP IVD DXS
 D ^BGP8GXI ;   BGP LBBB ON ECG CPT
 D ^BGP8GXJ ;   BGP LBBB ON ECG PROC
 D ^BGP8GXK ;   BGP LDL CPTS
 D ^BGP8GXL ;   BGP LDL LOINC CODES
 D ^BGP8GXM ;   BGP LIPID PROFILE LOINC CODES
 D ^BGP8GXN ;   BGP LIVER FUNCTION LOINC
 D ^BGP8GXO ;   BGP LVAD/HEART TRANSPLANT PROC
 D ^BGP8GXP ;   BGP MAJOR DEPRESSION (ADM)
 D ^BGP8GXQ ;   BGP MAJOR DEPRESSION PRIOR
 D ^BGP8GXR ;   BGP MAJOR DEPRESSIVE DISORDERS
 D ^BGP8GXS ;   BGP MASTECTOMY PROCEDURES
 D ^BGP8GXT ;   BGP MEASLES EVIDENCE
 D ^BGP8GXU ;   BGP MH OPT VISIT CPT NMH 1
 D ^BGP8GXV ;   BGP MH OPT VISIT CPT NMH 3
 D ^BGP8GXW ;   BGP MICROALBUM LOINC CODES
 D ^BGP8GXX ;   BGP MISCARRIAGE/ABORTION DXS
 D ^BGP8GXY ;   BGP MMR CONTRAINDICATIONS
 D ^BGP8GXZ ;   BGP MOOD DISORDERS
 Q
