BGP8DP1D ; IHS/CMI/LAB - print ind 1 21 Mar 2008 12:55 PM ; 01 Jul 2008  11:40 AM
 ;;8.0;IHS CLINICAL REPORTING;**2**;MAR 12, 2008
ONM1 ;EP
 I $G(BGPAREAA),$G(BGPEXCEL) D
 .Q:$P(^BGPINDEC(BGPPC,0),U,6)=""
 .;set each numerator and percent,then set BGPONN1
 .NEW X S X=0 F  S X=$O(BGPSUL(X)) Q:X'=+X  D
 ..S $P(BGPEXCT(X,1),U,1)=$P($G(^BGPGPDCE(X,N)),U,P),$P(BGPEXCT(X,1),U,3)=$S($P(BGPEXCT(X,1),U,2):(($P(BGPEXCT(X,1),U,1)/$P(BGPEXCT(X,1),U,2))*100),1:"")
 ..S $P(BGPEXCT(X,2),U,1)=$P($G(^BGPGPDPE(X,N)),U,P),$P(BGPEXCT(X,2),U,3)=$S($P(BGPEXCT(X,2),U,2):(($P(BGPEXCT(X,2),U,1)/$P(BGPEXCT(X,2),U,2))*100),1:"")
 ..S $P(BGPEXCT(X,3),U,1)=$P($G(^BGPGPDBE(X,N)),U,P),$P(BGPEXCT(X,3),U,3)=$S($P(BGPEXCT(X,3),U,2):(($P(BGPEXCT(X,3),U,1)/$P(BGPEXCT(X,3),U,2))*100),1:"")
 .S X=0 F  S X=$O(BGPEXCT(X)) Q:X'=+X  D
 ..S A=$P(BGPEXCT(X,1),U,1),B=$P(BGPEXCT(X,1),U,2),C=$P(BGPEXCT(X,1),U,3)
 ..S D=$P(BGPEXCT(X,2),U,1),E=$P(BGPEXCT(X,2),U,2),F=$P(BGPEXCT(X,2),U,3)
 ..S G=$P(BGPEXCT(X,3),U,1),H=$P(BGPEXCT(X,3),U,2),I=$P(BGPEXCT(X,3),U,3)
 ..I $P($P(^BGPINDEC(BGPPC,0),U,4),".")="023" S Y=$P(^BGPINDEC(BGPPC,0),U,6),$P(BGPONN1(X),U,Y)=$S(B:B,1:0),$P(BGPONN1(X),U,(Y+3))=$S(E:E,1:0),$P(BGPONN1(X),U,(Y+6))=$S(H:H,1:0) Q
 ..I $P($P(^BGPINDEC(BGPPC,0),U,4),".")="014" S Y=$P(^BGPINDEC(BGPPC,0),U,6),$P(BGPONN1(X),U,Y)=$S(B:B,1:0),$P(BGPONN1(X),U,(Y+3))=$S(E:E,1:0),$P(BGPONN1(X),U,(Y+6))=$S(H:H,1:0) Q
 ..I $P($P(^BGPINDEC(BGPPC,0),U,4),".")="016" S Y=$P(^BGPINDEC(BGPPC,0),U,6),$P(BGPONN1(X),U,Y)=$S(B:B,1:0),$P(BGPONN1(X),U,(Y+3))=$S(E:E,1:0),$P(BGPONN1(X),U,(Y+6))=$S(H:H,1:0) Q
 ..I $P($G(^BGPINDEC(BGPPC,19)),U,13) S Y=$P(^BGPINDEC(BGPPC,21),U,1),$P(BGPONN1(X),U,Y)=$S(B:B,1:0),$P(BGPONN1(X),U,(Y+3))=$S(E:E,1:0),$P(BGPONN1(X),U,(Y+6))=$S(H:H,1:0) Q
 ..S Y=$P(^BGPINDEC(BGPPC,0),U,6)
 ..S $P(BGPONN1(X),U,$P(^BGPINDEC(BGPPC,0),U,6))=$S(A:A,1:0),$P(BGPONN1(X),U,(Y+1))=$S(B:B,1:0),$P(BGPONN1(X),U,(Y+2))=$$SL(C)
 ..S $P(BGPONN1(X),U,(Y+3))=$S(D:D,1:0),$P(BGPONN1(X),U,(Y+4))=$S(E:E,1:0),$P(BGPONN1(X),U,(Y+5))=$$SL(F),$P(BGPONN1(X),U,(Y+6))=$S(G:G,1:0),$P(BGPONN1(X),U,(Y+7))=$S(H:H,1:0),$P(BGPONN1(X),U,(Y+8))=$$SL(I)
ONN2 ;
 I $G(BGPAREAA),$G(BGPEXCEL) D
 .Q:$P(^BGPINDEC(BGPPC,0),U,7)=""
 .;set each numerator and percent,then set BGPONN2
 .NEW X S X=0 F  S X=$O(BGPSUL(X)) Q:X'=+X  D
 ..S $P(BGPEXCT(X,1),U,1)=$P($G(^BGPGPDCE(X,N)),U,P),$P(BGPEXCT(X,1),U,3)=$S($P(BGPEXCT(X,1),U,2):(($P(BGPEXCT(X,1),U,1)/$P(BGPEXCT(X,1),U,2))*100),1:"")
 ..S $P(BGPEXCT(X,2),U,1)=$P($G(^BGPGPDPE(X,N)),U,P),$P(BGPEXCT(X,2),U,3)=$S($P(BGPEXCT(X,2),U,2):(($P(BGPEXCT(X,2),U,1)/$P(BGPEXCT(X,2),U,2))*100),1:"")
 ..S $P(BGPEXCT(X,3),U,1)=$P($G(^BGPGPDBE(X,N)),U,P),$P(BGPEXCT(X,3),U,3)=$S($P(BGPEXCT(X,3),U,2):(($P(BGPEXCT(X,3),U,1)/$P(BGPEXCT(X,3),U,2))*100),1:"")
 .S X=0 F  S X=$O(BGPEXCT(X)) Q:X'=+X  D
 ..S A=$P(BGPEXCT(X,1),U,1),B=$P(BGPEXCT(X,1),U,2),C=$P(BGPEXCT(X,1),U,3)
 ..S D=$P(BGPEXCT(X,2),U,1),E=$P(BGPEXCT(X,2),U,2),F=$P(BGPEXCT(X,2),U,3)
 ..S G=$P(BGPEXCT(X,3),U,1),H=$P(BGPEXCT(X,3),U,2),I=$P(BGPEXCT(X,3),U,3)
 ..I $P($P(^BGPINDEC(BGPPC,0),U,4),".")="023" S Y=$P(^BGPINDEC(BGPPC,0),U,7),$P(BGPONN2(X),U,Y)=$S(B:B,1:0),$P(BGPONN2(X),U,(Y+3))=$S(E:E,1:0),$P(BGPONN2(X),U,(Y+6))=$S(H:H,1:0) Q
 ..I $P($P(^BGPINDEC(BGPPC,0),U,4),".")="014" S Y=$P(^BGPINDEC(BGPPC,0),U,7),$P(BGPONN2(X),U,Y)=$S(B:B,1:0),$P(BGPONN2(X),U,(Y+3))=$S(E:E,1:0),$P(BGPONN2(X),U,(Y+6))=$S(H:H,1:0) Q
 ..I $P($P(^BGPINDEC(BGPPC,0),U,4),".")="016" S Y=$P(^BGPINDEC(BGPPC,0),U,7),$P(BGPONN2(X),U,Y)=$S(B:B,1:0),$P(BGPONN2(X),U,(Y+3))=$S(E:E,1:0),$P(BGPONN2(X),U,(Y+6))=$S(H:H,1:0) Q
 ..I $P(^BGPINDEC(BGPPC,0),U,4)="STI.AA.1A" S Y=$P(^BGPINDEC(BGPPC,0),U,7),$P(BGPONN2(X),U,Y)=$S(B:B,1:0),$P(BGPONN2(X),U,(Y+3))=$S(E:E,1:0),$P(BGPONN2(X),U,(Y+6))=$S(H:H,1:0) Q
 ..I $P(^BGPINDEC(BGPPC,0),U,4)="STI.AB.4A" S Y=$P(^BGPINDEC(BGPPC,0),U,7),$P(BGPONN2(X),U,Y)=$S(B:B,1:0),$P(BGPONN2(X),U,(Y+3))=$S(E:E,1:0),$P(BGPONN2(X),U,(Y+6))=$S(H:H,1:0) Q
 ..I $P($G(^BGPINDEC(BGPPC,19)),U,13) S Y=$P(^BGPINDEC(BGPPC,21),U,1),$P(BGPONN2(X),U,Y)=$S(B:B,1:0),$P(BGPONN2(X),U,(Y+3))=$S(E:E,1:0),$P(BGPONN2(X),U,(Y+6))=$S(H:H,1:0) Q
 ..S Y=$P(^BGPINDEC(BGPPC,0),U,7)
 ..S $P(BGPONN2(X),U,$P(^BGPINDEC(BGPPC,0),U,7))=$S(A:A,1:0),$P(BGPONN2(X),U,(Y+1))=$S(B:B,1:0),$P(BGPONN2(X),U,(Y+2))=$$SL(C)
 ..S $P(BGPONN2(X),U,(Y+3))=$S(D:D,1:0),$P(BGPONN2(X),U,(Y+4))=$S(E:E,1:0),$P(BGPONN2(X),U,(Y+5))=$$SL(F),$P(BGPONN2(X),U,(Y+6))=$S(G:G,1:0),$P(BGPONN2(X),U,(Y+7))=$S(H:H,1:0),$P(BGPONN2(X),U,(Y+8))=$$SL(I)
ONN3 ;
 I $G(BGPAREAA),$G(BGPEXCEL) D
 .Q:$P($G(^BGPINDEC(BGPPC,21)),U,1)=""
 .;set each numerator and percent,then set BGPONN3
 .NEW X S X=0 F  S X=$O(BGPSUL(X)) Q:X'=+X  D
 ..S $P(BGPEXCT(X,1),U,1)=$P($G(^BGPGPDCE(X,N)),U,P),$P(BGPEXCT(X,1),U,3)=$S($P(BGPEXCT(X,1),U,2):(($P(BGPEXCT(X,1),U,1)/$P(BGPEXCT(X,1),U,2))*100),1:"")
 ..S $P(BGPEXCT(X,2),U,1)=$P($G(^BGPGPDPE(X,N)),U,P),$P(BGPEXCT(X,2),U,3)=$S($P(BGPEXCT(X,2),U,2):(($P(BGPEXCT(X,2),U,1)/$P(BGPEXCT(X,2),U,2))*100),1:"")
 ..S $P(BGPEXCT(X,3),U,1)=$P($G(^BGPGPDBE(X,N)),U,P),$P(BGPEXCT(X,3),U,3)=$S($P(BGPEXCT(X,3),U,2):(($P(BGPEXCT(X,3),U,1)/$P(BGPEXCT(X,3),U,2))*100),1:"")
 .S X=0 F  S X=$O(BGPEXCT(X)) Q:X'=+X  D
 ..S A=$P(BGPEXCT(X,1),U,1),B=$P(BGPEXCT(X,1),U,2),C=$P(BGPEXCT(X,1),U,3)
 ..S D=$P(BGPEXCT(X,2),U,1),E=$P(BGPEXCT(X,2),U,2),F=$P(BGPEXCT(X,2),U,3)
 ..S G=$P(BGPEXCT(X,3),U,1),H=$P(BGPEXCT(X,3),U,2),I=$P(BGPEXCT(X,3),U,3)
 ..I $P($P(^BGPINDEC(BGPPC,0),U,4),".")="023" S Y=$P(^BGPINDEC(BGPPC,21),U,1),$P(BGPONN3(X),U,Y)=$S(B:B,1:0),$P(BGPONN3(X),U,(Y+3))=$S(E:E,1:0),$P(BGPONN3(X),U,(Y+6))=$S(H:H,1:0) Q
 ..I $P($P(^BGPINDEC(BGPPC,0),U,4),".")="014" S Y=$P(^BGPINDEC(BGPPC,21),U,1),$P(BGPONN3(X),U,Y)=$S(B:B,1:0),$P(BGPONN3(X),U,(Y+3))=$S(E:E,1:0),$P(BGPONN3(X),U,(Y+6))=$S(H:H,1:0) Q
 ..I $P($P(^BGPINDEC(BGPPC,0),U,4),".")="016" S Y=$P(^BGPINDEC(BGPPC,21),U,1),$P(BGPONN3(X),U,Y)=$S(B:B,1:0),$P(BGPONN3(X),U,(Y+3))=$S(E:E,1:0),$P(BGPONN3(X),U,(Y+6))=$S(H:H,1:0) Q
 ..I $P(^BGPINDEC(BGPPC,0),U,4)="STI.AA.1A" S Y=$P(^BGPINDEC(BGPPC,21),U,1),$P(BGPONN3(X),U,Y)=$S(B:B,1:0),$P(BGPONN3(X),U,(Y+3))=$S(E:E,1:0),$P(BGPONN3(X),U,(Y+6))=$S(H:H,1:0) Q
 ..I $P(^BGPINDEC(BGPPC,0),U,4)="STI.AB.4A" S Y=$P(^BGPINDEC(BGPPC,21),U,1),$P(BGPONN3(X),U,Y)=$S(B:B,1:0),$P(BGPONN3(X),U,(Y+3))=$S(E:E,1:0),$P(BGPONN3(X),U,(Y+6))=$S(H:H,1:0) Q
 ..I $P($G(^BGPINDEC(BGPPC,19)),U,13) S Y=$P(^BGPINDEC(BGPPC,21),U,1),$P(BGPONN3(X),U,Y)=$S(B:B,1:0),$P(BGPONN3(X),U,(Y+3))=$S(E:E,1:0),$P(BGPONN3(X),U,(Y+6))=$S(H:H,1:0) Q
 ..S Y=$P(^BGPINDEC(BGPPC,21),U,1)
 ..S $P(BGPONN3(X),U,$P(^BGPINDEC(BGPPC,21),U,1))=$S(A:A,1:0),$P(BGPONN3(X),U,(Y+1))=$S(B:B,1:0),$P(BGPONN3(X),U,(Y+2))=$$SL(C)
 ..S $P(BGPONN3(X),U,(Y+3))=$S(D:D,1:0),$P(BGPONN3(X),U,(Y+4))=$S(E:E,1:0),$P(BGPONN3(X),U,(Y+5))=$$SL(F),$P(BGPONN3(X),U,(Y+6))=$S(G:G,1:0),$P(BGPONN3(X),U,(Y+7))=$S(H:H,1:0),$P(BGPONN3(X),U,(Y+8))=$$SL(I)
 Q
SL(V) ;
 I V="" S V=0
 Q $$STRIP^XLFSTR($J(V,5,1)," ")
