BGP8JX ;IHS/CMI/LAB-CREATED BY ^ATXSTX ON FEB 29, 2008;
 ;;8.0;IHS CLINICAL REPORTING;;MAR 12, 2008
 ;
 ; See referenced routines to see taxonomies being loaded.
 ;
START ;
 D ^BGP8JXA ;   BGP ESRD PMS DXS
 D ^BGP8JXB ;   BGP HEDIS VASODILATOR NDC
 D ^BGP8JXC ;   BGP QUANT URINE PROT LOINC
 D ^BGP8JXD ;   BGP QUANT URINE PROT LOINC
 D ^BGP8JXE ;   BGP ESTIMATED GFR LOINC
 D ^BGP8JXF ;   BGP LIPID PROFILE LOINC CODES
 Q
