BGP9NX ; IHS/CMI/LAB -CREATED BY ^ATXSTX ON MAY 06, 2009 ;
 ;;9.0;IHS CLINICAL REPORTING;;JUL 1, 2009
 ;
 ; See referenced routines to see taxonomies being loaded.
 ;
START ;
 D ^BGP9NXA ;   BGP URI DXS
 D ^BGP9NXB ;   BGP URINE GLUCOSE LOINC
 D ^BGP9NXC ;   BGP URINE PROTEIN LOINC CODES
 D ^BGP9NXD ;   BGP VARICELLA CONTRA
 D ^BGP9NXE ;   BGP VARICELLA EVIDENCE
 D ^BGP9NXF ;   BGP VIRAL LOAD LOINC CODES
 D ^BGP9NXG ;   BGP COLO DXS
 Q
