BGPUTX ; IHS/CMI/LAB -CREATED BY ^ATXSTX ON APR 21, 2005 ;
 ;;7.0;IHS CLINICAL REPORTING;;JAN 24, 2007
 ;;;BGPU;;APR 21, 2005
 ;
 ; See referenced routines to see taxonomies being loaded.
 ;
START ;
 D ^BGPUTXA ;   BGP CMS BETA BLOCKER NDC
 D ^BGPUTXB ;   BGP CMS BRADYCARDIA DXS
 D ^BGPUTXC ;   BGP CMS CIRCULATORY SHOCK DXS
 D ^BGPUTXD ;   BGP CMS EJECTION FRACTION CPTS
 D ^BGPUTXE ;   BGP CMS EJECTION FRACTION PROC
 D ^BGPUTXF ;   BGP CMS HEART FAILURE DXS
 D ^BGPUTXG ;   BGP CMS LVSD DXS
 D ^BGPUTXH ;   BGP CMS PNEUMONIA DXS
 D ^BGPUTXI ;   BGP CMS SEPTI/RESP FAIL DXS
 D ^BGPUTXJ ;   BGP COLO CPTS
 D ^BGPUTXK ;   BGP CMS BRADYCARDIA DXS
 D ^BGPUTXL ;   BGP COPD DXS
 D ^BGPUTXM ;   BGP COPD DXS BB CONT
 D ^BGPUTXN ;   BGP CPT FLU
 D ^BGPUTXO ;   BGP CPT HIV TESTS
 D ^BGPUTXP ;   BGP CPT MAMMOGRAM
 D ^BGPUTXQ ;   BGP CPT MAMMOGRAM HEDIS
 D ^BGPUTXR ;   BGP CPT PAP
 D ^BGPUTXS ;   BGP CREATININE CPTS
 D ^BGPUTXT ;   BGP CREATININE LOINC CODES
 D ^BGPUTXU ;   BGP DEPRESSIVE DISORDERS
 D ^BGPUTXV ;   BGP DIPHTHERIA EVIDENCE
 D ^BGPUTXW ;   BGP DV DXS
 D ^BGPUTXX ;   BGP EMPHYSEMA DXS
 D ^BGPUTXY ;   BGP FOBT LOINC CODES
 D ^BGPUTXZ ;   BGP FRACTURE CPTS
 Q
