AGSSDEL ; IHS/ASDS/EFG - Process SSA SSN deletes to NPIRS ;  
 ;;7.1;PATIENT REGISTRATION;;AUG 25,2005
 ;
 Q:'$D(^AGSSTEMP(AGSSITE,"DEL"))
 S (AGSHRN,AGSENT)=""  ;added AGSENT (entry number)
 F  S AGSHRN=$O(^AGSSTEMP(AGSSITE,"DEL",AGSHRN)) Q:'+AGSHRN  D
 .F  S AGSENT=$O(^AGSSTEMP(AGSSITE,"DEL",AGSHRN,AGSENT)) Q:AGSENT=""  D
 ..S AGSUB=^AGSSTEMP(AGSSITE,"DEL",AGSHRN,AGSENT) S ^AGPATCH("DEL",AGSUB)=""
 K AGSHRN,AGSUB,AGSENT
 Q
