AULMICD ;CODE TO CHANGE INTERNAL NUMBERS [ 10/07/86  2:20 PM ]
 ;IN THE ICD FILE, DELETE OLD ONES AND CROSS REFERENCE NEW ONES
 S OS=12262,NS=20000,FO=20001,U="^"
 F I=0:0 S OS=$O(^LORIICD(OS)) Q:(OS="")!(OS=FO)!(OS'?5N)  S FROM="^LORIICD("_OS_",",NS=NS+1,TO="^LORIICD("_NS_"," D ^AIMUGTR1 S $P(^LORIICD(0),U,4)=$P(^LORIICD(0),U,4)+1 S DIK="^LORIICD(",DA=OS D ^DIK
RECROSS F I=FO:1:NS S DIK="^LORIICD(",DA=I D IX1^DIK
 S $P(^LORIICD(0),"^",3)=NS
 Q
