ABMDTDCD ; IHS/ASDST/DMJ - REPORT OF UB92 BILLING CODES ; 
 ;;2.6;IHS 3P BILLING SYSTEM;;NOV 12, 2009
 ;
W1 W !!! S %ZIS="NQ",%ZIS("B")="" D ^%ZIS G:'$D(IO)!$G(POP) QUIT
 S ABM("ION")=ION G:$D(IO("Q")) QUE
 I IO'=IO(0),$E(IOST)'="C",'$D(IO("S")),$P($G(^ABMDPARM(DUZ(2),1,0)),U,13)="Y" W !!,"As specified in the 3P Site Parameters File FORCED QUEUEING is in effect!",! G QUE
PRQUE ;EP - Entry Point for Taskman
S2 S L=0,DIC="^ABMDCODE(",FLDS="[ABMD TM CODES]",BY="[ABMD TM CODES]",FR="A,?",TO="ZZ,?"
 S IOP=ABM("ION")_";80",PG=1
 D EN1^DIP
QUIT D ^%ZISC K ABM
 Q
QUE K IO("Q") S ZTRTN="PRQUE^ABMDTDCD",ZTDESC="REPORT OF 3P BILLING CODES" F ABM="ABM(""ION"")" S ZTSAVE(ABM)=""
 D ^%ZTLOAD W:$D(ZTSK) !,"REQUEST QUEUED!",! G QUIT
