IBINI049	; ; 21-MAR-1994
	;;Version 2.0 ; INTEGRATED BILLING ;; 21-MAR-94
	Q:'DIFQ(354.6)  F I=1:2 S X=$T(Q+I) Q:X=""  S Y=$E($T(Q+I+1),4,999),X=$E(X,4,999) S:$A(Y)=126 I=I+1,Y=$E(Y,2,999)_$E($T(Q+I+1),5,99) S:$A(Y)=61 Y=$E(Y,2,999) X NO E  S @X=Y
Q	Q
	;;^DIC(354.6,0,"GL")
	;;=^IBE(354.6,
	;;^DIC("B","IB FORM LETTER",354.6)
	;;=
	;;^DIC(354.6,"%D",0)
	;;=^^8^8^2940214^^
	;;^DIC(354.6,"%D",1,0)
	;;=This file contains the Header and Main body of letters that are
	;;^DIC(354.6,"%D",2,0)
	;;=generated by the IB package.  Sites should edit the header of the
	;;^DIC(354.6,"%D",3,0)
	;;=letter to their own address.  Sites may edit the main body of the
	;;^DIC(354.6,"%D",4,0)
	;;=letter to change the signer of the letter or add in contact persons 
	;;^DIC(354.6,"%D",5,0)
	;;=and phone numbers.  The text of the letters have been approved
	;;^DIC(354.6,"%D",6,0)
	;;=by MCCR VACO.
	;;^DIC(354.6,"%D",7,0)
	;;= 
	;;^DIC(354.6,"%D",8,0)
	;;=Per VHA Directive 10-93-142, this file definition should not be modified.
	;;^DD(354.6,0)
	;;=FIELD^^2^6
	;;^DD(354.6,0,"DDA")
	;;=N
	;;^DD(354.6,0,"DT")
	;;=2930507
	;;^DD(354.6,0,"IX","B",354.6,.01)
	;;=
	;;^DD(354.6,0,"NM","IB FORM LETTER")
	;;=
	;;^DD(354.6,.01,0)
	;;=NAME^RF^^0;1^K:$L(X)>30!($L(X)<3)!'(X'?1P.E) X
	;;^DD(354.6,.01,1,0)
	;;=^.1
	;;^DD(354.6,.01,1,1,0)
	;;=354.6^B
	;;^DD(354.6,.01,1,1,1)
	;;=S ^IBE(354.6,"B",$E(X,1,30),DA)=""
	;;^DD(354.6,.01,1,1,2)
	;;=K ^IBE(354.6,"B",$E(X,1,30),DA)
	;;^DD(354.6,.01,3)
	;;=Answer must be 3-30 characters in length.
	;;^DD(354.6,.01,21,0)
	;;=^^5^5^2930504^^^
	;;^DD(354.6,.01,21,1,0)
	;;=Enter the name of the form letter.  Normally the names will begin with
	;;^DD(354.6,.01,21,2,0)
	;;=the IB namespace.  The entries in this file will normally
	;;^DD(354.6,.01,21,3,0)
	;;=be sent out with each release in the approved format from VACO.
	;;^DD(354.6,.01,21,4,0)
	;;=Local editing of the Header and of the signature line in the main body
	;;^DD(354.6,.01,21,5,0)
	;;=is permitted.
	;;^DD(354.6,.01,22)
	;;=
	;;^DD(354.6,.01,"DT")
	;;=2930504
	;;^DD(354.6,.02,0)
	;;=LONG NAME^F^^0;2^K:$L(X)>60!($L(X)<3) X
	;;^DD(354.6,.02,3)
	;;=Answer must be 3-60 characters in length.
	;;^DD(354.6,.02,21,0)
	;;=^^1^1^2940213^^
	;;^DD(354.6,.02,21,1,0)
	;;=This is the full descriptive name of this letter.
	;;^DD(354.6,.02,"DT")
	;;=2930427
	;;^DD(354.6,.03,0)
	;;=TYPE^S^1:INITAL EXEMPTION;^0;3^Q
	;;^DD(354.6,.03,21,0)
	;;=^^2^2^2940213^^^
	;;^DD(354.6,.03,21,1,0)
	;;=This field tells what type of application the letter is for.  Currently 
	;;^DD(354.6,.03,21,2,0)
	;;=only one type is defined.
	;;^DD(354.6,.03,"DT")
	;;=2930427
	;;^DD(354.6,.04,0)
	;;=STARTING ADDRESS LINE^NJ2,0^^0;4^K:+X'=X!(X>25)!(X<10)!(X?.E1"."1N.N) X
	;;^DD(354.6,.04,3)
	;;=Type a Number between 10 and 25, 0 Decimal Digits
	;;^DD(354.6,.04,21,0)
	;;=^^6^6^2930507^^
	;;^DD(354.6,.04,21,1,0)
	;;=This is the line number that the patient address should start on.  The
	;;^DD(354.6,.04,21,2,0)
	;;=default if this is unanswered is line 15.  
	;;^DD(354.6,.04,21,3,0)
	;;= 
	;;^DD(354.6,.04,21,4,0)
	;;=To account for slight differences in printers and automated letter folders
	;;^DD(354.6,.04,21,5,0)
	;;=the line that the address starts on is now a parameter.  Set this to the
	;;^DD(354.6,.04,21,6,0)
	;;=correct value for the printer and folder combination for your facility.
	;;^DD(354.6,.04,"DT")
	;;=2930507
	;;^DD(354.6,1,0)
	;;=MAIN BODY^354.61^^1;0
	;;^DD(354.6,1,21,0)
	;;=^^2^2^2930504^^^
	;;^DD(354.6,1,21,1,0)
	;;=This field contains the main body of the letter that will be printed
	;;^DD(354.6,1,21,2,0)
	;;=after the salutation and includes the signature line.
	;;^DD(354.6,1,23,0)
	;;=^^3^3^2930429^
	;;^DD(354.6,1,23,1,0)
	;;=The data in this field will be printed as it is entered.  VA FileMan
	;;^DD(354.6,1,23,2,0)
	;;=utilities are not used to format the data, hence, any imbedded functions
