BMCSKILL ; IHS/PHXAO/TMJ - KILL ALL BMC VARIABLES ;  
 ;;4.0;REFERRED CARE INFO SYSTEM;**9**;JAN 09, 2006;Build 51
 ;BMC*4.0*9 IHS.OIT.FCJ ADDED BMCDX10
 ; Kill all BMC variables including system wide variables
 ;
START ;
 K BMCALTG,BMCALTL,BMCCHS,BMCDXPR,BMCLCAT
 K BMCPCC,BMCCHS,BMCDXPR,BMCLCAT,BMCOLOC,BMCDMGR,BMCCHSS,BMCBOS,BMCCHSA,BMCTXPHC,BMCTXCCP,BMCTXCEX,BMCTXCHC,BMCTXL3P
 K BMCFY,BMCGFY,BMCRY,BMCCURFY,BMCHOUSA,BMCIHSA,BMCOTHRA,BMCCHSE,BMCDXCPT,BMCDX10
 D ^BMCKILL
 D KILL^AUPNPAT
 D ^XBFMK
 Q
