APCDFH1 ; IHS/CMI/LAB - LIST MANAGER API'S FOR FAMILY HISTORY AND API FOR REP FACTORS 19 Jun 2008 2:14 PM ; 
 ;;2.0;IHS PCC SUITE;**2,7**;MAY 14, 2009
 ;
 ;
FM ;EP - called from d/e input template APCD FP (FP)
 S APCDREPI=DA
 D EN^XBNEW("FM1^APCDFH","APCDREPI;APCDDATE")
 K Y
 Q
FM1 ;EP - called from XBNEW call
 S APCDC=0 K APCDCM
 W !!,"Contraceptive Methods currently recorded:"
 I '$O(^AUPNREP(APCDREPI,2101,0)) S APCDC=0 W "  None recorded" G FM12
 D EN^DDIOL("Contraceptive Method","","!?3"),EN^DDIOL("Start Date","","?43"),EN^DDIOL("End Date","","?63")
 D EN^DDIOL($$REPEAT^XLFSTR("-",75),"","!?3")
 K APCDCM S X=0,APCDC=0 F  S X=$O(^AUPNREP(APCDREPI,2101,X)) Q:X'=+X  D
 .S APCDC=APCDC+1,APCDCM(APCDC)=X
 .W !?2,APCDC,")  ",$P(^AUTTCM($P(^AUPNREP(APCDREPI,2101,X,0),U),0),U),?43,$$FMTE^XLFDT($P(^AUPNREP(APCDREPI,2101,X,0),U,2)),?63,$$FMTE^XLFDT($P(^AUPNREP(APCDREPI,2101,X,0),U,3))
 .I $P(^AUPNREP(APCDREPI,2101,X,0),U,6)]"" W !?4,"Comment: ",$P(^AUPNREP(APCDREPI,2101,X,0),U,6)
 .I $P(^AUPNREP(APCDREPI,2101,X,0),U,7)]"" W !?4,"Reason Discontinued: ",$P(^AUPNREP(APCDREPI,2101,X,0),U,7)
FM12 ;
 D EN^DDIOL("","","!!")
 K DIR
 S DIR(0)="S^A:ADD a new Contraceptive Method"_$S(APCDC:";E:Edit an Existing Contraceptive Method;D:Delete an Existing Contraceptive Method",1:"")_";Q:QUIT"
 S DIR("A")="Which action",DIR("B")="Q" KILL DA D ^DIR KILL DIR
 I $D(DIRUT) G FM13
 I Y="Q" G FM13
 S Y="FM"_Y
 D @Y
 G FM1
FM13 ; 
 K Y
 Q
FMA ;
 NEW APCDY
 S DIC("A")="Enter CONTRACEPTIVE METHOD: ",DIC="^AUTTCM(",DIC(0)="AEMQ" D ^DIC
 I Y=-1 K DIC Q
 S APCDCMI=+Y
 S DIC="^AUPNREP("_APCDREPI_",2101,"
 S DA(1)=APCDREPI
 S DIC("P")=$P(^DD(9000017,2101,0),U,2)
 S X=APCDCMI
 S DIE("NO^")=1
 S DIC("DR")=""
 K DD,D0,DO
 D FILE^DICN
 S DIE("NO^")=1
 S (APCDY,DA)=+Y,DA(1)=APCDREPI,DR=".04///^S X=$S($G(APCDDATE):$$FMTE^XLFDT(APCDDATE),1:$$FMTE^XLFDT(DT))"
 S DIE="^AUPNREP("_APCDREPI_",2101,",DIE("NO^")=1
 D ^DIE
 I $P(^AUTTCM(APCDCMI,0),U,1)'="NONE" D
 .S DA=APCDY,DA(1)=APCDREPI,DR=".02R;.03"
 .S DIE="^AUPNREP("_APCDREPI_",2101,",DIE("NO^")=1
 .D ^DIE
 I $P(^AUTTCM(APCDCMI,0),U,1)="NONE" D
 .S DA=APCDY,DA(1)=APCDREPI,DR=".02;.03"
 .S DIE="^AUPNREP("_APCDREPI_",2101,",DIE("NO^")=1
 .D ^DIE
 S DA=APCDY,DA(1)=APCDREPI,DR=".06"
 S DIE="^AUPNREP("_APCDREPI_",2101,",DIE("NO^")=1
 D ^DIE
 I $P(^AUPNREP(APCDREPI,2101,APCDY,0),U,3)]"" D
 .S DA(1)=APCDREPI,DA=APCDY,DR=".05",DIE="^AUPNREP("_APCDREPI_",2101," D ^DIE
 K DIE,DR,DA
 Q
FME ;
 NEW APCDY
 D EN^DDIOL("","","!")
 K DIR
 S DIR(0)="N^1:"_APCDC_":0",DIR("A")="Edit Which One" KILL DA D ^DIR KILL DIR
 I $D(DIRUT) Q
FME1 K DIC,DA,DR
 NEW N
 S (DA,APCDY)=APCDCM(Y),DA(1)=APCDREPI
 ;is this None?
 S N=""
 I $P(^AUTTCM($P(^AUPNREP(APCDREPI,2101,APCDY,0),U),0),U)="NONE" S N=1
 S DR=".01;.02"_$S('N:"R",1:"")_";.03;.06;.04///^S X=$S($G(APCDDATE):$$FMTE^XLFDT(APCDDATE),1:$$FMTE^XLFDT(DT))"
 S DIE="^AUPNREP("_APCDREPI_",2101,",DIE("NO^")=1
 D ^DIE
 I $P(^AUPNREP(APCDREPI,2101,APCDY,0),U,3)]"" D
 .S DA(1)=APCDREPI,DA=APCDY,DR=".05",DIE="^AUPNREP("_APCDREPI_",2101," D ^DIE
 K DIE,DA,DR
 Q
FMD ;
 D EN^DDIOL("","","!")
 K DIR
 S DIR(0)="N^1:"_APCDC_":0",DIR("A")="Delete Which One" KILL DA D ^DIR KILL DIR
 I $D(DIRUT) Q
 K DIC,DA,DR
 S APCDY=+Y
 S DA=APCDCM(APCDY),DA(1)=APCDREPI,DR=".01///@"
 S DIE="^AUPNREP("_APCDREPI_",2101,"
 D ^DIE
 S DA=APCDCM(APCDY),DA(1)=APCDREPI D MULTOSET^APCDRF
 K DA
 Q
 ;
FMN ;;EP - called from d/e input template APCD FM (FM)
 S APCDREPI=DA
 D EN^XBNEW("FMN1^APCDFH1","APCDREPI;APCDDATE")
 K Y
 Q
FMN1 ;EP - called from XBNEW call
 S APCDRFS="",APCDPARS=""
 I '$D(^AUPNREP(APCDREPI)) S X=$$RFADD^APCDRF(APCDREPI) I 'X W $P(X,U,2) Q
FMN12 ;
 D FM1
 K Y
 Q
EDC ;EP - called from d/e input template APCD EDC (EDC)
 S APCDREPI=DA
 D EN^XBNEW("EDC1^APCDFH1","APCDREPI;APCDDATE")
 K Y
 Q
EDC1 ;EP - called from XBNEW call
 S APCDRFS="",APCDPARS=""
 I '$D(^AUPNREP(APCDREPI)) S X=$$RFADD^APCDRF(APCDREPI) I 'X W $P(X,U,2) Q
EDC11 ;
 S DIE="^AUPNREP(",DA=APCDREPI,DR="[APCD EDC EDIT]" D ^DIE
 K DIE,DA,DR
 K Y
 Q
LMP ;EP - called from d/e input template APCD LMP (LMP)
 S APCDREPI=DA
 D EN^XBNEW("LMP1^APCDFH1","APCDREPI;APCDDATE")
 K Y
 Q
LMP1 ;EP - called from XBNEW call
 S APCDRFS="",APCDPARS=""
 I '$D(^AUPNREP(APCDREPI)) S X=$$RFADD^APCDRF(APCDREPI) I 'X W $P(X,U,2) Q
LMP11 ;
 S DIE="^AUPNREP(",DA=APCDREPI,DR="[APCD LMP EDIT]" D ^DIE
 K DIE,DA,DR
 K Y
 Q
