APCLPOS5 ; IHS/OHPRD/TMJ - Non DX/PX Taxonomy Fix ;
 ;;3.0;IHS PCC REPORTS;;FEB 05, 1997
 ;
START ;
 S ATXFLG=1
 D TOBACCO,TBHLTH,DMEDUC,DMADA
 Q
TOBACCO ;add tobacco health factor taxonomy
 W !,"Creating Tobacco Health factors taxonomy... "
 S APCLDA=0 F  S APCLDA=$O(^ATXAX("B","DM AUDIT TOBACCO HLTH FACTORS",APCLDA)) Q:APCLDA=""  I APCLDA S DA=APCLDA S DIK="^ATXAX(" D ^DIK K DA,DIK
 S X="DM AUDIT TOBACCO HLTH FACTORS",DIC="^ATXAX(",DIC(0)="L",DIADD=1,DLAYGO=9002226 D ^DIC K DIC,DA,DIADD,DLAYGO,I
 I Y=-1 W !!,"ERROR IN CREATING DM AUDIT TOBACCO HLTH FACTORS TAX" Q
 S APCLTX=+Y,$P(^ATXAX(APCLTX,0),U,2)="DM AUDIT TOBACCO HLTH FACTORS",$P(^(0),U,5)=DUZ,$P(^(0),U,8)=0,$P(^(0),U,9)=DT,$P(^(0),U,12)=78,$P(^(0),U,13)=0,$P(^(0),U,15)=9999999.64,^ATXAX(APCLTX,21,0)="^9002226.02101A^0^0"
 S APCLTEXT="TOB" F APCLX=1:1:5 S X=$P($T(@APCLTEXT+APCLX),";;",2),DIC="^AUTTHF(",DIC(0)="M" D ^DIC K DIC,DA,DR,DIADD,DLAYGO,DQ,DI,D1,D0 I $P(Y,U)>0 D
 .S ^ATXAX(APCLTX,21,APCLX,0)=+Y,$P(^ATXAX(APCLTX,21,0),U,3)=APCLX,$P(^(0),U,4)=APCLX,^ATXAX(APCLTX,21,"AA",+Y,APCLX)=""
 .Q
 S DA=APCLTX,DIK="^ATXAX(" D IX1^DIK
 Q
DMEDUC ;
 W !,"Creating Education topics taxonomy..."
 S APCLDA=0 F  S APCLDA=$O(^ATXAX("B","DM AUDIT DIABETES EDUC TOPICS",APCLDA)) Q:APCLDA=""  I APCLDA S DA=APCLDA S DIK="^ATXAX(" D ^DIK K DA,DIK
 S X="DM AUDIT DIABETES EDUC TOPICS",DIC="^ATXAX(",DIC(0)="L",DIADD=1,DLAYGO=9002226 D ^DIC K DIC,DA,DIADD,DLAYGO,I
 I Y=-1 W !!,"ERROR IN CREATING DM AUDIT DIABETES EDUC TOPICS TAX" Q
 S APCLTX=+Y,$P(^ATXAX(APCLTX,0),U,2)="DM AUDIT DIABETES EDUC TOPICS",$P(^(0),U,5)=DUZ,$P(^(0),U,8)=0,$P(^(0),U,9)=DT,$P(^(0),U,12)=280,$P(^(0),U,13)=0,$P(^(0),U,15)=9999999.09,^ATXAX(APCLTX,21,0)="^9002226.02101A^0^0"
 S APCLTEXT="EDUC" F APCLX=1:1:10 S X=$P($T(@APCLTEXT+APCLX),";;",2),DIC="^AUTTEDT(",DIC(0)="M" D ^DIC K DIC,DA,DR,DIADD,DLAYGO,DQ,DI,D1,D0 I $P(Y,U)>0 D
 .S ^ATXAX(APCLTX,21,APCLX,0)=+Y,$P(^ATXAX(APCLTX,21,0),U,3)=APCLX,$P(^(0),U,4)=APCLX,^ATXAX(APCLTX,21,"AA",+Y,APCLX)=""
 .Q
 S DA=APCLTX,DIK="^ATXAX(" D IX1^DIK
 Q
DMADA ;
 W !,"Creating DM ADA Codes Taxonomy..."
 S APCLDA=0 F  S APCLDA=$O(^ATXAX("B","DM AUDIT DENTAL EXAM ADA CODES",APCLDA)) Q:APCLDA=""  I APCLDA S DA=APCLDA S DIK="^ATXAX(" D ^DIK K DA,DIK
 S X="DM AUDIT DENTAL EXAM ADA CODES",DIC="^ATXAX(",DIC(0)="L",DIADD=1,DLAYGO=9002226 D ^DIC K DIC,DA,DIADD,DLAYGO,I
 I Y=-1 W !!,"ERROR IN CREATING DM AUDIT DENTAL EXAM ADA CODES TAX" Q
 S APCLTX=+Y,$P(^ATXAX(APCLTX,0),U,2)="DM AUDIT DENTAL EXAM ADA CODES",$P(^(0),U,5)=DUZ,$P(^(0),U,8)=0,$P(^(0),U,9)=DT,$P(^(0),U,12)=174,$P(^(0),U,13)=0,$P(^(0),U,15)=9999999.31,^ATXAX(APCLTX,21,0)="^9002226.02101A^0^0"
 S APCLTEXT="ADA" F APCLX=1:1:2 S X=$P($T(@APCLTEXT+APCLX),";;",2),DIC="^AUTTADA(",DIC(0)="M" D ^DIC K DIC,DA,DR,DIADD,DLAYGO,DQ,DI,D1,D0 I $P(Y,U)>0 D
 .S ^ATXAX(APCLTX,21,APCLX,0)=+Y,$P(^ATXAX(APCLTX,21,0),U,3)=APCLX,$P(^(0),U,4)=APCLX,^ATXAX(APCLTX,21,"AA",+Y,APCLX)=""
 .Q
 S DA=APCLTX,DIK="^ATXAX(" D IX1^DIK
 Q
TBHLTH ;tb health factors taxonomy
 W !,"Creating TB HF Taxonomy... "
 S APCLDA=0 F  S APCLDA=$O(^ATXAX("B","DM AUDIT TB HEALTH FACTORS",APCLDA)) Q:APCLDA=""  I APCLDA S DA=APCLDA S DIK="^ATXAX(" D ^DIK K DA,DIK
 S X="DM AUDIT TB HEALTH FACTORS",DIC="^ATXAX(",DIC(0)="L",DIADD=1,DLAYGO=9002226 D ^DIC K DIC,DIADD,DLAYGO,DA,DR,DO,D0
 I Y=-1 W !!,"ERROR IN CREATING DM AUDIT TB HLTH FACTORS TAX" Q
 S APCLTX=+Y,$P(^ATXAX(APCLTX,0),U,2)="TB TX STATUS HLTH FACTORS",$P(^(0),U,5)=DUZ,$P(^(0),U,8)=0,$P(^(0),U,9)=DT,$P(^(0),U,12)=78,$P(^(0),U,13)=0,$P(^(0),U,15)=9999999.64
 S ^ATXAX(APCLTX,21,0)="^9002226.02101A^0^0"
 S APCLTEXT="TBHF" F APCLX=1:1:4 S X=$P($T(@APCLTEXT+APCLX),";;",2),DIC="^AUTTHF(",DIC(0)="M" D ^DIC K DIC,DA,DR,DIADD,DLAYGO,DQ,DI,D1,D0 I $P(Y,U)>0 D
 .S ^ATXAX(APCLTX,21,APCLX,0)=+Y,$P(^ATXAX(APCLTX,21,0),U,3)=APCLX,$P(^(0),U,4)=APCLX,^ATXAX(APCLTX,21,"AA",+Y,APCLX)=""
 .Q
 S DA=APCLTX,DIK="^ATXAX(" D IX1^DIK
 Q
TBHF ;
 ;;TB - TX UNTREATED
 ;;TB - TX INCOMPLETE
 ;;TB - TX COMPLETE
 ;;TB - TX UNKNOWN
TOB ;
 ;;NON-TOBACCO USER
 ;;CURRENT SMOKER
 ;;CURRENT SMOKELESS
 ;;PREVIOUS SMOKER
 ;;PREVIOUS SMOKELESS
EDUC ;
 ;;DM-COMPLICATIONS
 ;;DM-DIET
 ;;DM-DISEASE PROCESS
 ;;DM-EXERCISE
 ;;DM-FOLLOW UP
 ;;DM-FOOT CARE
 ;;DM-GENERAL INFORMATION
 ;;DM-LIFESTYLE ADAPTATIONS
 ;;DM-MEDICATIONS
 ;;DM-NUTRITION
ADA ;
 ;;0110
 ;;0120
 ;;0150
 ;;9321
 ;;9320
