BJPC2T ; IHS/CMI/LAB -CREATED BY ^ATXSTX ON JUN 23, 2008 ;
 ;;2.0;IHS PCC SUITE;;MAY 14, 2009
 ;
 ; See referenced routines to see taxonomies being loaded.
 ;
START ;
 I '$O(^ATXAX("B","APCL INJ WATER TRANSPORT",0)) D ^BJPC2TA ;   APCL INJ WATER TRANSPORT
 I '$O(^ATXAX("B","ATX ADR NOTIFICATION",0)) D ^BJPC2TB ;   ATX ADR NOTIFICATION
 I '$O(^ATXAX("B","DM AUDIT 75GM 2HR LOINC",0)) D ^BJPC2TC ;   DM AUDIT 75GM 2HR LOINC
 I '$O(^ATXAX("B","DM AUDIT A/C RATIO LOINC",0)) D ^BJPC2TD ;   DM AUDIT A/C RATIO LOINC
 I '$O(^ATXAX("B","DM AUDIT DEPRESSIVE DISORDERS",0)) D ^BJPC2TE ;   DM AUDIT DEPRESSIVE DISORDERS
 I '$O(^ATXAX("B","DM AUDIT EKG CPTS",0)) D ^BJPC2TF ;   DM AUDIT EKG CPTS
 I '$O(^ATXAX("B","DM AUDIT ESTIMATED GFR LOINC",0)) D ^BJPC2TG ;   DM AUDIT ESTIMATED GFR LOINC
 I '$O(^ATXAX("B","DM AUDIT FASTING GLUC LOINC",0)) D ^BJPC2TH ;   DM AUDIT FASTING GLUC LOINC
 I '$O(^ATXAX("B","DM AUDIT FLU CPTS",0)) D ^BJPC2TI ;   DM AUDIT FLU CPTS
 I '$O(^ATXAX("B","DM AUDIT MAMMOGRAM CPTS",0)) D ^BJPC2TJ ;   DM AUDIT MAMMOGRAM CPTS
 I '$O(^ATXAX("B","DM AUDIT MICROALBUMIN LOINC",0)) D ^BJPC2TK ;   DM AUDIT MICROALBUMIN LOINC
 I '$O(^ATXAX("B","DM AUDIT P/C RATIO LOINC",0)) D ^BJPC2TL ;   DM AUDIT P/C RATIO LOINC
 I '$O(^ATXAX("B","DM AUDIT PAP CPTS",0)) D ^BJPC2TM ;   DM AUDIT PAP CPTS
 I '$O(^ATXAX("B","DM AUDIT PNEUMO CPTS",0)) D ^BJPC2TN ;   DM AUDIT PNEUMO CPTS
 I '$O(^ATXAX("B","DM AUDIT PRE-DIABETES DXS",0)) D ^BJPC2TO ;   DM AUDIT PRE-DIABETES DXS
 I '$O(^ATXAX("B","DM AUDIT PROBLEM DIABETES DX",0)) D ^BJPC2TP ;   DM AUDIT PROBLEM DIABETES DX
 I '$O(^ATXAX("B","DM AUDIT PROBLEM HTN DIAGNOSES",0)) D ^BJPC2TQ ;   DM AUDIT PROBLEM HTN DIAGNOSES
 I '$O(^ATXAX("B","DM AUDIT PROBLEM SMOKING DXS",0)) D ^BJPC2TR ;   DM AUDIT PROBLEM SMOKING DXS
 I '$O(^ATXAX("B","DM AUDIT PROBLEM TB DXS",0)) D ^BJPC2TS ;   DM AUDIT PROBLEM TB DXS
 I '$O(^ATXAX("B","DM AUDIT SMOKING RELATED DXS",0)) D ^BJPC2TT ;   DM AUDIT SMOKING RELATED DXS
 I '$O(^ATXAX("B","DM AUDIT TD CPTS",0)) D ^BJPC2TU ;   DM AUDIT TD CPTS
 I '$O(^ATXAX("B","DM AUDIT TYPE I DXS",0)) D ^BJPC2TV ;   DM AUDIT TYPE I DXS
 I '$O(^ATXAX("B","DM AUDIT TYPE II DXS",0)) D ^BJPC2TW ;   DM AUDIT TYPE II DXS
 I '$O(^ATXAX("B","DM AUDIT URINALYSIS LOINC",0)) D ^BJPC2TX ;   DM AUDIT URINALYSIS LOINC
 I '$O(^ATXAX("B","DM AUDIT URINE PROTEIN LOINC",0)) D ^BJPC2TY ;   DM AUDIT URINE PROTEIN LOINC
 I '$O(^ATXAX("B","SURVEILLANCE DIABETES",0)) D ^BJPC2TZ ;   SURVEILLANCE DIABETES
 Q
