ABSPOSBL ; IHS/FCS/DRS - obsolete;   
 ;;1.0;PHARMACY POINT OF SALE;;JUN 21, 2001
 Q
EN ; option ABSP LOG OF BILLING marked as DELETE AT SITE - XINDEX bug?
 D IMPOSS^ABSPOSUE("P","T",,,"EN",$T(+0))
 Q
