BRARPTS ; IHS/ADC/PDW - NO DESCRIPTION PROVIDED ;   
 ;;5.0;Radiology/Nuclear Medicine;;Feb 20, 2004
 ;
PROC1 ;EP---> ALPHABETIC LISTING OF ACTIVE PROCEDURES.
 D ^XBKVAR
 S L=0,DIC=71,FLDS="[RA IHS ALPHA ACTIVE PROC LIST]"
 S BY="[RA IHS ALPHA ACTIVE PROC LIST]"
 S DHD="RADIOLOGY PROCEDURES - ACTIVE ONLY"
 D EN1^DIP
 K BY,DHD,DIC,FLDS,L
