BDMGRG ; IHS/CMI/LAB - BDM DMS GUI Reports ; 09 Feb 2010  7:38 AM
 ;;2.0;DIABETES MANAGEMENT SYSTEM;**7**;JUN 14, 2007;Build 24
 ;
DEBUG(BDMRET,BDMSTR) ;-- debugger
 D DEBUG^%Serenji("DMA12P^BDMGRE(.BDMRET,.BDMSTR)")
 Q
 ;
DAL(RETVAL,BDMSTR) ;-- get audit logic values
 N P,BDMI,BDMYR,BDMYRI,BDMAL
 S P="|"
 S BDMI=0
 K ^BDMTMP($J)
 S RETVAL="^BDMTMP("_$J_")"
 S @RETVAL@(BDMI)="T00010BMXIEN^T00080Logic"_$C(30)
 I $G(BDMSTR)="" S BDMSTR=$$CATSTR^BDMGU(.BDMSTR,.BDMSTR)
 S BDMYR=$P(BDMSTR,P)
 S BDMYRI=$O(^BDMDMTX("B",BDMYR,0))
 I '$G(BDMYRI) S BDMYRI=$O(^BDMDMTX("B",BDMYR_" DIABETES",0))
 S BDMDA=0 F  S BDMDA=$O(^BDMDMTX(BDMYRI,11,BDMDA)) Q:'BDMDA  D
 . Q:'$D(^BDMDMTX(BDMYRI,11,BDMDA,11))
 . S BDMAL=$P($G(^BDMDMTX(BDMYRI,11,BDMDA,0)),U)
 . S BDMI=BDMI+1
 . S @RETVAL@(BDMI)=BDMDA_U_BDMAL_$C(30)
 S @RETVAL@(BDMI+1)=$C(31)
 Q
 ;
DALD(RETVAL,BDMSTR) ;-- return the actual audit logic text
 N P,R,BDMA,BDME,BDMYR,BDMYRI,BDMDESC
 S P="|",R="~"
 S BDMI=0
 K ^BDMTMP($J)
 S RETVAL="^BDMTMP("_$J_")"
 S @RETVAL@(BDMI)="T00080Logic^T00250Description"_$C(30)
 I $G(BDMSTR)="" S BDMSTR=$$CATSTR^BDMGU(.BDMSTR,.BDMSTR)
 S BDMYR=$P(BDMSTR,P)
 S BDMYRI=$O(^BDMDMTX("B",BDMYR,0))
 I '$G(BDMYRI) S BDMYRI=$O(^BDMDMTX("B",BDMYR_" DIABETES",0))
 S BDMLOG=$P(BDMSTR,P,2)
 N I
 F I=1:1 D  Q:$P(BDMLOG,R,I)=""
 . S BDMA=$P(BDMLOG,R,I)
 . Q:BDMA=""
 . S BDME=$E(BDMA,1,30)
 . S BDMI=BDMI+1
 . S @RETVAL@(BDMI)=$P($G(^BDMDMTX(BDMYRI,11,BDMA,0)),U)_$C(30)
 . Q:$P(BDMLOG,R,I)=""
 . S BDMDA=0 F  S BDMDA=$O(^BDMDMTX(BDMYRI,11,BDMA,11,BDMDA)) Q:'BDMDA  D
 .. S BDMI=BDMI+1
 .. S BDMDESC=$G(^BDMDMTX(BDMYRI,11,BDMA,11,BDMDA,0))
 .. S @RETVAL@(BDMI)=BDMDESC_$C(30)
 . S BDMI=BDMI+1
 . S @RETVAL@(BDMI)=$C(30)
 S @RETVAL@(BDMI+1)=$C(31)
 Q
 ;
LM(RETVAL,BDMSTR) ;-- do the Lab/Med Report
 N P,R,BDMJ,BDMH,BDMB,BDME,BDMT
 S BDMJ=$J,BDMH=$H
 S P="|",R="~"
 S BDMI=0
 K ^BDMTMP($J)
 S RETVAL="^BDMTMP("_$J_")"
 S @RETVAL@(BDMI)="T00010Result"_$C(30)
 I $G(BDMSTR)="" S BDMSTR=$$CATSTR^BDMGU(.BDMSTR,.BDMSTR)
 S BDMT=$P(BDMSTR,P)
 S BDMB=$P(BDMSTR,P,2)
 S BDME=$P(BDMSTR,P,3)
 D BDMG^BDMLLMR(BDMJ,BDMH,BDMT,BDMB,BDME)
 S BDMI=BDMI+1
 S @RETVAL@(BDMI)=$C(30)
 S @RETVAL@(BDMI+1)=$C(31)
 Q
 ;
