BDMVAG1 ; cmi/anch/maw - PATIENT DATA VIEW ;
 ;;2.0;DIABETES MANAGEMENT SYSTEM;;AUG 11, 2006
 ;IHS/CMI/THL 2/13/97
 ; -- copy of AGSEENLY with patient defined for browse call
 ;
 D ^AGVAR
L1 ;D ^AG W !!!?27,"Patient Data View System",!!
 ;D PTLK^AG
 I $D(DFN) S AGSEENLY="",AGPAGE=1 G L5
L2 K AG,AGSEENLY,DIC,AG("LKDATA"),AG("LKERR"),AG("LKPRINT"),AGPAGE
 Q
L5 ;D @($P($T(@AGPAGE),";;",2)) W:$Y<7 !?32,"NONE..." X AGLINE("EQ") W !?32,"Press RETURN  " D READ^AGED1
 D @($P($T(@AGPAGE),";;",2)) W:$Y<7 !?32,"NONE..."
 F I=1:1 Q:($Y#20=0)  W !
 ;X AGLINE("EQ")
 ;G L1:$D(DTOUT)!$D(DFOUT)
 ;I $D(DUOUT) S AGPAGE=AGPAGE-1 G L5:AGPAGE>0,L1
 ;I $D(AG("ED")) S AGPAGE=AG("ED") G L5
 S AGPAGE=AGPAGE+1 G L5:AGPAGE<14,L2
1 ;;^AGED1
2 ;;DRAW^AGED2
3 ;;DRAW^AGED3
4 ;;^AGED4
5 ;;^AGED5
6 ;;DRAW^AGED6
7 ;;^AGSEE7
8 ;;DRAW^AGED8
9 ;;DRAW^AGED9
10 ;;DRAW^AGED10
11 ;;DRAW^AGED11
12 ;;DRAW^AGED12
13 ;;DRAW^AGED13
