AUMSCBA2  ;IHS/OIT/NKD - SCB UPDATE - FULL TABLE UPDATE CONT. 03/12/2014 ;
 ;;14.0;TABLE MAINTENANCE;**2**;AUG 20,2013;Build 1
 ;
 Q
STNM ; EP - STATION NUMBER - INSTITUTION FILE
 N AUMT,AUMGL,AUMTGL,AUMCNT,AUMCNT2,AUMP1,AUMP2,AUMP3
 S AUMT="STNM",AUMGL="^DIC(4,",AUMTGL="^TMP(""AUM"","_$J_",""ALL"",""STNM"""
 Q:'$D(@(AUMTGL_")"))
 ;
 I ($G(@(AUMTGL_",0)"))'=0) D
 . S AUMCNT=0 F  S AUMCNT=$O(@(AUMTGL_")")@(AUMCNT)) Q:AUMCNT']""  D
 . . S AUMP1=$P($G(@(AUMTGL_","_AUMCNT_")")),U,1)  ;NAME
 . . S AUMP2=$P($G(@(AUMTGL_","_AUMCNT_")")),U,2)  ;ASUFAC
 . . S AUMP3=$P($G(@(AUMTGL_","_AUMCNT_")")),U,3)  ;STNM
 . . ; DELETE FROM INCORRECT ENTRIES
 . . S AUMCNT2=0 F  S AUMCNT2=$O(^DIC(4,"D",AUMP3,AUMCNT2)) Q:'AUMCNT2  D
 . . . Q:($$GET1^DIQ(9999999.06,AUMCNT2,.0799,"I")=AUMP2)
 . . . S ^TMP("AUM",$J,"COUNT",AUMT)=$G(^TMP("AUM",$J,"COUNT",AUMT))+1
 . . . D ENTRY^AUMSCBD(AUMT,"DEL",$$GET1^DIQ(4,AUMCNT2,.01,"I")_U_$$GET1^DIQ(9999999.06,AUMCNT2,.0799,"I")_U_AUMP3,,)
 . . ; ADD TO CORRECT ENTRY
 . . D ENTRY^AUMSCBD(AUMT,"ADD",$G(@(AUMTGL_","_AUMCNT_")")),,1)
 ;
 K @(AUMTGL_")")
 Q
 ;
