AUMUPD4 ;IHS/OIT/NKD - SCB UPDATE  03/01/2012 ;
 ;;12.0;TABLE MAINTENANCE;**2**;SEP 27,2011;Build 1
 ;
ADDOK ;----- "ADDED" MESSAGE
 D RSLT($J("",5)_"Added : "_L)
 Q
 ;
ADDFAIL ;----- "FAILED" MESSAGE
 D RSLT($J("",5)_$$M(0)_"ADD FAILED => "_L)
 Q
 ;
DASH ;----- PRT DASH LINE
 D RSLT("")
 D RSLT($$REPEAT^XLFSTR("-",$S($G(IOM):IOM-10,1:70)))
 D RSLT("")
 Q
 ;
DIE ;----- DIE EDIT
 N @($P($T(SVARS),";",3))
 L +(@(DIE_DA_")")):10
 E  D RSLT($J("",5)_$$M(0)_"Entry '"_DIE_DA_"' IS LOCKED.  NOTIFY PROGRAMMER.") S Y=1 Q
 D ^DIE
 L -(@(DIE_DA_")"))
 Q
 ;
DIK ;--- KILL ENTRY
 N @($P($T(SVARS),";",3)),DIK
 D ^DIK
 Q
 ;
FILE ;--- FILE NEW ENTRY
 N @($P($T(SVARS),";",3))
 K DD,DO
 S DIC(0)="L"
 D FILE^DICN
 K DIC,DLAYGO
 Q
 ;
M(%) ;--- ERROR MESSAGE
 Q $S(%=0:"ERROR : ",%=1:"NOT ADDED : ",1:"")
 ;
MODOK ;--- IF MOD OK 
 D RSLT($J("",5)_"Changed : "_L)
 Q
 ;
RSLT(%) ;--- ISSUE MESSAGES DURING INSTALL
 N @($P($T(SVARS),";",3))
 D MES^XPDUTL(%)
 Q
 ;
IXDIC(DIC,DIC0,D,X,DLAYGO)   ;
 ;--- CALL TO FILEMAN IX^DIC
 N @($P($T(SVARS),";",3))
 S DIC(0)=DIC0
 K DIC0
 I '$G(DLAYGO) K DLAYGO
 D IX^DIC
 Q Y
 ;
PCLASALL ;EP --- PROVIDER TABLE UPDATE
 N C,CI,A,S,I,II,L,N,NI,AUMI,AUMII
 S C=$O(^DIC(7,"D","")),A="" ;TRAVERSE THE D INDEX (CODE)
 F  Q:$L(C)<1  D
 .S I=$O(^DIC(7,"D",C,"")) ;STORE THE IEN
 .;ITERATE THROUGH MASTER RETRIEVING CODES
 .F  Q:$L(I)<1  D
 ..N S
 ..;IF THE LOCAL CODE MATCHES, UPDATE THE LOCAL ENTRY AND REMOVE FROM THE MASTER
 ..F AUMII=1:1:$P(AUMPRV(0),"^",4) I $D(AUMPRV(AUMII,0)) S CI=$P(AUMPRV(AUMII,0),"^",1) Q:$D(S)  D
 ...I CI=C D RSLT("SERVICES RENDERED BY (PROVIDER) CODE CHANGES"),PCLASDIE S S="" K AUMPRV(AUMII,0)
 ..I '$D(S) S A=A_I_"^" ;IF NOT FOUND IN THE MASTER, STORE IEN IN LOCAL VARIABLE
 ..S I=$O(^DIC(7,"D",C,I)) ;ITERATE TO THE NEXT IEN WITH THIS CODE
 .S C=$O(^DIC(7,"D",C)) ;TRAVERSE TO THE NEXT CODE
 ;ITERATE THROUGH THE STORED IENs
 F AUMI=1:1 S I=$P(A,"^",AUMI) Q:$L(I)<1  D
 .N S
 .S N=$P(^DIC(7,I,0),"^",1) ;STORE THE NAME
 .;ITERATE THROUGH MASTER RETRIEVING NAMES
 .F AUMII=1:1:$P(AUMPRV(0),"^",4) I $D(AUMPRV(AUMII,0)) S NI=$P(AUMPRV(AUMII,0),"^",2) Q:$D(S)  D
 ..;IF THE LOCAL NAME MATCHES, UPDATE THE LOCAL ENTRY AND REMOVE FROM THE MASTER
 ..I NI=N D RSLT("SERVICES RENDERED BY (PROVIDER) NAME CHANGES"),PCLASDIE S S="" K AUMPRV(AUMII,0)
 .;IF NOT FOUND, INACTIVATE LOCAL ENTRY
 .I '$D(S)  D
 ..D RSLT("SERVICES RENDERED BY (PROVIDER) INACTIVATE")
 ..S L=$P(^DIC(7,I,9999999),"^",1)_" "_N_" "_$P(^DIC(7,I,9999999),"^",2)
 ..S DIE="^DIC(7,",DA=I,DR="9999999.06///"_DT D ^DIE
 ..I $D(Y) D RSLT($J("",5)_$$M(0)_"INACTIVATE PROVIDER CODE FAILED => "_L) Q
 ..D RSLT($J("",5)_"INACTIVATED : "_L)
 ;ITERATE THROUGH REMAINING MASTER ENTRIES AND ADD
 F AUMI=1:1:$P(AUMPRV(0),"^",4) I $D(AUMPRV(AUMI,0))  D
 .D RSLT("SERVICES RENDERED BY (PROVIDER) ADD")
 .S C=$P(AUMPRV(AUMI,0),"^",1),N=$P(AUMPRV(AUMI,0),"^",2),A=$P(AUMPRV(AUMI,0),"^",3),P=$P(AUMPRV(AUMI,0),"^",4),R=$P(AUMPRV(AUMI,0),"^",5)
 .S L=C_" "_N_$J("",(32-$L(N)))_A
 .I $D(^DIC(7,"D",C)) D RSLT($J("",5)_$$M(1)_"PROVIDER CODE EXISTS => "_C),RSLT("") Q
 .S DLAYGO=7,DIC="^DIC(7,",X=N,DIC("DR")="1///"_A_";9999999.01///"_C_";9999999.03///"_P_";9999999.05///"_R
 .D FILE
 .D @$S(Y>0:"ADDOK",1:"ADDFAIL")
 .K AUMPRV(AUMI,0)
 Q
PCLASDIE ;
 N C,N,A,P,R,L,DIE,DA,DR
 S C=$P(AUMPRV(AUMII,0),"^",1),N=$P(AUMPRV(AUMII,0),"^",2),A=$P(AUMPRV(AUMII,0),"^",3),P=$P(AUMPRV(AUMII,0),"^",4),R=$P(AUMPRV(AUMII,0),"^",5)
 S L=C_" "_N_" "_A
 S DIE="^DIC(7,",DA=I,DR=".01///"_N_";1///"_A_";9999999.01///"_C_";9999999.03///"_P_";9999999.05///"_R
 I $L($P(AUMPRV(AUMII,0),"^",6))>0 S DR=DR_";9999999.06///"_$P(AUMPRV(AUMII,0),"^",6)
 D ^DIE
 I $D(Y) D RSLT($J("",5)_$$M(0)_"EDIT PROVIDER CODE FAILED => "_L) Q
 D MODOK
 Q
SVARS ;;A,C,E,F,L,M,N,O,P,R,S,T,V;Single-character work variables
 Q
