BUD5TX ; IHS/CMI/LAB -CREATED BY ^ATXSTX ON JAN 16, 2006 ;
 ;;6.0;IHS/RPMS UNIFORM DATA SYSTEM;;JAN 23, 2012;Build 25
 ;;;BUD5;;JAN 16, 2006
 ;
 ; See referenced routines to see taxonomies being loaded.
 ;
START ;
 D ^BUD5TXA ;   BUD L26 CPTS
 D ^BUD5TXB ;   BUD CPT PAP 05
 D ^BUD5TXC ;   BGP PAP LOINC CODES
 D ^BUD5TXD ;   BUD IMM CPTS
 D ^BUD5TXE ;   BUD CPT HIV TESTS
 D ^BUD5TXF ;   BGP HIV TEST LOINC CODES
 Q
