BUD9TX ; IHS/CMI/LAB -CREATED BY ^ATXSTX ON DEC 28, 2009 ;
 ;;7.0;IHS/RPMS UNIFORM DATA SYSTEM;;JAN 23, 2013;Build 31
 ;
 ; See referenced routines to see taxonomies being loaded.
 ;
START ;
 D ^BUD9TXA ;   BUD CPT HIV TESTS
 D ^BUD9TXB ;   BUD CPT PAP 03
 D ^BUD9TXC ;   BUD CPT PAP 04
 D ^BUD9TXD ;   BUD CPT PAP 05
 D ^BUD9TXE ;   BUD CPT PAP 07
 D ^BUD9TXF ;   BUD IMM CPTS
 D ^BUD9TXG ;   BUD L26 CPTS
 D ^BUD9TXH ;   BUD TABLE 6 LINE 16
 D ^BUD9TXI ;   BUD TABLE 6 LINE 17
 D ^BUD9TXJ ;   BUD TABLE 6 LINE 19
 D ^BUD9TXK ;   BUD TABLE 6 LINE 20
 D ^BUD9TXL ;   BUD CPT PAP 08
 D ^BUD9TXM ;   BUD HYSTERECTOMY CPTS
 D ^BUD9TXN ;   BUD HYSTERECTOMY PROCEDURES
 D ^BUD9TXO ;   BUD IPV EVID DISEASE
 D ^BUD9TXP ;   BUD CPT PAP TABLE 6B 09
 D ^BUD9TXQ ;   BUD HYPERTENSION DXS
 D ^BUD9TXR ;   BUD CPT NORMAL DIASTOLIC
 D ^BUD9TXS ;   BUD CPT NORMAL SYSTOLIC
 D ^BUD9TXT ;   BUD DIASTOLIC BP CPTS
 D ^BUD9TXU ;   BUD SYSTOLIC BP CPTS
 D ^BUD9TXV ;   BUD GEST/STEROID DM DX
 D ^BUD9TXW ;   BUD HGBA1C CPTS
 D ^BUD9TXX ;   BUD CPT PAP 09
 D ^BUD9TXY ;   BUD 09 CPT IMM LINE 24
 D ^BUD9TXZ ;   BUD DIABETES DXS FOR TABLE 7
 Q
