AQAOT15 ; GENERATED FROM 'AQAO PLAN EDIT' INPUT TEMPLATE(#1135), FILE 9002168.5;05/13/96
 D DE G BEGIN
DE S DIE="^AQAO(5,",DIC=DIE,DP=9002168.5,DL=1,DIEL=0,DU="" K DG,DE,DB Q:$O(^AQAO(5,DA,""))=""
 I $D(^(0)) S %Z=^(0) S %=$P(%Z,U,1) S:%]"" DE(1)=% S %=$P(%Z,U,2) S:%]"" DE(2)=% S %=$P(%Z,U,3) S:%]"" DE(13)=% S %=$P(%Z,U,5) S:%]"" DE(3)=%
 K %Z Q
 ;
W W !?DL+DL-2,DLB_": "
 Q
O D W W Y W:$X>45 !?9
 I $L(Y)>19,'DV,DV'["I",(DV["F"!(DV["K")) G RW^DIR2
 W:Y]"" "// " I 'DV,DV["I",$D(DE(DQ))#2 S X="" W "  (No Editing)" Q
TR R X:DTIME E  S (DTOUT,X)=U W $C(7)
 Q
A K DQ(DQ) S DQ=DQ+1
B G @DQ
RE G PR:$D(DE(DQ)) D W,TR
N I X="" G A:DV'["R",X:'DV,X:D'>0,A
RD G QS:X?."?" I X["^" D D G ^DIE17
 I X="@" D D G Z^DIE2
 I X=" ",DV["d",DV'["P",$D(^DISV(DUZ,"DIE",DLB)) S X=^(DLB) I DV'["D",DV'["S" W "  "_X
T G M^DIE17:DV,^DIE3:DV["V",P:DV'["S" X:$D(^DD(DP,DIFLD,12.1)) ^(12.1) D SET I 'DDER X:$D(DIC("S")) DIC("S") I  W:'$D(DB(DQ)) "  "_% G V
 K DDER G X
P I DV["P" S DIC=U_DU,DIC(0)=$E("EN",$D(DB(DQ))+1)_"M"_$E("L",DV'["'") S:DIC(0)["L" DLAYGO=+$P(DV,"P",2) I DV'["*" D ^DIC S X=+Y,DIC=DIE G X:X<0
 G V:DV'["N" D D I $L($P(X,"."))>24 K X G Z
 I $P(DQ(DQ),U,5)'["$",X?.1"-".N.1".".N,$P(DQ(DQ),U,5,99)["+X'=X" S X=+X
V D @("X"_DQ) K YS
Z K DIC("S"),DLAYGO I $D(X),X'=U S DG(DW)=X S:DV["d" ^DISV(DUZ,"DIE",DLB)=X G A
X W:'$D(ZTQUEUED) $C(7),"??" I $D(DB(DQ)) G Z^DIE17
 S X="?BAD"
QS S DZ=X D D,QQ^DIEQ G B
D S D=DIFLD,DQ(DQ)=DLB_U_DV_U_DU_U_DW_U_$P($T(@("X"_DQ))," ",2,99) Q
Y I '$D(DE(DQ)) D O G RD:"@"'[X,A:DV'["R"&(X="@"),X:X="@" S X=Y G N
PR S DG=DV,Y=DE(DQ),X=DU I $D(DQ(DQ,2)) X DQ(DQ,2) G RP
R I DG["P",@("$D(^"_X_"0))") S X=+$P(^(0),U,2) G RP:'$D(^(Y,0)) S Y=$P(^(0),U),X=$P(^DD(X,.01,0),U,3),DG=$P(^(0),U,2) G R
 I DG["V",+Y,$P(Y,";",2)["(",$D(@(U_$P(Y,";",2)_"0)")) S X=+$P(^(0),U,2) G RP:'$D(^(+Y,0)) S Y=$P(^(0),U) I $D(^DD(+X,.01,0)) S DG=$P(^(0),U,2),X=$P(^(0),U,3) G R
 X:DG["D" ^DD("DD") I DG["S" S %=$P($P(";"_X,";"_Y_":",2),";") S:%]"" Y=%
RP D O I X="" S X=DE(DQ) G A:'DV,A:DC<2,N^DIE17
I I DV'["I",DV'["#" G RD
 D E^DIE0 G RD:$D(X),PR
 Q
SET I X'?.ANP S DDER=1 Q 
 N DIR S DIR(0)="SMV^"_DU,DIR("V")=1
 I $D(DB(DQ)),'$D(DIQUIET) N DIQUIET S DIQUIET=1
 D ^DIR I 'DDER S %=Y(0),X=Y
 Q
BEGIN S DNM="AQAOT15",DQ=1
 S:$D(DTIME)[0 DTIME=300 S D0=DA,DIEZ=1135,U="^"
1 S DW="0;1",DV="RFI",DU="",DLB="ACTION NUMBER",DIFLD=.01
 S DE(DW)="C1^AQAOT15"
 G RE
C1 G C1S:$D(DE(1))[0 K DB S X=DE(1),DIC=DIE
 K ^AQAO(5,"B",$E(X,1,30),DA)
C1S S X="" Q:DG(DQ)=X  K DB S X=DG(DQ),DIC=DIE
 S ^AQAO(5,"B",$E(X,1,30),DA)=""
 Q
X1 K:$L(X)>10!($L(X)<1)!'(X'?1P.E) X
 I $D(X),X'?.ANP K X
 Q
 ;
2 D:$D(DG)>9 F^DIE17,DE S DQ=2,DW="0;2",DV="RP9002168.6'",DU="",DLB="ACTION CATEGORY",DIFLD=.02
 S DU="AQAO(6,"
 G RE
X2 Q
3 S DW="0;5",DV="RS",DU="",DLB="PLAN STATUS",DIFLD=.05
 S DE(DW)="C3^AQAOT15"
 S DU="1:AWAITING IMPLEMENTATION;2:IMPLEMENTED;3:REVIEWED-EFFECTIVE CHANGE;4:REVIEWED-PARTIALLY EFFECTIVE;5:REVIEWED-INEFFECTIVE CHANGE;9:DELETED;"
 G RE
C3 G C3S:$D(DE(3))[0 K DB S X=DE(3),DIC=DIE
 K ^AQAO(5,"AC",$E(X,1,30),DA)
C3S S X="" Q:DG(DQ)=X  K DB S X=DG(DQ),DIC=DIE
 S ^AQAO(5,"AC",$E(X,1,30),DA)=""
 Q
X3 Q
4 D:$D(DG)>9 F^DIE17,DE S Y=U,DQ=4 D X4 G A:$D(Y)[0,A:Y=U S X=Y,DIC(0)="F",DW=DQ G OUT^DIE17
X4 D IND^AQAOHAPL
 Q
5 D:$D(DG)>9 F^DIE17,DE S DQ=5,D=0 K DE(1) ;5
 S Y="INDICATOR ASSESSMENT REPORT^W^^0;1^Q",DG="IND",DC="^9002168.55" D DIEN^DIWE K DE(1) G A
 ;
6 D:$D(DG)>9 F^DIE17,DE S Y=U,DQ=6 D X6 G A:$D(Y)[0,A:Y=U S X=Y,DIC(0)="F",DW=DQ G OUT^DIE17
X6 D SUMM^AQAOHAPL
 Q
7 S D=0 K DE(1) ;1
 S Y="ACTION TAKEN^W^^0;1^Q",DG="SUMM",DC="^9002168.51" D DIEN^DIWE K DE(1) G A
 ;
8 D:$D(DG)>9 F^DIE17,DE S Y=U,DQ=8 D X8 G A:$D(Y)[0,A:Y=U S X=Y,DIC(0)="F",DW=DQ G OUT^DIE17
X8 D TEAM^AQAOHAPL
 Q
9 S D=0 K DE(1) ;2
 S DIFLD=2,DGO="^AQAOT151",DC="1^9002168.52P^TEAM^",DV="9002168.52MP9002169.1'",DW="0;1",DOW="IMPLEMENTATION TEAM",DLB="Select "_DOW S:D DC=DC_D
 S DU="AQAO1(1,"
 G RE:D I $D(DSC(9002168.52))#2,$P(DSC(9002168.52),"I $D(^UTILITY(",1)="" X DSC(9002168.52) S D=$O(^(0)) S:D="" D=-1 G M9
 S D=$S($D(^AQAO(5,DA,"TEAM",0)):$P(^(0),U,3,4),$O(^(0))'="":$O(^(0)),1:-1)
M9 I D>0 S DC=DC_D I $D(^AQAO(5,DA,"TEAM",+D,0)) S DE(9)=$P(^(0),U,1)
 G RE
R9 D DE
 S D=$S($D(^AQAO(5,DA,"TEAM",0)):$P(^(0),U,3,4),1:1) G 9+1
 ;
10 D:$D(DG)>9 F^DIE17,DE S Y=U,DQ=10 D X10 G A:$D(Y)[0,A:Y=U S X=Y,DIC(0)="F",DW=DQ G OUT^DIE17
X10 S AQAOSTAT=$P(^AQAO(5,D0,0),U,5)
 Q
11 D:$D(DG)>9 F^DIE17,DE S Y=U,DQ=11 D X11 G A:$D(Y)[0,A:Y=U S X=Y,DIC(0)="F",DW=DQ G OUT^DIE17
X11 S:AQAOSTAT=1 Y="@1"
 Q
12 D:$D(DG)>9 F^DIE17,DE S Y=U,DQ=12 D X12 G A:$D(Y)[0,A:Y=U S X=Y,DIC(0)="F",DW=DQ G OUT^DIE17
X12 S:AQAOSTAT=9 Y="@9"
 Q
13 S DW="0;3",DV="D",DU="",DLB="IMPLEMENTATION DATE",DIFLD=.03
 G RE
X13 S %DT="EX" D ^%DT S X=Y K:Y<1 X
 Q
 ;
14 D:$D(DG)>9 F^DIE17 G ^AQAOT152
