AZXARD1 ; IHS/PHXAO/TMJ - NO DESCRIPTION PROVIDED ;
 ;;2.0;RELEASE OF INFORMATION;;FEB 21, 2002
START ;
 D GETREF
 Q:AZXAQ
 D BROWSE
 D XIT
 Q
 ;
GETREF ; GET REFERRAL
 S AZXAQ=1
 S DIC="^AZXAREF(",DIC(0)="AEMQ" D DIC^AZXAFMC
 Q:Y<0
 S AZXARIEN=+Y
 S AZXAQ=0
 Q
 ;
BROWSE ;
 S XBRP="DISP^AZXARD1"
 S XBRC="",XBRX="XIT^AZXARD1",XBIOP=0 D ^XBDBQUE
 ;D VIEWR^XBLM("^AZXAVLP")
 Q
XIT ;EP
 D ^AZXAKILL
 K ^TMP("AZXARDSP",$J)
 Q
DISP ;EP
 D EN^VALM("AZXA RECORD DISPLAY")
 D CLEAR^VALM1
 Q
HDR ; -- header code
 S VALMHDR(1)="User:  "_$P(^VA(200,DUZ,0),U)
 Q
 ;
INIT ; -- init variables and list array
 D EP^AZXARD(AZXARIEN)
 S VALMCNT=$O(^TMP("AZXARDSP",$J,""),-1)
 Q
 ;
HELP ; -- help code
 S X="?" D DISP^XQORM1 W !!
 Q
 ;
EXIT ; -- exit code
 Q
