ADE6O1 ; IHS/HQT/MJL - DENTAL TABLE UPDATES;  [ 03/24/1999   9:04 AM ]
 ;;6.0;ADE;;APRIL 1999
 ;
 ;Data for modified DENTAL OPERATIVE SITE Codes
OPMOD ;;EP
 ;;FROM^DECIDUOUS CANINE,MAND LEFT^M^22D
 ;;TO^DECIDUOUS CANINE,MAND LEFT^22D^M
 ;;FROM^DECIDUOUS CANINE,MAND RIGHT^R^27D
 ;;TO^DECIDUOUS CANINE,MAND RIGHT^27D^R
 ;;FROM^DECIDUOUS CANINE,MAX LEFT^H^11D
 ;;TO^DECIDUOUS CANINE,MAX LEFT^11D^H
 ;;FROM^DECIDUOUS CANINE,MAX RIGHT^C ^6D
 ;;TO^DECIDUOUS CANINE,MAX RIGHT^6D^C
 ;;FROM^DECIDUOUS CENTRAL INCISOR,MAND LEFT^O^24D
 ;;TO^DECIDUOUS CENTRAL INCISOR,MAND LEFT^24D^O
 ;;FROM^DECIDUOUS CENTRAL INCISOR,MAND RIGHT^P^25D
 ;;TO^DECIDUOUS CENTRAL INCISOR,MAND RIGHT^25D^P
 ;;FROM^DECIDUOUS CENTRAL INCISOR,MAX RIGHT^E ^8D
 ;;TO^DECIDUOUS CENTRAL INCISOR,MAX RIGHT^8D^E
 ;;FROM^DECIDUOUS CENTRAL INCISOR,MAX LEFT^F ^9D
 ;;TO^DECIDUOUS CENTRAL INCISOR,MAX LEFT^9D^F
 ;;FROM^DECIDUOUS FIRST MOLAR,MAND LEFT^L ^21D
 ;;TO^DECIDUOUS FIRST MOLAR,MAND LEFT^21D^L
 ;;FROM^DECIDUOUS FIRST MOLAR,MAND RIGHT^S^28D
 ;;TO^DECIDUOUS FIRST MOLAR,MAND RIGHT^28D^S
 ;;FROM^DECIDUOUS FIRST MOLAR,MAX LEFT^I^12D
 ;;TO^DECIDUOUS FIRST MOLAR,MAX LEFT^12D^I
 ;;FROM^DECIDUOUS FIRST MOLAR,MAX RIGHT^B ^5D
 ;;TO^DECIDUOUS FIRST MOLAR,MAX RIGHT^5D^B
 ;;FROM^DECIDUOUS LATERAL INCISOR,MAND LEFT^N^23D
 ;;TO^DECIDUOUS LATERAL INCISOR,MAND LEFT^23D^N
 ;;FROM^DECIDUOUS LATERAL INCISOR,MAND RIGHT^Q^26D
 ;;TO^DECIDUOUS LATERAL INCISOR,MAND RIGHT^26D^Q
 ;;FROM^DECIDUOUS LATERAL INCISOR,MAX RIGHT^D ^7D
 ;;TO^DECIDUOUS LATERAL INCISOR,MAX RIGHT^7D^D
 ;;FROM^DECIDUOUS LATERAL INCISOR,MAX LEFT^G^10D
 ;;TO^DECIDUOUS LATERAL INCISOR,MAX LEFT^10D^G
 ;;FROM^DECIDUOUS SECOND MOLAR,MAND LEFT^K^20D
 ;;TO^DECIDUOUS SECOND MOLAR,MAND LEFT^20D^K
 ;;FROM^DECIDUOUS SECOND MOLAR,MAND RIGHT^T^29D
 ;;TO^DECIDUOUS SECOND MOLAR,MAND RIGHT^29D^T
 ;;FROM^DECIDUOUS SECOND MOLAR,MAX LEFT^J^13D
 ;;TO^DECIDUOUS SECOND MOLAR,MAX LEFT^13D^J
 ;;FROM^DECIDUOUS SECOND MOLAR,MAX RIGHT^A^4D
 ;;TO^DECIDUOUS SECOND MOLAR,MAX RIGHT^4D^A
 ;;END
