ADETMP ; IHS/HQT/MJL - RECOMPILE MISSING DATA [ 03/24/1999   9:04 AM ]
 ;;6.0;ADE;;APRIL 1999
 W !!,"This option will update the quarters starting from the last"
 W !,"quarter compiled and ending at the 4th quarter 1998"
 S DIR(0)="YA",DIR("B")="YES",DIR("A")="Continue? "
 D ^DIR Q:'Y
 I $D(DTOUT)!($D(DUOUT))!($D(DIROUT)) Q
 S ZTRTN="START^ADETMP",ZTDESC="DENTAL STATS COMPILE QUARTERS",ZTIO=""
 D ^%ZTLOAD
 Q
START ;
 S ADEQTR=0 F  S ADEQTR=$O(^ADEKNT("AD",ADEQTR)) Q:ADEQTR=""  S ADEQTR($P(ADEQTR,".",1,2))=""
 S ADEQTR=0 F  S ADELQTR=ADEQTR,ADEQTR=$O(ADEQTR(ADEQTR)) Q:ADEQTR=""  S ADEQDF=ADEQTR-ADELQTR I ADEQDF>.1,ADELQTR,ADEQDF'=.7 Q
 S ADEYQ=ADELQTR
 K ADEQDF,ADELQTR,ADEQTR
 F  D KNS^ADEKNT(ADEYQ,"ALL") Q:ADEYQ[98.4  S ADEYQ=ADEYQ+.1 S:ADEYQ[".5" ADEYQ=ADEYQ\1+1+.1
 Q
