ACHSDNU ; IHS/ITSC/PMF - DENIAL UNMET NEED LIST (1/3) ; [ 10/16/2001   8:16 AM ]
 ;;3.1;CONTRACT HEALTH MGMT SYSTEM;;JUN 11, 2001
 ;
BDT W !!,"Enter the BEGINNING ISSUE DATE for this report: " D READ^ACHSFU G K:$D(DUOUT)!$D(DTOUT)!(Y="") S:Y?1"?".E Y="?" S X=Y,%DT="XEP" D ^%DT G BDT:Y<1 S ACHSBDT=Y I Y>DT D FUDT^ACHS G BDT
 ;
EDT W !!,"Enter the ENDING ISSUE DATE for this report: " D READ^ACHSFU G K:$D(DTOUT)!(Y=""),BDT:$D(DUOUT) S:Y?1"?".E Y="?" S X=Y,%DT="XEP" D ^%DT G EDT:Y<1 S ACHSEDT=Y I Y>DT D FUDT^ACHS G EDT
 I ACHSEDT<ACHSBDT W !!,*7,"The END is before the BEGINNING." G BDT
 S ACHSIO=IO
 ;
DEV S %ZIS="OPQ" D ^%ZIS I POP G K
 G:'$D(IO("Q")) ^ACHSDNU1 K IO("Q") I $D(IO("S"))!($E(IOST)'="P") W *7,!,"Please queue to system printers." D ^%ZISC G DEV
 X ^%ZOSF("UCI") S ZTRTN="^ACHSDNU1",ZTUCI=Y,ZTDESC="CHS UNMET Need List, "_$E(ACHSBDT,2,7)_" to "_$E(ACHSEDT,2,7)
 F ACHS="ACHSBDT","ACHSEDT","DUZ(2)" S ZTSAVE(ACHS)=""
 D ^%ZTLOAD G:'$D(ZTSK) DEV
K D ^%ZISC K ACHS,ACHSBDT,ACHSEDT,ACHSIO,ACHSQIO,DTOUT,DUOUT,ZTIO,ZTSK
 Q
