ACHSAI ; IHS/ITSC/PMF - GENERATE INITIAL CHS DOCUMENTS ;  [ 10/16/2001   8:16 AM ]
 ;;3.1;CONTRACT HEALTH MGMT SYSTEM;;JUN 11, 2001
 ;
 ;CALLED FROM OPTION [ACHSAI]
A1 ;
 S (ACHSTYP,ACHSPROV,ACHSCONP,ACHSCAN,ACHSSCC,ACHSCOPT,ACHSESDA,ACHSESDO,ACHSFDT,ACHSTDT,ACHSHON,ACHSHONN,ACHSEDOS)=""
 S (ACHSORDN,ACHSDES,ACHSRALR,ACHSRCOI,ACHSRDXN,ACHSRMPC,ACHSRPHY,ACHSRPXN,ACHSRECT,ACHSRDXN,ACHSSVDT,ACHSWKLD,ACHSDEST,ACHSDCR,ACHSAGRP,ACHSAGRN)=""
 K DFN,ACHSRDX,ACHSRPX,ACHSREF
 D ^ACHSA                      ;ENTER DOCUMENTS (1/8)
 I '$D(DUOUT),'$D(DTOUT) G A1
 D EN^XBVK("ACHS"),^ACHSVAR
 K DUOUT,DTOUT ; 3*17  6/12/00  PMF
 Q
 ;
