COPY ;COPY ONE GLOBAL TO ANOTHER [ 09/16/85  12:39 PM ]
 ;TOM FISHER
 K ^TXDATA
 W !,"COPY GLOBAL DATA FOR TRANSMISSION TO IBM"
 R !,"NUMBER OF RECORDS TO BYPASS  ",BYPASS
 R !,"NUMBER OF RECORDS TO COPY  ",RECCOPY
 S ^TXDATA(0)=^AGTXDATA(0)
 S X="1" F I=1:1:BYPASS-1 S X=$O(^AGTXDATA(X)) W:X="" !,"BYPASS REQUEST IS GREATER THAT DATA IN GLOBAL" Q:X="" 
 F I=1:1:RECCOPY S X=$O(^AGTXDATA(X)) G:X="" END  D CONVERT
END W !,I Q
 Q
CONVERT ;CONVERT DATA TO ALL CAPITAL LETTERS
 S DATA=^AGTXDATA(X)
 S HOLD=DATA,DATA=""
 F J=1:1:$L(HOLD) S CHR=$E(HOLD,J) S DATA=DATA_$S(CHR?1L:$C($A(CHR)-32),"[]\`"[CHR:"",1:CHR)    
 S ^TXDATA(I)=DATA
 Q
