IS00007A ;Compiled from script 'Generated: HL IHS DW1 A08-O' on SEP 08, 2008
 ;Part 2
 ;Copyright 2008 SAIC
EN S @INV@("PID13")=X K DXS,D0
 ;SET PID14 = ""
 S D0=INDA S X=""
 S @INV@("PID14")=X K DXS,D0
 ;SET PID15 = ""
 S D0=INDA S X=""
 S @INV@("PID15")=X K DXS,D0
 ;SET PID16 = ""
 S D0=INDA S X=""
 S @INV@("PID16")=X K DXS,D0
 ;SET PID17 = ""
 S D0=INDA S X=""
 S @INV@("PID17")=X K DXS,D0
 ;SET PID18 = ""
 S D0=INDA S X=""
 S @INV@("PID18")=X K DXS,D0
 ;SET PID19 = INSGX\^INTHL7F(16262,5)\\999\"OUTPUT TRANSFORM"
 S D0=INDA S X="OUTPUT TRANSFORM"
 S X1="^INTHL7F(16262,5)" X:$L($G(@X1)) $G(@X1) S X=$E(X,1,999)
 S @INV@("PID19")=X K DXS,D0
 ;SET PID20 = ""
 S D0=INDA S X=""
 S @INV@("PID20")=X K DXS,D0
 ;SET PID21 = ""
 S D0=INDA S X=""
 S @INV@("PID21")=X K DXS,D0
 ;SET PID22 = ""
 S D0=INDA S X=""
 S @INV@("PID22")=X K DXS,D0
 ;SET PID23 = ""
 S D0=INDA S X=""
 S @INV@("PID23")=X K DXS,D0
 ;SET PID24 = ""
 S D0=INDA S X=""
 S @INV@("PID24")=X K DXS,D0
 ;SET PID25 = ""
 S D0=INDA S X=""
 S @INV@("PID25")=X K DXS,D0
 ;SET PID26 = ""
 S D0=INDA S X=""
 S @INV@("PID26")=X K DXS,D0
 ;SET PID27 = INSGX\^INTHL7F(16270,5)\\999\"OUTPUT TRANSFORM"
 S D0=INDA S X="OUTPUT TRANSFORM"
 S X1="^INTHL7F(16270,5)" X:$L($G(@X1)) $G(@X1) S X=$E(X,1,999)
 S @INV@("PID27")=X K DXS,D0
 ;SET PID28 = ""
 S D0=INDA S X=""
 S @INV@("PID28")=X K DXS,D0
 ;SET PID29 = INSGX\^INTHL7F(16272,5)\\999\"OUTPUT TRANSFORM"
 S D0=INDA S X="OUTPUT TRANSFORM"
 S X1="^INTHL7F(16272,5)" X:$L($G(@X1)) $G(@X1) S X=$E(X,1,999)
 S @INV@("PID29")=X K DXS,D0
 ;SET PID30 = ""
 S D0=INDA S X=""
 S @INV@("PID30")=X K DXS,D0
 ;SET PID31 = ""
 S D0=INDA S X=""
 S @INV@("PID31")=X K DXS,D0
 ;SET PID32 = ""
 S D0=INDA S X=""
 S @INV@("PID32")=X K DXS,D0
 ;SET PID33 = ""
 S D0=INDA S X=""
 S @INV@("PID33")=X K DXS,D0
 ;SET PID34 = ""
 S D0=INDA S X=""
 S @INV@("PID34")=X K DXS,D0
 ;SET PID35 = ""
 S D0=INDA S X=""
 S @INV@("PID35")=X K DXS,D0
 ;SET PID36 = ""
 S D0=INDA S X=""
 S @INV@("PID36")=X K DXS,D0
 ;SET PID37 = ""
 S D0=INDA S X=""
 S @INV@("PID37")=X K DXS,D0
 ;SET PID38 = ""
 S D0=INDA S X=""
 S @INV@("PID38")=X K DXS,D0
 D:'INVS MC^INHS
 K LINE S LINE="",CP=0 S L1="PID" S:$TR(L1,$G(SUBDELIM))="" L1="" D SETPIECE^INHU(.LINE,DELIM,1,L1,.CP) S L1=$G(@INV@("PID1")) S:$TR(L1,$G(SUBDELIM))="" L1=""
 D SETPIECE^INHU(.LINE,DELIM,2,L1,.CP) S L1=$G(@INV@("PID2")) S:$TR(L1,$G(SUBDELIM))="" L1="" D SETPIECE^INHU(.LINE,DELIM,3,L1,.CP) S L1=$G(@INV@("PID3"))
 S:$TR(L1,$G(SUBDELIM))="" L1="" D SETPIECE^INHU(.LINE,DELIM,4,L1,.CP) S L1=$G(@INV@("PID4")) S:$TR(L1,$G(SUBDELIM))="" L1="" D SETPIECE^INHU(.LINE,DELIM,5,L1,.CP)
 S L1=$G(@INV@("PID5")) S:$TR(L1,$G(SUBDELIM))="" L1="" D SETPIECE^INHU(.LINE,DELIM,6,L1,.CP) S L1=$G(@INV@("PID6")) S:$TR(L1,$G(SUBDELIM))="" L1="" D SETPIECE^INHU(.LINE,DELIM,7,L1,.CP)
 S L1=$G(@INV@("PID7")) S:$TR(L1,$G(SUBDELIM))="" L1="" D SETPIECE^INHU(.LINE,DELIM,8,L1,.CP) S L1=$G(@INV@("PID8")) S:$TR(L1,$G(SUBDELIM))="" L1="" D SETPIECE^INHU(.LINE,DELIM,9,L1,.CP)
 S L1=$G(@INV@("PID9")) S:$TR(L1,$G(SUBDELIM))="" L1="" D SETPIECE^INHU(.LINE,DELIM,10,L1,.CP) S L1=$G(@INV@("PID10")) S:$TR(L1,$G(SUBDELIM))="" L1="" D SETPIECE^INHU(.LINE,DELIM,11,L1,.CP)
 S L1=$G(@INV@("PID11")) S:$TR(L1,$G(SUBDELIM))="" L1="" D SETPIECE^INHU(.LINE,DELIM,12,L1,.CP) S L1=$G(@INV@("PID12")) S:$TR(L1,$G(SUBDELIM))="" L1=""
 D SETPIECE^INHU(.LINE,DELIM,13,L1,.CP) S L1=$G(@INV@("PID13")) S:$TR(L1,$G(SUBDELIM))="" L1="" D SETPIECE^INHU(.LINE,DELIM,14,L1,.CP) S L1=$G(@INV@("PID14"))
 S:$TR(L1,$G(SUBDELIM))="" L1="" D SETPIECE^INHU(.LINE,DELIM,15,L1,.CP) S L1=$G(@INV@("PID15")) S:$TR(L1,$G(SUBDELIM))="" L1="" D SETPIECE^INHU(.LINE,DELIM,16,L1,.CP)
 S L1=$G(@INV@("PID16")) S:$TR(L1,$G(SUBDELIM))="" L1="" D SETPIECE^INHU(.LINE,DELIM,17,L1,.CP) S L1=$G(@INV@("PID17")) S:$TR(L1,$G(SUBDELIM))="" L1=""
 D SETPIECE^INHU(.LINE,DELIM,18,L1,.CP) S L1=$G(@INV@("PID18")) S:$TR(L1,$G(SUBDELIM))="" L1="" D SETPIECE^INHU(.LINE,DELIM,19,L1,.CP) S L1=$G(@INV@("PID19"))
 S:$TR(L1,$G(SUBDELIM))="" L1="" D SETPIECE^INHU(.LINE,DELIM,20,L1,.CP) S L1=$G(@INV@("PID20")) S:$TR(L1,$G(SUBDELIM))="" L1="" D SETPIECE^INHU(.LINE,DELIM,21,L1,.CP)
 S L1=$G(@INV@("PID21")) S:$TR(L1,$G(SUBDELIM))="" L1="" D SETPIECE^INHU(.LINE,DELIM,22,L1,.CP) S L1=$G(@INV@("PID22")) S:$TR(L1,$G(SUBDELIM))="" L1=""
 D SETPIECE^INHU(.LINE,DELIM,23,L1,.CP) S L1=$G(@INV@("PID23")) S:$TR(L1,$G(SUBDELIM))="" L1="" D SETPIECE^INHU(.LINE,DELIM,24,L1,.CP) S L1=$G(@INV@("PID24"))
 S:$TR(L1,$G(SUBDELIM))="" L1="" D SETPIECE^INHU(.LINE,DELIM,25,L1,.CP) S L1=$G(@INV@("PID25")) S:$TR(L1,$G(SUBDELIM))="" L1="" D SETPIECE^INHU(.LINE,DELIM,26,L1,.CP)
 S L1=$G(@INV@("PID26")) S:$TR(L1,$G(SUBDELIM))="" L1="" D SETPIECE^INHU(.LINE,DELIM,27,L1,.CP) S L1=$G(@INV@("PID27")) S:$TR(L1,$G(SUBDELIM))="" L1=""
 D SETPIECE^INHU(.LINE,DELIM,28,L1,.CP) S L1=$G(@INV@("PID28")) S:$TR(L1,$G(SUBDELIM))="" L1="" D SETPIECE^INHU(.LINE,DELIM,29,L1,.CP) S L1=$G(@INV@("PID29"))
 S:$TR(L1,$G(SUBDELIM))="" L1="" D SETPIECE^INHU(.LINE,DELIM,30,L1,.CP) S L1=$G(@INV@("PID30")) S:$TR(L1,$G(SUBDELIM))="" L1="" D SETPIECE^INHU(.LINE,DELIM,31,L1,.CP)
 S L1=$G(@INV@("PID31")) S:$TR(L1,$G(SUBDELIM))="" L1="" D SETPIECE^INHU(.LINE,DELIM,32,L1,.CP) S L1=$G(@INV@("PID32")) S:$TR(L1,$G(SUBDELIM))="" L1=""
 D SETPIECE^INHU(.LINE,DELIM,33,L1,.CP) S L1=$G(@INV@("PID33")) S:$TR(L1,$G(SUBDELIM))="" L1="" D SETPIECE^INHU(.LINE,DELIM,34,L1,.CP) S L1=$G(@INV@("PID34"))
 S:$TR(L1,$G(SUBDELIM))="" L1="" D SETPIECE^INHU(.LINE,DELIM,35,L1,.CP) S L1=$G(@INV@("PID35")) S:$TR(L1,$G(SUBDELIM))="" L1="" D SETPIECE^INHU(.LINE,DELIM,36,L1,.CP)
 S L1=$G(@INV@("PID36")) S:$TR(L1,$G(SUBDELIM))="" L1="" D SETPIECE^INHU(.LINE,DELIM,37,L1,.CP) S L1=$G(@INV@("PID37")) S:$TR(L1,$G(SUBDELIM))="" L1=""
 D SETPIECE^INHU(.LINE,DELIM,38,L1,.CP) S L1=$G(@INV@("PID38")) S:$TR(L1,$G(SUBDELIM))="" L1="" D SETPIECE^INHU(.LINE,DELIM,39,L1,.CP)
 S LCT=LCT+1,^UTILITY("INH",$J,LCT)=LINE I $D(LINE)>9 M ^UTILITY("INH",$J,LCT)=LINE
 SET INSETID=0
 ;SET ZP21 = INSGX\^INTHL7F(16288,5)\\999\"OUTPUT TRANSFORM"
 S D0=INDA S X="OUTPUT TRANSFORM"
 S X1="^INTHL7F(16288,5)" X:$L($G(@X1)) $G(@X1) S X=$E(X,1,999)
 S @INV@("ZP21")=X K DXS,D0
 ;SET ZP22 = ""
 S D0=INDA S X=""
 S @INV@("ZP22")=X K DXS,D0
 ;SET ZP23 = ""
 S D0=INDA S X=""
 S @INV@("ZP23")=X K DXS,D0
 ;SET ZP24 = ""
 S D0=INDA S X=""
 S @INV@("ZP24")=X K DXS,D0
 ;SET ZP25 = ""
 S D0=INDA S X=""
 S @INV@("ZP25")=X K DXS,D0
 ;SET ZP26 = ""
 S D0=INDA S X=""
 S @INV@("ZP26")=X K DXS,D0
 ;SET ZP27 = ""
 S D0=INDA S X=""
 S @INV@("ZP27")=X K DXS,D0
 ;SET ZP28 = ""
 S D0=INDA S X=""
 S @INV@("ZP28")=X K DXS,D0
 ;SET ZP29 = ""
 S D0=INDA S X=""
 S @INV@("ZP29")=X K DXS,D0
 ;SET ZP210 = ""
 S D0=INDA S X=""
 S @INV@("ZP210")=X K DXS,D0
 ;SET ZP211 = INSGX\^INTHL7F(16298,5)\\999\"OUTPUT TRANSFORM"
 S D0=INDA S X="OUTPUT TRANSFORM"
 S X1="^INTHL7F(16298,5)" X:$L($G(@X1)) $G(@X1) S X=$E(X,1,999)
 S @INV@("ZP211")=X K DXS,D0
 ;SET ZP212 = ""
 S D0=INDA S X=""
 S @INV@("ZP212")=X K DXS,D0
 ;SET ZP213 = ""
 S D0=INDA S X=""
 S @INV@("ZP213")=X K DXS,D0
 ;SET ZP214 = ""
 S D0=INDA S X=""
 S @INV@("ZP214")=X K DXS,D0
 ;SET ZP215 = INSGX\^INTHL7F(16302,5)\\999\"OUTPUT TRANSFORM"
 S D0=INDA S X="OUTPUT TRANSFORM"
 S X1="^INTHL7F(16302,5)" X:$L($G(@X1)) $G(@X1) S X=$E(X,1,999)
 S @INV@("ZP215")=X K DXS,D0
 ;SET ZP216 = INSGX\^INTHL7F(16303,5)\\999\"OUTPUT TRANSFORM"
9 G EN^IS00007B
