LRHYBC9 ;VA/DALOI/HOAK - UTILITY FOR LAB HOWDY ; 13-Aug-2013 09:16 ; MKK
 ;;5.2;LAB SERVICE;**405,1033**;NOV 01, 1997
 ;
SCROLON(LRHYTM,LRHYBM) ;
 ;MAKES A SCROLLING REGION ON THE SCREEN
 ;LRHYTM=TOP MARGIN(Y), LRHYBM=BOTTOM MARGIN(Y)
 ;
 D ENS^%ZISS
 S IOTM=LRHYTM,IOBM=LRHYBM
 W @IOSTBM
 Q
SCROLOFF() ;
 ;RETURNS SCREEN TO NORMAL SETTINGS Y=0 to 24
 D ENS^%ZISS
 S IOTM=0,IOBM=24
 W @IOSTBM
 D KILL^%ZISS
 Q
