ACDV4MES ;IHS/ADC/EDE/KML - V4 MESSAGES OF INTEREST 7/11/94;
 ;;4.1;CHEMICAL DEPENDENCY MIS;;MAY 11, 1998
 ;;
EN ;EP
 ;//[ACD REPORTS]
 ;//^ACDWSTAF
 W !!,"PLEASE NOTE: V4 OF CDMIS STARTS STORING THE NUMBER OF HOURS A PROVIDER SPENT"
 W !,"FOR PREVENTIONS AND 'CRISIS/BRIEF' CONTACT TYPES. THIS MEANS THE REPORTS"
 W !,"WILL ONLY REFLECT THESE 'HOURS' AS OF THE CDMIS V4 INSTALL DATE AT YOUR SITE.",!
 Q
 ;
EN1 ;EP
 ;//^ACDVSAVE
 W !!,"PLEASE NOTE THAT THE CDMIS V4 EXTRACT PROGRAM 'WILL NOT'"
 W !,"EXTRACT INTERVENTION DATA.",!
 Q
EN2 ;EP
 ;//[ACDREG]
 W !!,"ENTER THE PATIENTS NAME 'LASTNAME,FIRST'. IF THE PATIENT"
 W !,"IS REGISTERED, YOU WILL GET A MESSAGE SAYING SO. IF THE"
 W !,"PATIENT 'IS NOT' REGISTERED, YOU WILL GET A '??' DISPLAYED"
 W !,"AFTER YOU ENTER 'LASTNAME,FIRSTNAME'",!!
 S DIR(0)="E",DIR("A")="Press <return> to continue:" D ^DIR K DIR
 Q
EN3 ;EP
 ;//[ACDR5MENU]
 W !!,"NOTE: CDMIS V4 HAS A NEW 'CDMIS QUARTERLY/ANNUAL' FILE"
 W !,"THAT HOLDS YOUR PROGRAM SPECIFIC DATA. THESE"
 W !,"REPORTS STILL LOOK AT THE OLD 'CDMIS PROGRAM FILE' SO"
 W !,"UNTIL THEY ARE RE-WRITTEN, THEY WILL NOT REFLECT YOUR"
 W !,"TRUE PROGRAM SPECIFIC DATA.",!!
 W !!,"WHEN YOU DO DATA ENTRY FOR YOUR PROGRAM SPECIFIC DATA,"
 W !,"IT IS NOW STORED IN THE NEW 'CDMIS QUARTERLY/ANNUAL' FILE."
 W !!,"WHEN YOUR PROGRAM DATA IS EXTRACTED AND SENT TO HQW,"
 W !,"IT IS TAKEN OUT OF THE NEW 'CDMIS QUARTERLY/ANNUAL' FILE."
 S DIR(0)="E",DIR("A")="Press <return> to continue." D ^DIR K DIR
 Q
EN4 ;EP
 ;//^ACDDFAC
 W !!,"PLEASE NOTE: THIS UTILITY 'WILL NOT' DELETE YOUR "
 W !,"INTERVENTION DATA. THIS UTILITY ONLY DELETES DATA THAT"
 W !,"IS EXTRACTED (I.E., PREVENTION DATA AND CLIENT VISIT DATA)"
 W !
 Q
 ;
EN5 ;EP
 ;//^ACDPSAVE
 W !!,"I WILL EXTRACT THE DATA FROM YOUR NEW FILE CALLED"
 W !,"'CDMIS QUARTERLY/ANNUAL'"
 W !
 Q
 ;
EN6 ;EP
 ;;[ACD REPORTS]
 W !!,"PLEASE NOTE: CDMIS 4 STARTED STORING STATE AND TRIBE CODES SO REPORTS, WHEN"
 W !,"RUN BY TRIBE OR STATE, WILL ONLY BE ACCURATE AS OF THE CDMIS 4 INSTALL DATE.",!
 Q
