ACDWRP26 ;IHS/ADC/EDE/KML - OUTPUT GENERATOR;
 ;;4.1;CHEMICAL DEPENDENCY MIS;;MAY 11, 1998
 ;Reports 309
 I '$D(^TMP("ACD",ACDJOB,ACDBT,ACDTGSUB,"VAL")) D ^ACDWK Q
 S (ACDNCNT,ACDVCNT)=0
P1 ;
 D C
 S ACDP1=""
 F  S ACDP1=$O(^TMP("ACD",ACDJOB,ACDBT,ACDTGSUB,"VAL",ACDP1)) Q:ACDP1=""  W !,$E(ACDP1,1,22) D P2 Q:$D(DIRUT)
 W:'$D(DIRUT) !?35,"=====",?62,"=====",!?35,ACDNCNT,?62,ACDVCNT
 D ^ACDWK
 Q
P2 ;
 S ACDP2="" F  D F Q:$D(DIRUT)  S ACDP2=$O(^TMP("ACD",ACDJOB,ACDBT,ACDTGSUB,"VAL",ACDP1,ACDP2)) Q:ACDP2=""  W ?24,$E(ACDP2,1,14) D P3 Q:$D(DIRUT)
 Q
P3 ;
 S ACDP3="" F  D F Q:$D(DIRUT)  S ACDP3=$O(^TMP("ACD",ACDJOB,ACDBT,ACDTGSUB,"VAL",ACDP1,ACDP2,ACDP3)) Q:ACDP3=""  S ACDN0=^(ACDP3) D P4 Q:$D(DIRUT)
 Q
P4 ;
 S ACDVIS=$P(ACDN0,U),ACDNUMR=$P(ACDN0,U,2)
 D F Q:$D(DIRUT)  W ?35,ACDNUMR,?44,$E(ACDP3,1,14),?62,ACDVIS,?72,$J(ACDNUMR/ACDVIS,7,2),!
 S ACDNCNT=ACDNCNT+ACDNUMR,ACDVCNT=ACDVCNT+ACDVIS
 Q
F ;Form feed
 I $Y+4>IOSL D F^ACDWUTL D:'$D(DIRUT) C
 Q
C ;Column
 W !,ACDC(1),?24,ACDC(2),?35,ACDC(3),?44,ACDC(4),?62,ACDC(5),?71,ACDC(6),!,ACDH(1),!
 Q
