OCXOZ09 ;SLC/RJS,CLA - Order Check Scan ;JUN 15,2011 at 12:58
 ;;3.0;ORDER ENTRY/RESULTS REPORTING;**32**;Dec 17,1997
 ;;  ;;ORDER CHECK EXPERT version 1.01 released OCT 29,1998
 ;
 ; ***************************************************************
 ; ** Warning: This routine is automatically generated by the   **
 ; ** Rule Compiler (^OCXOCMP) and ANY changes to this routine  **
 ; ** will be lost the next time the rule compiler executes.    **
 ; ***************************************************************
 ;
 Q
 ;
CHK192 ; Look through the current environment for valid Event/Elements for this patient.
 ;  Called from CHK188+14^OCXOZ08.
 ;
 Q:$G(OCXOERR)
 ;
 ;    Local CHK192 Variables
 ; OCXDF(68) ---> Data Field: MISSING ANGIOGRAM, CATH PERIF LAB TESTS (FREE TEXT)
 ;
 ;      Local Extrinsic Functions
 ; FILE(DFN,65, -----> FILE DATA IN PATIENT ACTIVE DATA FILE  (Event/Element: SESSION ORDER FOR ANGIOGRAM)
 ; MTSTF( -----------> MISSING TESTS DURING SESSION
 ;
 S OCXDF(68)=$$MTSTF("PROTHROMBIN TIME,PARTIAL THROMBOPLASTIN TIME") I $L(OCXDF(68)),($L(OCXDF(68))>0) S OCXOERR=$$FILE(DFN,65,"68") Q:OCXOERR 
 Q
 ;
CHK196 ; Look through the current environment for valid Event/Elements for this patient.
 ;  Called from CHK163+13^OCXOZ07.
 ;
 Q:$G(OCXOERR)
 ;
 ;    Local CHK196 Variables
 ; OCXDF(2) ----> Data Field: FILLER (FREE TEXT)
 ; OCXDF(37) ---> Data Field: PATIENT IEN (NUMERIC)
 ; OCXDF(67) ---> Data Field: CONTRAST MEDIA CODE (FREE TEXT)
 ; OCXDF(73) ---> Data Field: ORDERABLE ITEM IEN (NUMERIC)
 ;
 ;      Local Extrinsic Functions
 ;
 S OCXDF(2)=$P($G(OCXPSD),"|",2) I $L(OCXDF(2)) D CHK198
 S OCXDF(73)=$P($G(OCXPSD),"|",1) I $L(OCXDF(73)) S OCXDF(67)=$$CM^ORQQRA(OCXDF(73)) I $L(OCXDF(67)),(OCXDF(67)["M") S OCXDF(37)=$G(DFN) I $L(OCXDF(37)) D CHK467^OCXOZ0E
 S OCXDF(37)=$G(DFN) I $L(OCXDF(37)) D CHK498^OCXOZ0F
 Q
 ;
CHK198 ; Look through the current environment for valid Event/Elements for this patient.
 ;  Called from CHK196+13.
 ;
 Q:$G(OCXOERR)
 ;
 ;    Local CHK198 Variables
 ; OCXDF(2) ----> Data Field: FILLER (FREE TEXT)
 ;
 I (OCXDF(2)="RA") D CHK199
 I ($E(OCXDF(2),1,2)="PS") D CHK363^OCXOZ0C
 Q
 ;
CHK199 ; Look through the current environment for valid Event/Elements for this patient.
 ;  Called from CHK198+8.
 ;
 Q:$G(OCXOERR)
 ;
 ;    Local CHK199 Variables
 ; OCXDF(37) ---> Data Field: PATIENT IEN (NUMERIC)
 ; OCXDF(69) ---> Data Field: RECENT BARIUM STUDY FLAG (BOOLEAN)
 ; OCXDF(73) ---> Data Field: ORDERABLE ITEM IEN (NUMERIC)
 ;
 ;      Local Extrinsic Functions
 ; RECBAR( ----------> RECENT BARIUM STUDY
 ;
 S OCXDF(73)=$P($G(OCXPSD),"|",1) I $L(OCXDF(73)) D CHK201
 S OCXDF(37)=$G(DFN) I $L(OCXDF(37)) S OCXDF(69)=$P($$RECBAR(OCXDF(37),48),"^",1) I $L(OCXDF(69)),(OCXDF(69)) S OCXDF(73)=$P($G(OCXPSD),"|",1) I $L(OCXDF(73)) D CHK219
 Q
 ;
CHK201 ; Look through the current environment for valid Event/Elements for this patient.
 ;  Called from CHK199+13.
 ;
 Q:$G(OCXOERR)
 ;
 ;    Local CHK201 Variables
 ; OCXDF(37) ---> Data Field: PATIENT IEN (NUMERIC)
 ; OCXDF(56) ---> Data Field: CONTRAST MEDIA FLAG (BOOLEAN)
 ; OCXDF(65) ---> Data Field: CONTRAST MEDIA ALLERGY FLAG (BOOLEAN)
 ; OCXDF(67) ---> Data Field: CONTRAST MEDIA CODE (FREE TEXT)
 ; OCXDF(73) ---> Data Field: ORDERABLE ITEM IEN (NUMERIC)
 ; OCXDF(78) ---> Data Field: PATIENT TOO BIG FOR SCANNER FLAG (BOOLEAN)
 ;
 ;      Local Extrinsic Functions
 ; CM( --------------> DOES THIS RADIOLOGY PROCEDURE USE A CONTRAST MEDIA
 ; CTMRI( -----------> CT MRI PHYSICAL LIMITS
 ; FILE(DFN,106, ----> FILE DATA IN PATIENT ACTIVE DATA FILE  (Event/Element: RADIOLOGY PROCEDURE CONTAINS NON-BARIUM CONTRAST MEDIA)
 ;
 S OCXDF(56)=$P($$CM(OCXDF(73)),"^",1) I $L(OCXDF(56)),(OCXDF(56)) S OCXDF(37)=$G(DFN) I $L(OCXDF(37)) S OCXDF(65)=$$ORCHK^GMRAOR(OCXDF(37),"CM","") I $L(OCXDF(65)) D CHK208
 S OCXDF(37)=$G(DFN) I $L(OCXDF(37)) S OCXDF(78)=$P($$CTMRI(OCXDF(37),OCXDF(73)),"^",1) I $L(OCXDF(78)),(OCXDF(78)) D CHK242^OCXOZ0A
 S OCXDF(67)=$$CM^ORQQRA(OCXDF(73)) I $L(OCXDF(67)),(OCXDF(67)["M") S OCXOERR=$$FILE(DFN,106,"") Q:OCXOERR 
 Q
 ;
CHK208 ; Look through the current environment for valid Event/Elements for this patient.
 ;  Called from CHK201+18.
 ;
 Q:$G(OCXOERR)
 ;
 ;    Local CHK208 Variables
 ; OCXDF(65) ---> Data Field: CONTRAST MEDIA ALLERGY FLAG (BOOLEAN)
 ; OCXDF(66) ---> Data Field: CONTRAST MEDIA CODE TRANSLATION (FREE TEXT)
 ; OCXDF(67) ---> Data Field: CONTRAST MEDIA CODE (FREE TEXT)
 ; OCXDF(73) ---> Data Field: ORDERABLE ITEM IEN (NUMERIC)
 ;
 ;      Local Extrinsic Functions
 ; CONTRANS( --------> CONTRAST MEDIA CODE TRANSLATION
 ; FILE(DFN,66, -----> FILE DATA IN PATIENT ACTIVE DATA FILE  (Event/Element: CONTRAST MEDIA ALLERGY)
 ;
 I (OCXDF(65)) S OCXDF(67)=$$CM^ORQQRA(OCXDF(73)) I $L(OCXDF(67)) S OCXDF(66)=$$CONTRANS(OCXDF(67)),OCXOERR=$$FILE(DFN,66,"66") Q:OCXOERR 
 Q
 ;
CHK219 ; Look through the current environment for valid Event/Elements for this patient.
 ;  Called from CHK199+14.
 ;
 Q:$G(OCXOERR)
 ;
 ;    Local CHK219 Variables
 ; OCXDF(37) ---> Data Field: PATIENT IEN (NUMERIC)
 ; OCXDF(67) ---> Data Field: CONTRAST MEDIA CODE (FREE TEXT)
 ; OCXDF(70) ---> Data Field: RECENT BARIUM STUDY TEXT (FREE TEXT)
 ; OCXDF(73) ---> Data Field: ORDERABLE ITEM IEN (NUMERIC)
 ; OCXDF(121) --> Data Field: RECENT BARIUM STUDY ORDER STATUS (FREE TEXT)
 ;
 ;      Local Extrinsic Functions
 ; RECBAR( ----------> RECENT BARIUM STUDY
 ; RECBARST( --------> RECENT BARIUM ORDER STATUS
 ;
 S OCXDF(67)=$$CM^ORQQRA(OCXDF(73)) I $L(OCXDF(67)),(OCXDF(67)["B") S OCXDF(70)=$P($$RECBAR(OCXDF(37),48),"^",3),OCXDF(121)=$P($$RECBARST(OCXDF(37),48),"^",2) D CHK224
 Q
 ;
CHK224 ; Look through the current environment for valid Event/Elements for this patient.
 ;  Called from CHK219+16.
 ;
 Q:$G(OCXOERR)
 ;
 ;      Local Extrinsic Functions
 ; FILE(DFN,67, -----> FILE DATA IN PATIENT ACTIVE DATA FILE  (Event/Element: RECENT BARIUM STUDY ORDERED)
 ;
 S OCXOERR=$$FILE(DFN,67,"70,121") Q:OCXOERR 
 Q
 ;
CM(OCXOI) ;  Compiler Function: DOES THIS RADIOLOGY PROCEDURE USE A CONTRAST MEDIA
 ;
 N OCXVAL S OCXVAL=$$CM^ORQQRA(OCXOI) Q:((OCXVAL["B")!(OCXVAL["M")) 1_U_OCXVAL Q 0
 ;  
 ;
CONTRANS(OCXC) ;  Compiler Function: CONTRAST MEDIA CODE TRANSLATION
 ;
 N OCXX
 Q:'$L($G(OCXC)) "" S OCXX=$S((OCXC["B"):"Barium",1:"")
 I (OCXC["M") S:$L(OCXX) OCXX=OCXX_" and/or " S OCXX=OCXX_"Unspecified contrast media"
 Q OCXX
 ;
CTMRI(DFN,OCXOI) ;  Compiler Function: CT MRI PHYSICAL LIMITS
 ;
 N OCXDEV,OCXWTP,OCXHTP,OCXWTL,OCXHTL
 S OCXDEV=$$TYPE^ORKRA(OCXOI)
 Q:'((OCXDEV="MRI")!(OCXDEV="CT")) 0_U
 S OCXWTP=$P($$WT^ORQPTQ4(DFN),U,2),OCXHTP=$P($$HT^ORQPTQ4(DFN),U,2)
 I (OCXDEV="CT") S OCXWTL=$$GET^XPAR("ALL","ORK CT LIMIT WT",1,"Q"),OCXHTL=$$GET^XPAR("ALL","ORK CT LIMIT HT",1,"Q")
 I (OCXDEV="CT"),(OCXWTL),(OCXWTP>OCXWTL) Q 1_U_"too heavy"_U_"CT scanner"
 I (OCXDEV="CT"),(OCXHTL),(OCXHTP>OCXHTL) Q 1_U_"too tall"_U_"CT scanner"
 I (OCXDEV="MRI") S OCXWTL=$$GET^XPAR("ALL","ORK MRI LIMIT WT",1,"Q"),OCXHTL=$$GET^XPAR("ALL","ORK MRI LIMIT HT",1,"Q")
 I (OCXDEV="MRI"),(OCXWTL),(OCXWTP>OCXWTL) Q 1_U_"too heavy"_U_"MRI scanner"
 I (OCXDEV="MRI"),(OCXHTL),(OCXHTP>OCXHTL) Q 1_U_"too tall"_U_"MRI scanner"
 Q 0_U
 ;
FILE(DFN,OCXELE,OCXDFL) ;     This Local Extrinsic Function logs a validated event/element.
 ;
 N OCXTIMN,OCXTIML,OCXTIMT1,OCXTIMT2,OCXDATA,OCXPC,OCXPC,OCXVAL,OCXSUB,OCXDFI
 S DFN=+$G(DFN),OCXELE=+$G(OCXELE)
 ;
 Q:'DFN 1 Q:'OCXELE 1 K OCXDATA
 ;
 S OCXDATA(DFN,OCXELE)=1
 F OCXPC=1:1:$L(OCXDFL,",") S OCXDFI=$P(OCXDFL,",",OCXPC) I OCXDFI D
 .S OCXVAL=$G(OCXDF(+OCXDFI)),OCXDATA(DFN,OCXELE,+OCXDFI)=OCXVAL
 ;
 M ^TMP("OCXCHK",$J,DFN)=OCXDATA(DFN)
 ;
 Q 0
 ;
MTSTF(OILIST) ;  Compiler Function: MISSING TESTS DURING SESSION
 ;
 N OCXPC,OCXOI,OCXOUT S OCXOUT=""
 F OCXPC=1:1:$L(OILIST,",") S OCXOI=$P(OILIST,",",OCXPC) I $L(OCXOI) D
 .N OCXL,OCXF,OCXD0
 .S OCXL="",OCXF=$$TERMLKUP(OCXOI,.OCXL)
 .S OCXD0=0 F  S OCXD0=$O(OCXL(OCXD0)) Q:'OCXD0  Q:$$OISESS^ORKCHK2(+OCXD0)
 .Q:OCXD0
 .S:$L(OCXOUT) OCXOUT=OCXOUT_", " S OCXOUT=OCXOUT_OCXOI
 Q OCXOUT
 ;
RECBAR(DFN,HOURS) ;  Compiler Function: RECENT BARIUM STUDY
 ;
 Q:'$G(DFN) 0 Q:'$G(HOURS) 0 N OUT S OUT=$$RECENTBA^ORKRA(DFN,HOURS) Q:'$L(OUT) 0 Q 1_U_OUT
 ;  
 ;
RECBARST(DFN,HOURS)    ;  Compiler Function: RECENT BARIUM ORDER STATUS
 ;
 Q:'$G(DFN) 0 Q:'$G(HOURS) 0
 N ORDER S ORDER=$P($$RECENTBA^ORKRA(DFN,HOURS),U) Q:'$L(ORDER) 0
 N STATUS S STATUS=$P($$STATUS^ORQOR2(ORDER),U,2) Q:'$L(STATUS) 0
 Q 1_U_STATUS
 ;
TERMLKUP(OCXTERM,OCXLIST) ;
 Q $$TERM^OCXOZ01(OCXTERM,.OCXLIST)
 ;
