OCXOZ0I ;SLC/RJS,CLA - Order Check Scan ;JAN 28,2014 at 03:37
 ;;3.0;ORDER ENTRY/RESULTS REPORTING;**32,221,243**;Dec 17,1997;Build 242
 ;;  ;;ORDER CHECK EXPERT version 1.01 released OCT 29,1998
 ;
 ; ***************************************************************
 ; ** Warning: This routine is automatically generated by the   **
 ; ** Rule Compiler (^OCXOCMP) and ANY changes to this routine  **
 ; ** will be lost the next time the rule compiler executes.    **
 ; ***************************************************************
 ;
 Q
 ;
EL111 ; Examine every rule that involves Element #111 [GLUCOPHAGE CREATININE > 1.5]
 ;  Called from SCAN+9^OCXOZ01.
 ;
 Q:$G(OCXOERR)
 ;
 D R67R1A^OCXOZ11   ; Check Relation #1 in Rule #67 'GLUCOPHAGE - LAB RESULTS'
 Q
 ;
EL112 ; Examine every rule that involves Element #112 [NO GLUCOPHAGE CREATININE]
 ;  Called from SCAN+9^OCXOZ01.
 ;
 Q:$G(OCXOERR)
 ;
 D R67R2A^OCXOZ11   ; Check Relation #2 in Rule #67 'GLUCOPHAGE - LAB RESULTS'
 Q
 ;
EL122 ; Examine every rule that involves Element #122 [AMITRIPTYLINE ORDER]
 ;  Called from SCAN+9^OCXOZ01.
 ;
 Q:$G(OCXOERR)
 ;
 D R68R1A^OCXOZ12   ; Check Relation #1 in Rule #68 'DANGEROUS MEDS OVER AGE 64'
 Q
 ;
EL125 ; Examine every rule that involves Element #125 [MED ORDER FOR PT > 64]
 ;  Called from SCAN+9^OCXOZ01.
 ;
 Q:$G(OCXOERR)
 ;
 D R68R1A^OCXOZ12   ; Check Relation #1 in Rule #68 'DANGEROUS MEDS OVER AGE 64'
 D R68R2A^OCXOZ12   ; Check Relation #2 in Rule #68 'DANGEROUS MEDS OVER AGE 64'
 D R68R3A^OCXOZ12   ; Check Relation #3 in Rule #68 'DANGEROUS MEDS OVER AGE 64'
 Q
 ;
EL123 ; Examine every rule that involves Element #123 [CHLORPROPAMIDE ORDER]
 ;  Called from SCAN+9^OCXOZ01.
 ;
 Q:$G(OCXOERR)
 ;
 D R68R2A^OCXOZ12   ; Check Relation #2 in Rule #68 'DANGEROUS MEDS OVER AGE 64'
 Q
 ;
EL124 ; Examine every rule that involves Element #124 [DIPYRIDAMOLE ORDER]
 ;  Called from SCAN+9^OCXOZ01.
 ;
 Q:$G(OCXOERR)
 ;
 D R68R3A^OCXOZ12   ; Check Relation #3 in Rule #68 'DANGEROUS MEDS OVER AGE 64'
 Q
 ;
EL131 ; Examine every rule that involves Element #131 [GREATER THAN LAB THRESHOLD]
 ;  Called from SCAN+9^OCXOZ01.
 ;
 Q:$G(OCXOERR)
 ;
 D R69R1A^OCXOZ12   ; Check Relation #1 in Rule #69 'LAB THRESHOLD'
 Q
 ;
EL132 ; Examine every rule that involves Element #132 [LESS THAN LAB THRESHOLD]
 ;  Called from SCAN+9^OCXOZ01.
 ;
 Q:$G(OCXOERR)
 ;
 D R69R1A^OCXOZ12   ; Check Relation #1 in Rule #69 'LAB THRESHOLD'
 Q
 ;
EL28 ; Examine every rule that involves Element #28 [RADIOLOGY ORDER]
 ;  Called from SCAN+9^OCXOZ01.
 ;
 Q:$G(OCXOERR)
 ;
 D R70R1A^OCXOZ13   ; Check Relation #1 in Rule #70 'NO ALLERGY ASSESSMENT'
 D R72R1A^OCXOZ14   ; Check Relation #1 in Rule #72 'ALLERGIES UNASSESSIBLE'
 Q
 ;
EL135 ; Examine every rule that involves Element #135 [DIET ORDER]
 ;  Called from SCAN+9^OCXOZ01.
 ;
 Q:$G(OCXOERR)
 ;
 D R70R1A^OCXOZ13   ; Check Relation #1 in Rule #70 'NO ALLERGY ASSESSMENT'
 D R72R1A^OCXOZ14   ; Check Relation #1 in Rule #72 'ALLERGIES UNASSESSIBLE'
 Q
 ;
EL136 ; Examine every rule that involves Element #136 [NO ALLERGY ASSESSMENT]
 ;  Called from SCAN+9^OCXOZ01.
 ;
 Q:$G(OCXOERR)
 ;
 D R70R1A^OCXOZ13   ; Check Relation #1 in Rule #70 'NO ALLERGY ASSESSMENT'
 Q
 ;
EL137 ; Examine every rule that involves Element #137 [PHARMACY ORDER]
 ;  Called from SCAN+9^OCXOZ01.
 ;
 Q:$G(OCXOERR)
 ;
 D R70R1A^OCXOZ13   ; Check Relation #1 in Rule #70 'NO ALLERGY ASSESSMENT'
 D R72R1A^OCXOZ14   ; Check Relation #1 in Rule #72 'ALLERGIES UNASSESSIBLE'
 Q
 ;
EL138 ; Examine every rule that involves Element #138 [DUP OPIOID MEDS]
 ;  Called from SCAN+9^OCXOZ01.
 ;
 Q:$G(OCXOERR)
 ;
 D R71R1A^OCXOZ14   ; Check Relation #1 in Rule #71 'OPIOID MEDICATIONS'
 Q
 ;
EL139 ; Examine every rule that involves Element #139 [OPIOID MED ORDER]
 ;  Called from SCAN+9^OCXOZ01.
 ;
 Q:$G(OCXOERR)
 ;
 D R71R1A^OCXOZ14   ; Check Relation #1 in Rule #71 'OPIOID MEDICATIONS'
 Q
 ;
EL140 ; Examine every rule that involves Element #140 [ALLERGIES UNASSESSIBLE]
 ;  Called from SCAN+9^OCXOZ01.
 ;
 Q:$G(OCXOERR)
 ;
 D R72R1A^OCXOZ14   ; Check Relation #1 in Rule #72 'ALLERGIES UNASSESSIBLE'
 Q
 ;
R3R1A ; Verify all Event/Elements of  Rule #3 'CRITICAL LAB RESULTS'  Relation #1 'CRITICAL LAB TEST'
 ;  Called from EL24+5^OCXOZ0G.
 ;
 Q:$G(OCXOERR)
 ;
 ;      Local Extrinsic Functions
 ; MCE24( ----------->  Verify Event/Element: 'HL7 LAB TEST RESULTS CRITICAL'
 ;
 Q:$G(^OCXS(860.2,3,"INACT"))
 ;
 I $$MCE24 D R3R1B^OCXOZ0J
 Q
 ;
MCE24() ; Verify Event/Element: HL7 LAB TEST RESULTS CRITICAL
 ;
 ;
 N OCXRES
 I $L(OCXDF(37)) S OCXRES(24,37)=OCXDF(37)
 Q:'(OCXDF(37)) 0 I $D(^TMP("OCXCHK",$J,OCXDF(37),24)) Q $G(^TMP("OCXCHK",$J,OCXDF(37),24))
 Q 0
 ;
