OCXOZ0H ;SLC/RJS,CLA - Order Check Scan ;JAN 28,2014 at 03:37
 ;;3.0;ORDER ENTRY/RESULTS REPORTING;**32,221,243**;Dec 17,1997;Build 242
 ;;  ;;ORDER CHECK EXPERT version 1.01 released OCT 29,1998
 ;
 ; ***************************************************************
 ; ** Warning: This routine is automatically generated by the   **
 ; ** Rule Compiler (^OCXOCMP) and ANY changes to this routine  **
 ; ** will be lost the next time the rule compiler executes.    **
 ; ***************************************************************
 ;
 Q
 ;
EL142 ; Examine every rule that involves Element #142 [NO SS REFILL REQUEST]
 ;  Called from SCAN+9^OCXOZ01.
 ;
 Q:$G(OCXOERR)
 ;
 D R44R1A^OCXOZ0R   ; Check Relation #1 in Rule #44 'ORDER REQUIRES ELECTRONIC SIGNATURE'
 Q
 ;
EL143 ; Examine every rule that involves Element #143 [SS REFILL REQUEST]
 ;  Called from SCAN+9^OCXOZ01.
 ;
 Q:$G(OCXOERR)
 ;
 D R44R2A^OCXOZ0S   ; Check Relation #2 in Rule #44 'ORDER REQUIRES ELECTRONIC SIGNATURE'
 Q
 ;
EL58 ; Examine every rule that involves Element #58 [NEW SITE FLAGGED ORDER]
 ;  Called from SCAN+9^OCXOZ01.
 ;
 Q:$G(OCXOERR)
 ;
 D R48R1A^OCXOZ0S   ; Check Relation #1 in Rule #48 'SITE FLAGGED ORDER'
 D R48R2A^OCXOZ0T   ; Check Relation #2 in Rule #48 'SITE FLAGGED ORDER'
 Q
 ;
EL127 ; Examine every rule that involves Element #127 [INPATIENT]
 ;  Called from SCAN+9^OCXOZ01.
 ;
 Q:$G(OCXOERR)
 ;
 D R48R1A^OCXOZ0S   ; Check Relation #1 in Rule #48 'SITE FLAGGED ORDER'
 D R49R1A^OCXOZ0U   ; Check Relation #1 in Rule #49 'SITE FLAGGED RESULT'
 Q
 ;
EL128 ; Examine every rule that involves Element #128 [OUTPATIENT]
 ;  Called from SCAN+9^OCXOZ01.
 ;
 Q:$G(OCXOERR)
 ;
 D R48R2A^OCXOZ0T   ; Check Relation #2 in Rule #48 'SITE FLAGGED ORDER'
 D R49R2A^OCXOZ0U   ; Check Relation #2 in Rule #49 'SITE FLAGGED RESULT'
 Q
 ;
EL59 ; Examine every rule that involves Element #59 [SITE FLAGGED FINAL LAB RESULT]
 ;  Called from SCAN+9^OCXOZ01.
 ;
 Q:$G(OCXOERR)
 ;
 D R49R1A^OCXOZ0U   ; Check Relation #1 in Rule #49 'SITE FLAGGED RESULT'
 D R49R2A^OCXOZ0U   ; Check Relation #2 in Rule #49 'SITE FLAGGED RESULT'
 Q
 ;
EL102 ; Examine every rule that involves Element #102 [SITE FLAGGED FINAL IMAGING RESULT]
 ;  Called from SCAN+9^OCXOZ01.
 ;
 Q:$G(OCXOERR)
 ;
 D R49R1A^OCXOZ0U   ; Check Relation #1 in Rule #49 'SITE FLAGGED RESULT'
 D R49R2A^OCXOZ0U   ; Check Relation #2 in Rule #49 'SITE FLAGGED RESULT'
 Q
 ;
EL109 ; Examine every rule that involves Element #109 [SITE FLAGGED FINAL CONSULT RESULT]
 ;  Called from SCAN+9^OCXOZ01.
 ;
 Q:$G(OCXOERR)
 ;
 D R49R1A^OCXOZ0U   ; Check Relation #1 in Rule #49 'SITE FLAGGED RESULT'
 D R49R2A^OCXOZ0U   ; Check Relation #2 in Rule #49 'SITE FLAGGED RESULT'
 Q
 ;
EL129 ; Examine every rule that involves Element #129 [ABNORMAL RENAL RESULTS]
 ;  Called from SCAN+9^OCXOZ01.
 ;
 Q:$G(OCXOERR)
 ;
 D R50R1A^OCXOZ0V   ; Check Relation #1 in Rule #50 'BIOCHEM ABNORMALITIES/CONTRAST MEDIA CHECK'
 Q
 ;
EL130 ; Examine every rule that involves Element #130 [CONTRAST MEDIA ORDER]
 ;  Called from SCAN+9^OCXOZ01.
 ;
 Q:$G(OCXOERR)
 ;
 D R50R1A^OCXOZ0V   ; Check Relation #1 in Rule #50 'BIOCHEM ABNORMALITIES/CONTRAST MEDIA CHECK'
 D R50R2A^OCXOZ0V   ; Check Relation #2 in Rule #50 'BIOCHEM ABNORMALITIES/CONTRAST MEDIA CHECK'
 Q
 ;
EL133 ; Examine every rule that involves Element #133 [NO CREAT RESULTS W/IN X DAYS]
 ;  Called from SCAN+9^OCXOZ01.
 ;
 Q:$G(OCXOERR)
 ;
 D R50R2A^OCXOZ0V   ; Check Relation #2 in Rule #50 'BIOCHEM ABNORMALITIES/CONTRAST MEDIA CHECK'
 Q
 ;
EL63 ; Examine every rule that involves Element #63 [PATIENT HAS RECENT CHOLECYSTOGRAM]
 ;  Called from SCAN+9^OCXOZ01.
 ;
 Q:$G(OCXOERR)
 ;
 D R51R1A^OCXOZ0W   ; Check Relation #1 in Rule #51 'RECENT CHOLECYSTOGRAM ORDER'
 Q
 ;
EL64 ; Examine every rule that involves Element #64 [PHARMACY PATIENT OVER 65]
 ;  Called from SCAN+9^OCXOZ01.
 ;
 Q:$G(OCXOERR)
 ;
 D R53R1A^OCXOZ0W   ; Check Relation #1 in Rule #53 'RENAL FUNCTIONS OVER AGE 65 CHECK'
 Q
 ;
EL65 ; Examine every rule that involves Element #65 [SESSION ORDER FOR ANGIOGRAM]
 ;  Called from SCAN+9^OCXOZ01.
 ;
 Q:$G(OCXOERR)
 ;
 D R54R1A^OCXOZ0W   ; Check Relation #1 in Rule #54 'CONCURRENT LAB ORDERS FOR ANGIOGRAM, CATH - PERIPHERAL'
 Q
 ;
EL66 ; Examine every rule that involves Element #66 [CONTRAST MEDIA ALLERGY]
 ;  Called from SCAN+9^OCXOZ01.
 ;
 Q:$G(OCXOERR)
 ;
 D R55R1A^OCXOZ0W   ; Check Relation #1 in Rule #55 'ALLERGY - CONTRAST MEDIA REACTION'
 Q
 ;
EL67 ; Examine every rule that involves Element #67 [RECENT BARIUM STUDY ORDERED]
 ;  Called from SCAN+9^OCXOZ01.
 ;
 Q:$G(OCXOERR)
 ;
 D R56R1A^OCXOZ0W   ; Check Relation #1 in Rule #56 'RECENT BARIUM STUDY'
 Q
 ;
EL116 ; Examine every rule that involves Element #116 [CLOZAPINE DRUG SELECTED]
 ;  Called from SCAN+9^OCXOZ01.
 ;
 Q:$G(OCXOERR)
 ;
 D R57R1A^OCXOZ0W   ; Check Relation #1 in Rule #57 'CLOZAPINE'
 D R57R2A^OCXOZ0X   ; Check Relation #2 in Rule #57 'CLOZAPINE'
 D R57R3A^OCXOZ0X   ; Check Relation #3 in Rule #57 'CLOZAPINE'
 D R57R4A^OCXOZ0X   ; Check Relation #4 in Rule #57 'CLOZAPINE'
 Q
 ;
EL117 ; Examine every rule that involves Element #117 [CLOZAPINE NO ANC W/IN 7 DAYS]
 ;  Called from SCAN+9^OCXOZ01.
 ;
 Q:$G(OCXOERR)
 ;
 D R57R1A^OCXOZ0W   ; Check Relation #1 in Rule #57 'CLOZAPINE'
 Q
 ;
EL118 ; Examine every rule that involves Element #118 [CLOZAPINE NO WBC W/IN 7 DAYS]
 ;  Called from SCAN+9^OCXOZ01.
 ;
 Q:$G(OCXOERR)
 ;
 D R57R1A^OCXOZ0W   ; Check Relation #1 in Rule #57 'CLOZAPINE'
 Q
 ;
EL114 ; Examine every rule that involves Element #114 [CLOZAPINE ANC < 1.5]
 ;  Called from SCAN+9^OCXOZ01.
 ;
 Q:$G(OCXOERR)
 ;
 D R57R2A^OCXOZ0X   ; Check Relation #2 in Rule #57 'CLOZAPINE'
 Q
 ;
EL119 ; Examine every rule that involves Element #119 [CLOZAPINE WBC < 3.0]
 ;  Called from SCAN+9^OCXOZ01.
 ;
 Q:$G(OCXOERR)
 ;
 D R57R2A^OCXOZ0X   ; Check Relation #2 in Rule #57 'CLOZAPINE'
 Q
 ;
EL115 ; Examine every rule that involves Element #115 [CLOZAPINE ANC >= 1.5]
 ;  Called from SCAN+9^OCXOZ01.
 ;
 Q:$G(OCXOERR)
 ;
 D R57R3A^OCXOZ0X   ; Check Relation #3 in Rule #57 'CLOZAPINE'
 Q
 ;
EL120 ; Examine every rule that involves Element #120 [CLOZAPINE WBC >= 3.0 & < 3.5]
 ;  Called from SCAN+9^OCXOZ01.
 ;
 Q:$G(OCXOERR)
 ;
 D R57R3A^OCXOZ0X   ; Check Relation #3 in Rule #57 'CLOZAPINE'
 Q
 ;
EL141 ; Examine every rule that involves Element #141 [CLOZAPINE ANC >= 1.5 & < 2.0]
 ;  Called from SCAN+9^OCXOZ01.
 ;
 Q:$G(OCXOERR)
 ;
 D R57R4A^OCXOZ0X   ; Check Relation #4 in Rule #57 'CLOZAPINE'
 Q
 ;
EL71 ; Examine every rule that involves Element #71 [AMINOGLYCOSIDE ORDER SESSION]
 ;  Called from SCAN+9^OCXOZ01.
 ;
 Q:$G(OCXOERR)
 ;
 D R59R1A^OCXOZ0X   ; Check Relation #1 in Rule #59 'AMINOGLYCOSIDE ORDER'
 Q
 ;
EL72 ; Examine every rule that involves Element #72 [PATIENT OVER CT OR MRI DEVICE LIMITATIONS]
 ;  Called from SCAN+9^OCXOZ01.
 ;
 Q:$G(OCXOERR)
 ;
 D R60R1A^OCXOZ0Y   ; Check Relation #1 in Rule #60 'CT OR MRI PHYSICAL LIMIT CHECK'
 Q
 ;
EL73 ; Examine every rule that involves Element #73 [CREATININE CLEARANCE ESTIMATE]
 ;  Called from SCAN+9^OCXOZ01.
 ;
 Q:$G(OCXOERR)
 ;
 D R61R1A^OCXOZ0Z   ; Check Relation #1 in Rule #61 'CREATININE CLEARANCE ESTIMATION'
 Q
 ;
EL96 ; Examine every rule that involves Element #96 [CREATININE CLEARANCE DATE/TIME]
 ;  Called from SCAN+9^OCXOZ01.
 ;
 Q:$G(OCXOERR)
 ;
 D R61R1A^OCXOZ0Z   ; Check Relation #1 in Rule #61 'CREATININE CLEARANCE ESTIMATION'
 Q
 ;
EL97 ; Examine every rule that involves Element #97 [RENAL RESULTS]
 ;  Called from SCAN+9^OCXOZ01.
 ;
 Q:$G(OCXOERR)
 ;
 D R61R1A^OCXOZ0Z   ; Check Relation #1 in Rule #61 'CREATININE CLEARANCE ESTIMATION'
 Q
 ;
EL84 ; Examine every rule that involves Element #84 [INPATIENT FOOD-DRUG REACTION]
 ;  Called from SCAN+9^OCXOZ01.
 ;
 Q:$G(OCXOERR)
 ;
 D R62R1A^OCXOZ10   ; Check Relation #1 in Rule #62 'FOOD/DRUG INTERACTION'
 Q
 ;
EL91 ; Examine every rule that involves Element #91 [PATIENT WITH GLUCOPHAGE MED]
 ;  Called from SCAN+9^OCXOZ01.
 ;
 Q:$G(OCXOERR)
 ;
 D R63R1A^OCXOZ10   ; Check Relation #1 in Rule #63 'GLUCOPHAGE - CONTRAST MEDIA'
 Q
 ;
EL106 ; Examine every rule that involves Element #106 [RADIOLOGY PROCEDURE CONTAINS NON-BARIUM CONTRAST MEDIA]
 ;  Called from SCAN+9^OCXOZ01.
 ;
 Q:$G(OCXOERR)
 ;
 D R63R1A^OCXOZ10   ; Check Relation #1 in Rule #63 'GLUCOPHAGE - CONTRAST MEDIA'
 Q
 ;
EL95 ; Examine every rule that involves Element #95 [POLYPHARMACY]
 ;  Called from SCAN+9^OCXOZ01.
 ;
 Q:$G(OCXOERR)
 ;
 D R65R1A^OCXOZ10   ; Check Relation #1 in Rule #65 'POLYPHARMACY'
 Q
 ;
EL86 ; Examine every rule that involves Element #86 [GLUCOPHAGE ORDER]
 ;  Called from SCAN+9^OCXOZ01.
 ;
 Q:$G(OCXOERR)
 ;
 D R67R1A^OCXOZ11   ; Check Relation #1 in Rule #67 'GLUCOPHAGE - LAB RESULTS'
 D R67R2A^OCXOZ11   ; Check Relation #2 in Rule #67 'GLUCOPHAGE - LAB RESULTS'
 Q
 ;
