ABPAPD1 ;PVT-INS PYMT ENTRY FROM END^ABPAPD3; [ 06/21/91  5:56 AM ]
 ;;1.4;AO PVT-INS TRACKING;*0*;IHS-OKC/KJR;JULY 25, 1991
BEG D XIT S U="^"
 S ABPA("HD",1)=ABPATLE,ABPA("HD",2)="Post PAYMENT Data"
 D ^ABPAHD W !,"*"
 S X="CURRENT BATCH FACILITY: "_$P(^DIC(4,ABPASITE,0),"^",1)
 W ?(40-($L(X)/2)),X,?78,"*",! F X=1:1:79 W "*"
 S X="BATCH DATE = "_ABPABDT W !!?(40-($L(X)/2)),X
PAT W !! D ^ABPAPATL
 I $D(ABPATDFN)'=1 D  G FAC^ABPAPD0
 .K ABPA("HD")
 .S ABPA("HD",1)=ABPATLE,ABPA("HD",2)="Post PAYMENT Data"
 .D ^ABPAHD S X="BATCH DATE = "_ABPABDT W !!?(40-($L(X)/2)),X
 G:+ABPATDFN<1 BEG
 L ^ABPVAO(ABPATDFN):3 I '$T D  G PAT
 .W *7,!!?5,"<<< PATIENT RECORD UNAVAILABLE AT THIS TIME -- "
 .W "TRY AGAIN LATER >>>"
HEAD S $P(ABPAX,"=",81)="",ABPAHRN=$P(^ABPVAO(ABPATDFN,0),"^",3)
 S ABPAL=$E($P(^DIC(4,$P(^ABPVAO(DA,0),U,2),0),U),1,19)
 S $P(ABPAXX,"-",81)="" ;,ABPAHD1="POST Payments" D HEADER^ABPAMAIN
 ;W !!,"Patient: ",ABPAPAT_"  ("_ABPAHRN_")",?50,"Facility: "
 ;W $E(ABPAL,1,19)
 K DXS S U="^",DC=1,D0=ABPATDFN W @IOF,! D ^ABPAPDB K DXS G ^ABPAPD2
XIT K ABPARECV,ABPAPD,ABPAENT,ABPADDFN,ABPATDFN,ABPADT,ABPADTD,ABPAPAT,D
 K ABPA,ABPAL,DIC,C,ABPAQKS,ABPAQK,ABPAHRN,DA,J,K,Z,XQH,ABPACOD
 K ABPAC,ABPAI,ABPAXX,ABPAINS,DIE,DR,%DT,ABPAFRDT,ABPATODT,ABPAX
 K ABPACSCR,ABPACHK,GOTCHECK,CLOSE,ABPACCNT,ABPACAMT,ABPAPAMT,ABPAPTOT
 K ABPATPD,ABPACOD,ABPACTOB,ABPACTPD,ABPACURB,ABPADATA,ABPADOS,ABPAJ
 K ABPAJ,ABPAK,ABPAOBAL,ABPAP1,ABPAP2,ABPAP3,ABPAP4,ABPAP5,ABPAPCOD
 K ABPAPOST,ABPAPSDT,ABPAPSSN,ABPAPTR,ABPAT1,ABPAT2,ABPAT3,ABPAT4
 K ABPAT5,ABPAT6,ABPATA2,ABPATA3,ABPATA4,ABPATA5,ABPATA7,ABPATBAL
 K ABPATCNT,ABPAY,ABPAZ,CLOSED,DIR,X Q
