ABPVZILP ;PRINT ALPHA LIST OF INSURERS [ 06/04/91  11:56 AM ]
 ;;2.0;FACILITY PVT-INS TRACKING;*0*;IHS-OKC/KJR;AUGUST 7, 1991
 S X="Print ALPHA LIST OF INSURERS" D SCREEN^ABPVZMM
 S L=0,DIC="^AUTNINS(",BY="[ABPV/ALPHA/LIST]"
 S DHD=$P(^DIC(4,DUZ(2),0),"^",1)_" - INSURANCE CARRIER LIST"
 W ! D EN1^DIP,PAUSE^ABPVZMM K L,DIC,BY,X,DHD
 Q
