BDPKILL ; IHS/CMI/TMJ - KILL ALL BDP VARIABLES ;
 ;;2.0;IHS PCC SUITE;;MAY 14, 2009
 ;
START ;
 K BDPLINKI
 K BDPCOUNT,BDPCPRV,BDPCRPRV,BDPLIEN,BDPLNUM,BDPLPROV,BDPPTNAM,BDPRPRVP,BDPTYPNM,BDPDFN,BDPIEN,BDPTYPEM,BDPCMCK,BDPCOMN,BDPCOMP,BDPRIEN,BDPPIEN
 K BDPLPROV,BDPPAT,BDPPROV,BDPQ,BDPREC,BDPRGTP,BDPRPROV,BDPTRN,BDPTRNA,BDPTYPE,BDPCPRVP,BDPRIEN,BDPRR
 D KILL^AUPNPAT
 D ^XBFMK
 Q
